### ISSUE TITLE
Required validator fails on boolean value

### ISSUE THREAD

**Issue by boskee** [rxweb/rxweb#111]
# Describe the bug

RxwebValidator.required() produces incorrect result if the component's value is false (boolean). That's due to non-strict comparison in isNotBlank method of RegexValidator:

```javascript
  static isNotBlank(value: any, isRemoveSpace: boolean = false): boolean {
    return !isRemoveSpace ?
      (value === 0) || (value != undefined && value != null && value != "") :
      (value === 0) || (value != undefined && value != null && String(value).trim() != "")
  }
```

# Expected Behavior

Required validator should only mark component as invalid if its value is empty, not if it's false (boolean). This can be fixed by changing comparison to strict:

```javascript
  static isNotBlank(value: any, isRemoveSpace: boolean = false): boolean {
    return !isRemoveSpace ?
      (value === 0) || (value !== undefined && value !== null && value !== "") :
      (value === 0) || (value !== undefined && value !== null && String(value).trim() !== "")
  }
```

# To Reproduce

Example using Angular Material:

```html
<mat-slide-toggle formControlName="toggle">Toggle me</mat-slide-toggle>
```

```javascript
    /**
     * Create form
     *
     * @returns {FormGroup}
     */
    createEntityForm(): FormGroup {
        return this._formBuilder.group({
            toggle: [this._entity.toggle, RxwebValidators.required()]
        });
    }
```

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-2feqht

# Package Version
@rxweb/reactive-form-validators@1.5.0

**Comment by ajayojha** [comment]
Thanks @boskee for the detailed information and the suggestion of this issue. I have resolved the issue as per your suggested approach. The working solution will be available in our next release.

**Comment by boskee** [comment]
Thank you @ajayojha - it's a great library, that's been very helpful in my latest project!

**Comment by ajayojha** [comment]
Thank You @boskee - I have released the new version [1.6.0](https://github.com/rxweb/rxweb/releases/tag/v1.6.0).

I have updated the latest version of rxweb in your provided [stackblitz example](https://stackblitz.com/edit/angular-g98hs9?file=src/app/app.component.ts). Now It's working as expected.

Please install the latest version in your project. If you face any issue, please let me know.

**Comment by boskee** [comment]
Thank you so much @ajayojha 

I am currently working on a project, so quick release is amazing. I'm really happy with all your hard work and I am looking forward to contribute something to the project :)

In the meantime I think I've spotted one more issue, which I am now trying to pinpoint before creating a ticket :)

Cheers!

**Comment by ajayojha** [comment]
Thank you very much @boskee for showing interest to contribute to the project.

I am looking forward to your pull request/suggestions to make rxweb framework better :)

**Comment by boskee** [comment]
@ajayojha 

Ok, I am not sure if it's a bug, so I am not creating an issue just yet. Basically conditionalExpression has interesting behaviour. Let's say there's a boolean control "toggle", and another one, which is required if toggle is true.

This won't work (won't fire at all, if you force update on it manually, it will return false:
                    conditionalExpression: (x) => x.toggle

but this will fire automatically when the value of toggle changes and work correctly:
                    conditionalExpression: (x) => x.toggle === true

Perhaps it should be mentioned in the docs?

**Comment by ajayojha** [comment]
> This won't work (won't fire at all, if you force update on it manually, it will return false:
conditionalExpression: (x) => x.toggle

The above-noted scenario won't work because there are lots of other scenarios I have to manage if I covered the above scenario. During design time my initial thought was to put this aside and try to include other scenarios to make this working. 

Thank you for sparking this scenario, I am creating a new issue to "**execute conditional expression without conditional statements**" for my action item.

I completely agree with you to mention in the docs until to make this working.

Thank you to spark this scenario.

**Comment by yoan-asdrubal** [comment]
I having problen with conditionalExpresion inside required validator, I thought it was better to comment here than to open a new issue. My condition involves a formArray and required validator do not apply when i needed. Here an example.
https://stackblitz.com/edit/rxweb-validator-required-error?file=src%2Fapp%2Fapp.component.html
