### ISSUE TITLE
Credit Card Validator Link is not working

### ISSUE THREAD

**Issue by rxcontributortwo** [rxweb/rxweb#13]
# Describe the bug

Credit Card Validator Link is not working. It is displaying 404 Not Found Error.

# Expected Behavior

Validator link must be working, and should navigate to the desired route.

# To Reproduce

Go to https://rxweb.github.io/reactive-form-validators/import-modules.html link and click Credit Card Validator link.

# Url

https://rxweb.github.io/reactive-form-validators/validation-decorators/creditcard.html

# Package Version
@rxweb/<package-name>@<packageversion>

# Browser

Any Browser

**Comment by rxcontributortwo** [comment]
thanks

**Comment by ajayojha** [comment]
Please check on the new site(http://rxweb.io), it is corrected
