### ISSUE TITLE
Discover card validation

### ISSUE THREAD

**Issue by jet8a** [rxweb/rxweb#139]
# Describe the bug
Now only discover cards with 16 numbers are being validated.

The discover card type may include 16-19 numbers
https://www.discoverglobalnetwork.com/downloads/IPP_VAR_Compliance.pdf
https://en.wikipedia.org/wiki/Payment_card_number

**Comment by ajayojha** [comment]
Thanks for the provided link to understand well and I have marked this as a bug. But could you please provide the stackblitz example. Because internally the framework validates both 16 and 19 digit number of discover card.

**Comment by jet8a** [comment]
Please select the discover type and paste this card number 6011345344455683539 or 6011504417586318394 (https://www.freeformatter.com/credit-card-number-generator-validator.html)
https://stackblitz.com/edit/angular-bdkyem

**Comment by ajayojha** [comment]
Thanks, This is a bug and will be resolved in our next release. 

Once I release, will let you know.

**Comment by ajayojha** [comment]
@jet8a We have released the [new version](https://www.npmjs.com/package/@rxweb/reactive-form-validators). I have updated the new version in the provided [stackblitz example](https://stackblitz.com/edit/angular-smkqdn?file=src/app/app.component.ts) and it's working fine. 

Please check and feel free message me if there is an issue :).
