### ISSUE TITLE
'errorMessage' property can be use without the inverted comma in the HTML

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#141]
### Description
As per the concern of @sholkajadav11 (https://github.com/rxweb/rxweb/issues/137#issuecomment-470912676), the errorMessage property should work without the inverted comma. 

The expected solution has been mentioned in the @sholkajadav11 comment.

**Comment by ajayojha** [comment]
@sholkajadav11 We have released this in our 1.8.4 release and working as expected. Now onwards this will not give build prod time error. But you have to change the datatype of your FormGroup.

I am assuming that your current datatype is FormGroup or RxFormGroup instead of this you have to change the datatype of IFormGroup<ModelName>. If you are not using the decorator based validation approach and you are creating a FormGroup through group method then you have to map the datatype of AppFormGroup.

Here is the code :
I have created a User Model 
```js
import { prop } from "@rxweb/reactive-form-validators"

export class User{
  
  @prop()
  fullName:string;

}
```
Now create the FormGorup of the user model
```js
export class UserInfoAddComponent implements OnInit {

    userFormGroup: IFormGroup<User>

    constructor(
        private formBuilder: RxFormBuilder
    ) { }

    ngOnInit() {
        this.userFormGroup  = this.formBuilder.formGroup(User) as IFormGroup<User>;
    }
}
```
On the HTML side.
```html
<form [formGroup]="userFormGroup">
<input type="text" formControlName="fullName" />
{{userFormGroup.controls.fullName.errorMessage}}
</form>
```
Please let me know, if there is any issue.

**Comment by mutualmill** [comment]
When creating the from group as IFormGroup<any> or AppFormGroup<any> the errorMessages is always blank unless I use the RxFormBuilder to create the FormGroup.  I also see that the IFormGroup on RxFormbuilder was changed to look for the AppFormGroup instead of IFormGroup. The IFormGroup appears to hold the IAbstractControl with ErrorMessages property. 

Backend clip:
constructor(
    private formBuilder: FormBuilder,
  ) {
    super();
    this.submissionForm = this.formBuilder.group({
  legalBusinessName: ['', [RxwebValidators.required(), RxwebValidators.maxLength({value: 255})]]
 }) as AppFormGroup<any>;

HTML clip: 
(It does see .errors when empty but no errorMessages exist)

<small class="form-text text-muted" *ngIf="submissionForm.controls?.legalBusinessName?.errors">
                <small class="form-text text-danger" *ngFor="let errorMessage of submissionForm.controls?.legalBusinessName?.errorMessages">{{errorMessage}}<br/></small>
            </small>

**Comment by ajayojha** [comment]
@mutualmill As IFormGroup and AppFormGroup is an interface, not a class object. As per the provided code, you have created the FormGroup through ```FormBuilder``` that returns the ```FormGroup```, not ```RxFormGroup```. The ```errorMessage``` and ```errorMessages``` properties are available in the ```RxFormGroup``` which can be accessed through if you create an object through ```RxFormBuilder```.

You don't have to worry, If you create an FormGroup object through ```RxFormBuilder``` then your current functionality will not break which is related to the FormGroup. Because internally we are not overriding anything on the existing feature of ```FormGroup``` But you will get some extra properties which available in the ```RxFormGroup```.

Feel free to ask a question If you have.
