### ISSUE TITLE
RxFormBuilder does not recognize Date field.

### ISSUE THREAD

**Issue by mparczewski** [rxweb/rxweb#148]
# Describe the bug

During parsing of data object with Date field RxFormBuilder  throws exception.

example:

```
let test = this.formBuilder.group(
      {
        date: new Date()

      }
    )
```

# Expected Behavior

Date field should be recognized add added to RxFormGroup as RxFormControl.

# Package Version
 "@rxweb/reactive-form-validators": "^1.8.4",

**Comment by ajayojha** [comment]
Thanks for reporting this issue. This will resolved in our next release, Will let you know as soon as I release the new version.

**Comment by ajayojha** [comment]
I have released the new version and now it's working as expected. Please refer the working example https://stackblitz.com/edit/angular-gg8jos?file=src%2Fapp%2Fgroup-complete.component.ts
