### ISSUE TITLE
choice validator minLength property is not working correctly

### ISSUE THREAD

**Issue by Srishti-Khandelwal16** [rxweb/rxweb#154]
# Describe the bug

choice validator minLength property is not working while applying along with maxLength.

# Expected Behavior

minLength property should also work along with other properties.

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-jd96rz?file=src%2Fapp%2Femployee-info.model.ts

# Package Version
@rxweb/reactive-form-validators@1.8.5

**Comment by ajayojha** [comment]
This issue has been resolved in our new release 1.8.6. Please refer to this stackblitz example:
https://stackblitz.com/edit/angular-jd96rz?file=src%2Fapp%2Femployee-info.model.ts
