### ISSUE TITLE
error binding strategy of FormControl

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#163]
### Description
As discussed with @zeesulehria on [gitter](https://gitter.im/rxweb-project/rxweb?at=5cb435cf1f6e900d5e3699a9) to extend the feature of error message binding. Currently, dev can bind the error messages conditionally through error or model decorator. But when the throughout application have the same strategy of showing error messages than through error or model decorator approach is a bit clumsy by putting the decorator on every model. Instead of doing this much activity, we can configure the strategy globally and it works accordingly.

### Describe the solution you'd like
I would suggest configuring the error binding strategy globally. 
The error binding strategy should be like as below:
```js
export enum ErrorBindingStrategy{
 none,
 onSubmit,
 onDirty,
 onTouched,
 onDirtyOrTouched
}
```
1. ```ErrorBindingStrategy.none``` : There is no condition to bind the error message, The error messages will be bind as soon as the FormControl is invalid. 
2. ```ErrorBindingStrategy.onSubmit``` : Whenever the ```RxFormGroup``` property ```submitted``` is true then the invalid FormControl error messages will be bind.
3. ```ErrorBindingStrategy.onDirty```: Once the FormControl is dirty, after that invalid FormControl error messages will be bind accordingly.
4. ```ErrorBindingStrategy.onTouched```: Once the FormControl is touched, after that invalid FormControl error messages will be bind accordingly.
5. ```ErrorBindingStrategy.onDirtyOrTouched```: Once the FormControl is Dirty or Touched, after that invalid FormControl error messages will be bind accordingly.

This error binding strategy to be configured through ReactiveFormConfig.
```js
ReactiveFormConfig.set({
reactiveForm:{
errorMessageBindingStrategy: ErrorBindingStrategy.onSubmit
}
})
```
As per the above configured code, The error messages will be bind when the ```RxFormGroup``` property ```submitted``` value is true.

> The by default ```errorMessageBindingStrategy``` is ```ErrorBindingStrategy.none```.

> If someone set the ```ErrorBindingStrategy.OnSubmit``` and one of the form has multiple nested formgroups and formarrays then dev don't need to set the submitted property true of every nested formgroups and formarrays. They just have to set it true of root formgroup. The same value will be applied to the nested formgroups and formarrays

Now, the other question comes, 

**What about the error and model decorator, is there any use of these or not?**

There is no change in the style of working in error and model decorator. let's say for example someone has configured the errorMessageBindingStrategy of onSubmit and one of the form he wants to override the strategy with some conditions through error or model decorator. ultimately error or model decorator override the strategy of particular FormControl or FormGroup.

**Comment by zeesulehria** [comment]
@ajayojha We can also support specifying OR of conditions like, to help user enable error binding at multiple different stages of form

```
ReactiveFormConfig.set({
reactiveForm:{
errorMessageBindingStrategy: ErrorBindingStrategy. onDirty | ErrorBindingStrategy.onSubmit
}
})
```

**Comment by prashantsynsoft** [comment]
Is there any way we can set this.RxFormGroup.submitted = true;
this line globally instead of individual page.
