### ISSUE TITLE
How to test validator with conditional expression?

### ISSUE THREAD

**Issue by Jonah-Jordan** [rxweb/rxweb#169]
I want to test if my form is valid/invalid. I'm using multiple validators like required and minNumber with the conditional expression option. 

The test which is testing the validated control is always valid... I think it's not checking the conditional expression.

**Comment by ajayojha** [comment]
Please refer the spec of required validator (https://github.com/rxweb/rxweb/blob/master/test/reactive-form-validators/validator/required.validator.spec.ts), this includes conditional expression.

If your validator spec is with template, then please let me so that I will share the same.

**Comment by Jonah-Jordan** [comment]
I will explain with a example:
This is my form:
```
this.form = this.fb.group({
      LatestPrice: ['', [RxwebValidators.required({
        conditionalExpression: (x: any) =>
          x.IsValidUser]],
      IsValidUser: [true]
      })})
```

And now I want to test the validation in my spec file:
```
it('form should be invalid on start', () => {
    expect(component.form.controls.LatestPrice.invalid).toBeTruthy();
  });
```

But the control is always valid. So I assume that it is not checking the conditional expression....

**Comment by ajayojha** [comment]
Please try below code :

```js
it('form should be invalid on start', () => {
    component.form.controls.LatestPrice.updateValueAndValidity();
    expect(component.form.controls.LatestPrice.invalid).toBeTruthy();
  });
```
Please let me if this will not work.

**Comment by Jonah-Jordan** [comment]
Thanks, it worked!

**Comment by ajayojha** [comment]
Good. I am closing this ticket as no further action required on this.
