### ISSUE TITLE
add new feature of min and max time validation 

### ISSUE THREAD

**Issue by shahishani06** [rxweb/rxweb#171]
### Description
I have one scenario for check fromTime must less than toTime. i check for this async validator but for this i need to add additional control toTime so i can access other parameter in function for checking other value control or i want relational operator for time

### Describe the solution you'd like
e.g. @async([ isBefore(toTime) ]) 
fromTime:string;

**Comment by ajayojha** [comment]
async validation decorator is used for server-side validation and you can use the current instance object properties like component properties. Relational operator is different than the async. 

can you please share your fromtime and totime value?

**Comment by shahishani06** [comment]
> async validation decorator is used for server-side validation and you can use the current instance object properties like component properties. Relational operator is different than the async.
> 
> can you please share your fromtime and totime value?

fromTime : 12:55
toTime: 3.55

in this case 12.55 is bigger than 3.55 its 24 hours time format

**Comment by ajayojha** [comment]
Thanks, @shahishani06,  Currently there is time validation decorator but not available min and max time validation. 
Will be available in our next release minTime and maxTime validation decorator.
