### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mitulpatel224** [rxweb/rxweb#194]
# Describe the bug
When selecting the file/files having the validations maxFiles I found an error in my console stated "Cannot read property 'length' of undefined" at reactive-form-validators.es5.js:4090

# Expected Behavior
It should allow files as well with RxFormGroup and return proper error message

# To Reproduce
Use form builder of RxFormBuilder
Create formGroup with file control and add validation RxwebValidators.file with maxFiles: 5

# Package Version
@rxweb/reactive-form-validators@^1.9.2

# Browser
Google Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

# Additional Info
Replication:
https://stackblitz.com/edit/angular-8vlt2f?file=src/app/file-add.component.ts
Try to upload file and open Console for the error.

**Comment by ajayojha** [comment]
@mitulpatel224 I have considered this as a bug and this will be fixed in our next release, till the time if you can create a ```FormGroup``` through ```FormBuilder``` then it will work as expected. I have changed in your provided stackblitz code.

Please refer this stackblitz link: https://stackblitz.com/edit/file-validator-alternate?file=src/app/file-add.component.ts

**Comment by mitulpatel224** [comment]
Thanks for update
Also, I fond a form control for the file will have the value having path only and not the whole object for the selected file/files.
Any solutions or there will be an update for the same!

**Comment by ajayojha** [comment]
@mitulpatel224 If you want to store the ```FileList``` object in the FormControl value, then you have to define the attribute ```[writeFile]="true"``` on the ```input``` file element. The HTML code like as below:
```html
<input type="file" [writeFile]="true" formControlName="totalImageFiles" class="form-control" multiple />
```
The same HTML code, I have updated in the stackblitz example, Please refer the same:  https://stackblitz.com/edit/file-validator-alternate?file=src%2Fapp%2Ffile-add.component.html

**Comment by ajayojha** [comment]
@mitulpatel224 I have released the new version(1.9.3) and the issue has been resolved in this release. Please update your project package.

Please let me know if there is any issue :).

**Comment by jeck5895** [comment]
Hello nice library! But I'm facing an issue it's not working with Bootstrap custom file Input I upload 4 files and the form is still valid?
form.component.html
`<input
        [writeFile]="true"
        type="file"
        formControlName="files"
        #fileInput
        (change)="onFileChange($event)"
        class="custom-file-input"
        id="customFileLangHTML"
        accept="application/pdf,video/mp4,video/x-m4v,video/*"
        multiple
      />`

form.component.ts
`this.articleForm = this.formBuilder.group({
      title: ["", Validators.required],
      paragraph: ["", Validators.required],
      category: ["", Validators.required],
      visibility: ["private", Validators.required],
      tags: ["", Validators.required],
      files: ["", [Validators.required, RxwebValidators.file({ maxFiles: 2 })]],
      uploadType: ["attach"],
      url: ["", [Validators.required, Validators.pattern(this.urlRegex)]]
    });`

**Comment by ajayojha** [comment]
@jeck5895 Thanks, Bootstrap library is creating a custom element and working the same, due that it's not working. I would suggest Please share the library web link or package name so I will check in detail :).

**Comment by jeck5895** [comment]
Hello my bad it's working. I figured out that I have condition on validating fields. It's working fine now. My new problem is there's an error on my console
`core.js:5873 ERROR Error: Pass the property of 'value' with value in the NumberConfig, otherwise it won't work.
    at rxweb-reactive-form-validators.js:2256
    at Array.forEach (<anonymous>)
    at checkRequiredProps (rxweb-reactive-form-validators.js:2254)
    at configProvider (rxweb-reactive-form-validators.js:2249)
    at getConfigObject (rxweb-reactive-form-validators.js:2231)
    at rxweb-reactive-form-validators.js:2528
    at RxFormControlDirective.validation (rxweb-reactive-form-validators.js:4284)
    at RxFormControlDirective.validate (rxweb-reactive-form-validators.js:4866)
    at forms.js:1583
    at forms.js:1528`

**Comment by jeck5895** [comment]
Any idea? That error appears when I navigate to another page which has form but doesn't use the rxweb validator.

**Comment by ajayojha** [comment]
Which version are you using?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeck5895** [comment]
"@rxweb/reactive-form-validators": "^1.9.9-beta4",

**Comment by jeck5895** [comment]
that's the default package when I run the installation from the docs

**Comment by jeck5895** [comment]
I tried figuring out what's the problem and I think it's related to one of my custom fields which is
<ngx-intl-tel-input></ngx-intl-tel-input> 

When I'm commenting that field out error is gone in the console. Any Idea?

**Comment by ajayojha** [comment]
Which validator are you using?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeck5895** [comment]
see on that page I'm not using any validation with rxweb on my form. I figured out that when I'm commenting <ngx-intl-tel-input> element error is gone. 

this is the other library that cause the error
`<ngx-intl-tel-input
      [cssClass]="'form-control'"
      [preferredCountries]="preferredCountries"
      [enableAutoCountrySelect]="false"
      [enablePlaceholder]="true"
      [searchCountryFlag]="true"
      [searchCountryField]="[SearchCountryField.Iso2, SearchCountryField.Name]"
      [selectFirstCountry]="false"
      [selectedCountryISO]="CountryISO.Philippines"
      [maxLength]="15"
      [tooltipField]="TooltipLabel.Name"
      [phoneValidation]="true"
      [separateDialCode]="separateDialCode"
      name="phone"
      formControlName="phone"
    >
    </ngx-intl-tel-input>`

below is my form. it has no rxweb validation because validation is just required.

`this.userForm = this.formBuilder.group(
      {
        firstName: ["", Validators.required],
        lastName: ["", Validators.required],
        client: ["", Validators.required],
        role: ["", Validators.required],
        // projects: ["", Validators.required],
        primarySkills: ["", Validators.required],
        secondarySkills: [""],
        email: [
          "",
          [
            Validators.required,
            Validators.pattern("^[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,4}$")
          ]
        ],
        phone: ["", Validators.required],
        expiration: ["", Validators.required]
        // photo: ["", Validators.required]
      },
      {
        validators: DomainValidation.validateEmailDomain
      }
    );`

**Comment by jeck5895** [comment]
Can you tell how can I set this NumberConfig based on this error
![image](https://user-images.githubusercontent.com/22309354/77875389-80c60f00-7282-11ea-9a09-b46bee2e1083.png)

**Comment by ajayojha** [comment]
@jeck5895 The error is coming due to ```[maxLength]``` attribute, I will fix this issue in the coming release.

**Comment by jeck5895** [comment]
Thank you @ajayojha. just wondering why is it validating a field where I didn't include any rxweb validation?.

**Comment by jeck5895** [comment]
Based on my observation it's setting an error required to true but the status of control itself is VALID

![image](https://user-images.githubusercontent.com/22309354/77984370-f3e38a00-7343-11ea-970d-7ca201dfc303.png)

**Comment by ajayojha** [comment]
> Thank you @ajayojha. just wondering why is it validating a field where I didn't include any rxweb validation?.

It's conflicting with your component input parameter, if you use ```maxLength``` attribute in the template like this ```[maxLength]="{value:50}" then it won't give you the error.

**Comment by ajayojha** [comment]
> Based on my observation it's setting an error required to true but the status of control itself is VALID
> 
> ![image](https://user-images.githubusercontent.com/22309354/77984370-f3e38a00-7343-11ea-970d-7ca201dfc303.png)

Please share the stackblitz url. for quicker answer of your query I would suggest please join our gitter channel https://gitter.im/rxweb-project/rxweb , I am fine in both ways :).

**Comment by jeck5895** [comment]
> > Thank you @ajayojha. just wondering why is it validating a field where I didn't include any rxweb validation?.
> 
> It's conflicting with your component input parameter, if you use `maxLength` attribute in the template like this ```[maxLength]="{value:50}" then it won't give you the error.

Yeah I guess maxlength validation of <ngx-intl-tel-input> conficted with the validation. I'm not sure if it would affect my validation because this input is also a library with their validation of telephone numbers., but I've change the value as you said and the error was gone.

` <ngx-intl-tel-input
      [cssClass]="'form-control'"
      [preferredCountries]="preferredCountries"
      [enableAutoCountrySelect]="false"
      [enablePlaceholder]="true"
      [searchCountryFlag]="true"
      [searchCountryField]="[SearchCountryField.Iso2, SearchCountryField.Name]"
      [selectFirstCountry]="false"
      [selectedCountryISO]="CountryISO.Philippines"
      [maxLength]="{ value: 15 }"
      [tooltipField]="TooltipLabel.Name"
      [phoneValidation]="true"
      [separateDialCode]="separateDialCode"
      name="phone"
      formControlName="phone"
    >
    </ngx-intl-tel-input>`
