### ISSUE TITLE
Button text in UI should be able to updated conditionally

### ISSUE THREAD

**Issue by Srishti-Khandelwal16** [rxweb/rxweb#195]
### Description

Button text in UI should be able to updated conditionally. 
**For Example:**
In this [stackblitz](https://stackblitz.com/edit/angular-tdmmpv?file=src%2Fapp%2Fselectcheckbox.model.ts), I am changing the button text conditionally, but it is not reflecting in the UI.

### Describe the solution you'd like

Button text should be able to change conditionally when i try to change it through a click event.

**Comment by ajayojha** [comment]
This has been resolved in 0.0.2 release, please update your project package.
