### ISSUE TITLE
Hostnames with no suffix fail validation when using RxwebValidators.url()

### ISSUE THREAD

**Issue by LukeIST** [rxweb/rxweb#196]
# Describe the bug
If a hostname is entered into a form input that does not contain a suffix it will fail validation when using the validator RxwebValidators.url(). Hostnames with no suffix are commonly used when developing locally ex. (http://localhost:8080) or for intranet servers ex. (https://localserver)

# Expected Behavior
Hostnames with no suffix should be considered a valid url either by default or with an optional setting. 

# To Reproduce
See Stackblitz

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/rxweb-validators-url-failing

# Package Version
@rxweb/reactive-form-validators@1.9.2

**Comment by ajayojha** [comment]
@LukeIST Thanks for reporting this issue, this will resolved in our next release.

**Comment by ajayojha** [comment]
I have released the new version 1.9.4 and the feature request has been resolved. The documentation will be available tomorrow. please refer the same.
