### ISSUE TITLE
Hidden Brains of rxweb 

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#198]
Hello @zeesulehria , @manudss and @sholkajadav11

I hope you are doing well.

It was pending since long to show your efforts on rxweb to the community. I am planning to add your names with your contributions information on the rxweb site.

Have a look below image.

![image](https://user-images.githubusercontent.com/20392302/64027524-83328000-cb5e-11e9-9613-a712c510744a.png)

Feel free to share your suggestions on this. I am looking forward to your response.

**Comment by manudss** [comment]
Hi, 
Thanks, it looks goods. 

Just one things for me : "Steban" is a part of my familly name. 
I would be better to use "Emmanuel has suggested ..." my first name. 

And for the feature, it would be better : "Dynamic validation config. "

Thanks. 

Emmanuel

**Comment by ajayojha** [comment]
Thanks @manudss , Updated the content as per your suggestion, you can refer this link(https://new.rxweb.io/contributors) with changes.

**Comment by ajayojha** [comment]
Thank you guys, sharing the feedback on this ticket/gitter. The page has been available on rxweb.io site.
