### ISSUE TITLE
Angular 4.2.3 compability

### ISSUE THREAD

**Issue by oskarm91** [rxweb/rxweb#20]
When I try to use 1.1.5 version of your package I got:
ERROR in Error: Metadata version mismatch for module .../node_modules/@rxweb/reactive-form-validators/rxweb-reactive-form-validators.d.ts, found version 4, expected 3, resolving symbol UiModule in <path-to-my-app>/src/app/ui/ui.module.ts, resolving symbol UiModule in <path-to-my-app>/src/app/ui/ui.module.ts ...

Can you point what can be wrong. Is it really incompatible with ng4?
ps. RxReactiveFormsModule is exported from submodule but when I import it directly in the AppRootModule it works.

**Comment by ajayojha** [comment]
We have released a new version(@rxweb/reactive-form-validators@1.1.5-beta.3) of rxweb. That is compatible with angular4 projects. You can check the working example of angular4 project  sample on this link : https://stackblitz.com/edit/rxweb-angular4-compatible-validator-example?file=src/app/app.component.ts

Please let me know, if there is any issue of rxweb in your project or if there is any new enhancement in our decorators, feel free create the issue.

**Comment by ajayojha** [comment]
I am not getting your point, please share your small code sample(not in detail), otherwise provide me more information.
second option is :  the stackblitz link I have provided in the above message, do the changes in that project as per your actual implementation of rxweb in your project and provide me the stackblitz link.

**Comment by ajayojha** [comment]
I am closing this issue because I don't see any action on this issue. Feel free to create a new issue if face any issue.
