### ISSUE TITLE
type `a`  is not working in additionalConfig

### ISSUE THREAD

**Issue by Ushmidave** [rxweb/rxweb#203]
# Describe the bug
Type `a` is not working as link in additionalConfig 

# Expected Behavior
Link should be created while added a control as `a` in additionalConfig

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-wavunp?file=src/app/custom.component.ts

# Package Version
@rxweb/reactive-dynamic-forms@0.02

**Comment by ajayojha** [comment]
I have updated the below code in the provided example. It's working fine now.
```js
href:'https://www.google.com',
```
