### ISSUE TITLE
property 'class' is not being defined in @overrideProps

### ISSUE THREAD

**Issue by Ushmidave** [rxweb/rxweb#206]
# Describe the bug

class property is not being defined while using @overrideProps in dynamic forms.

# Expected Behavior
class should be defined and changed based on server returned condition

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-h66k8s-failyu?file=src/app/override-props-complete.component.ts

# Package Version
@rxweb/reactive-dynamic-forms@0.0.3

**Comment by ajayojha** [comment]
@Ushmidave  Please refer to this ticket(https://github.com/rxweb/rxweb/issues/210) for more information. Hence I am closing this ticket as no further action required from my end.
