### ISSUE TITLE
get() method of 'RxHttp' is not working without get({})}

### ISSUE THREAD

**Issue by Ushmidave** [rxweb/rxweb#207]
# Describe the bug
get() method of RxHttp is not working without get({})

# Expected Behavior
get() method of RxHttp should work without get({})

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-wd24kr-xauyhb?file=src/app/base.component.ts

# Package Version
@rxweb/http@0.0.0-3

**Comment by ajayojha** [comment]
The issue has been resolved 0.0.0-4 version.
