### ISSUE TITLE
Angular 4 support, metadata version mismatch: @rxweb/reactive-dynamic-forms/rxweb-reactive-dynamic-forms.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by iranicus** [rxweb/rxweb#208]
## Statement
Hello there, I've been trying to get the framework to work with Angular 4 but have thus been unable to, currently when performing a 

> ng serve --aot

 I am given the following error:

> Metadata version mismatch for module ...@rxweb/reactive-dynamic-forms/rxweb-reactive-dynamic-forms.d.ts, found version 4, expected 3

I am confused on this as having read the metadata.json for this library it sure enough supports angular 4 but for some reason 3 is expected instead? It dawns on me that there is something in my package.json that is likely causing this issue:

**package.json**
```
{
  "name": "angular",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "^4.1.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@rxweb/reactive-dynamic-forms": "0.0.0-3",
    "@rxweb/reactive-form-validators": "^1.9.2",
    "core-js": "2.5.3",
    "rxjs": "5.5.2",
    "webpack": "3.10.0",
    "zone.js": "0.8.29"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.10",
    "@angular/compiler-cli": "4.4.6",
    "@angular/language-service": "4.4.6",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "7.0.52",
    "codelyzer": "^3.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "7.0.0",
    "tslint": "5.3.2",
    "typescript": "3.4.3"
  }
}
```

## Expectation
That angular 4 will compile and the app run without errors with the currently released versions of @rxweb/reactive-dynamic-forms & @rxweb/reactive-form-validators

If someone could take a look it might be an obvious issue,
ty :0)

**Comment by ajayojha** [comment]
@iranicus It's a metadata issue(@rxweb/reactive-form-validators), as the package has been released with the metadata 4 version and your project supports metadata3, I will release the new version with the support of metadata 3 version.

**Comment by iranicus** [comment]
@ajayojha Thanks!

**Comment by iranicus** [comment]
@ajayojha Just wanted to update you, we will be upgrading to Angular 8 early next year while updating various aspects of our architecture. I will therefore revisit the use of rxweb when that time comes. Thanks for your help.
