### ISSUE TITLE
Incorrect example of checkbox (Single Select)

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#209]
# Description
The provided example is binding a collection in the checkbox, But the actual definition of the example is to store non-array value in the FormControl.

# Location
**example [link](https://new.rxweb.io/reactive-dynamic-forms/controls/checkbox#singleselect)**
It should bind a single object instead of an Array.

**Comment by Ushmidave** [comment]
This issue has been resolved and changes are updated on https://new.rxweb.io/reactive-dynamic-forms/controls/checkbox#singleselect

**Comment by ajayojha** [comment]
Thanks @Ushmidave
