### ISSUE TITLE
Default value placeholder have not set properly

### ISSUE THREAD

**Issue by kunal-Rojasara** [rxweb/rxweb#210]
# Description

https://stackblitz.com/angular/aylgxaybjjx?file=src%2Fapp%2Foverride-props-complete.component.ts

in this example lastName placeholder not set default value "Enter Lastname" 

Describe the bug you found.

# Location
Dynamic forms > Override Props example

Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

**Comment by ajayojha** [comment]
I working fine, I have changed the code in the provided stackblitz example, please refer the same. 

The code which I have changed is below
# before
```js
lastName: {
    placeholder: {
      get: function () {
         if (this.controlsConfig.firstName.value)
        return "Enter your LastName"
         }, set: function () {
        { this.overrides.placeholder = "Enter LastName"; }
      }
    }
  }
```

# After
```js
lastName: {
    placeholder: {
      get: function () {
         if (this.controlsConfig.firstName.value)
        return "Enter your LastName"
        return this.overrides.placeholder
      }, set: function () {
        { this.overrides.placeholder = "Enter LastName"; }
      }
    }
  }
```

Hence, I am closing this ticket as no further action required on this ticket.
