### ISSUE TITLE
Navigation issue in checkbox controls page

### ISSUE THREAD

**Issue by kunal-Rojasara** [rxweb/rxweb#212]
Next slide button on checkbox controls page is not working properly.

Currently it redirects to Uibindings > Static binding > description page

Actually it should redirect to Uibindings > controls > class page

URl: 

https://new.rxweb.io/reactive-dynamic-forms/controls/checkbox

**Comment by Ushmidave** [comment]
This issue has been resolved and updated on https://new.rxweb.io/reactive-dynamic-forms/controls/checkbox

**Comment by ajayojha** [comment]
@kunal-Rojasara I hope your state concern has been resolved. Feel free to open a new ticket if you found anything in the doc which is not working properly. I highly appreciate your suggestion.
