### ISSUE TITLE
Can we set header value for particular URL

### ISSUE THREAD

**Issue by rxdotnetdev37** [rxweb/rxweb#213]
I am using @rxweb/http package in Sample Project. 
It is very advanced and easy to implement as compared to others, however, while exploring this package I found that if user want to set header value for particular API(or API URL), 
then the user may need to add their custom logic to achieve this.
So can package have the facility where user don't need to add their customize code and
can be managed from @rxweb/http package.

Here are the few examples where the user doesn't need to send an AuthorizationToken in Header:
1: `api/Login`
2: `api/ForgotPassword`

Here are the few example where user need to send an AuthorizationToken in Header:
1: `api/RecoveryPassword`

**Comment by ajayojha** [comment]
I am closing this issue because this issue is duplicate, please refer this ticket https://github.com/rxweb/rxweb/issues/214 for the status of the feature request
