### ISSUE TITLE
Form Aligned

### ISSUE THREAD

**Issue by elvispdosreis** [rxweb/rxweb#217]
## Describe the problem statement?

i need to access values inside a form aligned in another group for example x.adrress.number

in group1 access group address
` {conditionalExpression:(x)=> x.adrress.number === 1}`

```
ngOnInit() {
        this.userInfoFormGroup = this.formBuilder.group({
          firstName:['',[RxwebValidators.required()]],
          group1: this.formBuilder.group({
                    lastName:['',[RxwebValidators.required({conditionalExpression:(x)=> x.firstName == 'John'})]]
          })          
        });
 }
```

## Package version
@rxweb/last

**Comment by ajayojha** [comment]
@elvispdosreis You can use that in existing release as well by adding the additional parameter in the ```condtionalExpression``` function. 
Here is code :
```js
{conditionalExpression:(x,y)=> x.adrress.number === 1}
```
Basicly ```x``` parameter is used for current FormGroup value and ```y``` parameter is used for root FormGroup value.

**Comment by ajayojha** [comment]
I hope your concern has been resolved with the suggested approach, I am closing this ticket, if still, you have any question, please open a new ticket.
