### ISSUE TITLE
Address bar shows complete data in query string while submitting dynamic form.

### ISSUE THREAD

**Issue by hinalborad** [rxweb/rxweb#219]
## Describe the problem statement?
This issue is only for Dynamic form. 

![error](https://user-images.githubusercontent.com/16860739/66123926-bd30ef00-e600-11e9-93e9-ea0b20ea5464.PNG)

**Comment by ajayojha** [comment]
@hinalborad would be great if you share a little bit more information.

**Comment by hinalborad** [comment]
kindly see the screenshot:
![error](https://user-images.githubusercontent.com/16860739/66183935-20219500-e698-11e9-9bd9-0f819e75867e.PNG)

**Comment by ajayojha** [comment]
@hinalborad With the provided information, I can't gauge the issue, would be great if you share minimal reproduce issue step as well as stackblitz example.

**Comment by ajayojha** [comment]
@hinalborad With limited information, I can't solve the issue. Whenever you have time please create a new ticket with detail information as per our bug template.
