### ISSUE TITLE
Group Validade

### ISSUE THREAD

**Issue by elvispdosreis** [rxweb/rxweb#220]
## Describe the problem statement?
I have a form with several steps each step is in a group, it is possible to check the validation by group

## Package version
@rxweb/last

**Comment by ajayojha** [comment]
@elvispdosreis Yes, it is possible with the decorator based validation. Are you using decorator based validation or validator based validation?

**Comment by elvispdosreis** [comment]
based on validator, and I'm just using "RxwebValidators" with angular "FormBuilder"

**Comment by ajayojha** [comment]
I was thinking of the alternate approach in RxwebValidators and found the way to work through steps forms. Create a ```type``` property in root formgroup and set the conditional expression in every FormControl.
Here is the code snippet.

```js
this.userFormGroup = this.formBuilder.group(
{
type:'step1',
firstStep:this.formBuilder.group({
name:['',RxwebValidators.required({conditionalExpression:(x,y)=>y.type == 'step1'}]
}),
secondStep:this.formBuilder.group({
city:['',RxwebValidators.required({conditionalExpression:(x,y)=>y.type == 'step2'})]
})
}
)
```
On the step changed event you can set the value in ```type``` FormControl based upon the active tab.

Please let me know if there is any confusion.

**Comment by ajayojha** [comment]
I hope your concern has been resolved with the provided information. Any question please create a new ticket.
