### ISSUE TITLE
http path is not working in parent abstract class 

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#221]
while setting http path for server side API in parent abstract class shows config error (Please see the screenshot below) 
, its working fine in child class.  

![Screenshot (13)](https://user-images.githubusercontent.com/46072385/66183990-45ae9e80-e698-11e9-986e-572373bb7c81.png)

**Comment by ajayojha** [comment]
@rachanachag Would be great if you share the stackblitz not working example.

**Comment by ajayojha** [comment]
@rachanachag Whenever you have time to provide the example at that time please create a new ticket with detailed information, I would be happy to resolve the same., Currently, I don't see any further action on this ticket due to limited information so that I am closing this ticket.
