### ISSUE TITLE
Form Dynamic

### ISSUE THREAD

**Issue by elvispdosreis** [rxweb/rxweb#222]
## Describe the problem statement?
Sounds crazy but I would like to know if I can relate my own components or third party components, for example

`type:" ng-select ",`

for example for a country component I create a component with my asynchronous queries and relate it to * dynamic-forms * for form creation

```
serverData = [
    {
        name: "email",
        type: "text",
        ui: {
            viewMode: {
                advance: {
                    div: ["col-md-6","col-sm-6"]
                }
            },
            label: "Email",
            placeholder: "Email",
        }
    }
];
```

```
serverData = [
    {
        name: "email",
        type: "my_custom_component",
        ui: {
            viewMode: {
                advance: {
                    div: ["col-md-6","col-sm-6"]
                }
            },
            label: "Email",
            placeholder: "Email",
        }
    }
];
```

## Package version
@rxweb/@last

**Comment by ajayojha** [comment]
@elvispdosreis You can use your custom component in dynamic forms, Please refer this stackblitz example (https://stackblitz.com/edit/angular-hrvzsf-p9c9ba?file=src/app/dynamic-complete.component.ts).

Any Question please let me know.

**Comment by ajayojha** [comment]
I hope your concern has been resolved with the provided example. I am closing this ticket as I don't any further action on this.
