### ISSUE TITLE
Pattern - Argument of type is not part of panel config

### ISSUE THREAD

**Issue by Adam-Kernig** [rxweb/rxweb#234]
# Describe the bug
https://www.npmjs.com/package/@rxweb/reactive-form-validators#pattern
Following the documentation here throws a ts error:

`{ pattern: { 'onlyAlpha': RegExp; }; }' is not assignable to parameter of type 'PatternConfig'`

my code snippet:
 details: this.formBuilder.control('', [
                RxwebValidators.pattern({pattern:{'onlyAlpha': /^[A-Za-z]+$/} })
]),

# Expected Behavior
To respond correctly as the documentation states

# FIXED
The documentation on NPM DOES NOT match the documentation on the actuall website.
I would recomend that gets updated as developers will use npms docs more than the website:
https://rxweb.io/form-validations/pattern/validators

**Comment by ajayojha** [comment]
Thanks for reporting this :). This opens up for me to review others as well and do the necessary changes.
