### ISSUE TITLE
Decimal with numeric validator bug with LOCAL_ID = 'fr'

### ISSUE THREAD

**Issue by luchidalgo** [rxweb/rxweb#235]
# Describe the bug

When I change LOCALE_ID to 'fr' with : 
       ` { provide: LOCALE_ID, useValue: 'fr' }`
The numeric validator create error with decimals with 

# Expected Behavior

I should can use , or . in numeric field

# To Reproduce

Use numeric validator with allowDecimal: true and set LOCAL_ID to fr
Then try validation with 23,30 or 23.30 errors everytime

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/reactive-form-validators@latest

**Comment by ajayojha** [comment]
@luchidalgo I have created a stackblitz example it's working fine, please refer this link : https://stackblitz.com/edit/numeric-validator-fr?file=src/app/user-info.model.ts . Would like to know the steps when it breaks. Provided steps are working fine in the example.

**Comment by luchidalgo** [comment]
Sorry, I didn't mention that you have to put `type="number"` on field to see the bug

**Comment by luchidalgo** [comment]
I had to add `ReactiveFormConfig.set({"allowDecimalSymbol": "."});` in app.module to make it works

**Comment by ajayojha** [comment]
Thanks, I am closing this ticket, as no further action needed on this ticket. Feel free to create another ticket if there is any issue.
