### ISSUE TITLE
Supported vanilla Angular FormArray with a new component called RxFormArray

### ISSUE THREAD

**Issue by OrlandoMarciales** [rxweb/rxweb#237]
### Description
Actually **RxFormGroup** and **RxFormBuilder** manage **FormArray** as a simple **Array** on form declaration.

This "FormArray" is binded to template with FormGroup directive, not with FormArrayName directive.

### Describe the solution you'd like
Build a new component called RxFormArray extended from [FormArray](https://angular.io/api/forms/FormArray), with the support for rxweb-validators. This implies RxFormGroup and RxFormBuilder must also support **FormArray** & **RxFormArray**.

This is because also angular templates, actually support [FormArrayName ](https://angular.io/api/forms/FormArrayName)directive, this feature must have to be support for **RxFormArray**.

**Comment by ajayojha** [comment]
Sorry @OrlandoMarciales I am not getting exactly what you are expecting, Let me share my understanding, We have already defined a class of RxFormArray which is extended with the FormArray and on the template side the FormArrayName works well if the object RxFormArray.

**Comment by OrlandoMarciales** [comment]
A ok, so you are saying, RxFormArray exist, can you tell me which version support this? I'm already using 1.9.3

**Comment by ajayojha** [comment]
Which validation approach you are following, decorator or validator, if you are creating a form group through “formgroup” method of rxformbuilder, then it automatically creates a rxformarray if there is a array object is available.
Please refer the proparray example of the doc.
Any co confusion please let me know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
@OrlandoMarciales  It's available in 1.9.3 version, please refer this doc : https://rxweb.io/decorators/propArray/decorators . If you are expecting something different then please let me know.

**Comment by ajayojha** [comment]
I am closing this ticket as no further action required on this ticket. Feel free to open a new ticket if you have any further questions/suggestions :)
