### ISSUE TITLE
Numeric validator issues with dots

### ISSUE THREAD

**Issue by luchidalgo** [rxweb/rxweb#239]
# Describe the bug

When I try to type a number with decimal, the numeric validator reject the '.', I have to type twice the '.' to make it appear

# Expected Behavior

The '.' for decimal separator should appear the first time I type '.'

# To Reproduce

Use decimal validator with a field empty at start, then try to type a decimal value

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/numeric-validator-fr-5scgcw

# Package Version
@rxweb/reactive-form-validators@latest

**Comment by ajayojha** [comment]
@luchidalgo  Sorry for the late reply, I was trying to reproduce your mentioned case But didn't get success. I have two questions:

1. Is your locale is `fr`?
2. Can you please provide me the value which you are entering.

**Comment by ajayojha** [comment]
@luchidalgo  I am closing this ticket, as there is no complete information available. Whenever you have time please reopen this ticket with an answer to my questions.
