### ISSUE TITLE
@patern validation decorator bug when class extends other class

### ISSUE THREAD

**Issue by luchidalgo** [rxweb/rxweb#240]
# Describe the bug

When I use the @pattern validator decorator in base class that inherit from other class, the decorator "loose" the Regex and add errors to console 

# Expected Behavior

Decorators should work with child classes

# To Reproduce

use the stackblitz below

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/numeric-validator-fr-chgge3

# Package Version
@rxweb/rxweb@lastest

**Comment by ajayojha** [comment]
@luchidalgo The issue has been resolved in 1.9.7 release. Please update the package. If you face any problem then please let me know.
