### ISSUE TITLE
Sorting icons is missing on the @rxweb/grid

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#245]
# Describe the bug

When I try to sort the list I have observe that the sorting Icons is missing on the column name of the Rx-grid when the list page loaded first time. It shows only when I click the column name first.

# Expected Behavior

Grid sorting icons should be visible at the time of page load.

# To Reproduce

1. Bind grid with any tables of your Database.
2. Then set Allow Sorting True under database models folder in v-{entity-name}-base.ts file

> allowSorting: true

`import { prop, propObject, propArray, required, maxLength, range } from "@rxweb/reactive-form-validators"
import { gridColumn, actionColumn } from "@rxweb/grid"

@actionColumn({
    allowSorting: true,
    configuredTemplate: { templateName: 'action' }, columnIndex: 3, headerTitle: "Action"
    
})`

3. Observe Grid sorting behavior.

# Url (stackblitz or plunker or other)

Before Click: [http://prntscr.com/q3o0gl](url)
After Click: [http://prntscr.com/q3o1s4](url)
# Package Version
@rxweb/grid

**Comment by ajayojha** [comment]
I have resolved the bug. Please update the latest package of "@rxweb/grid".
