### ISSUE TITLE
@Rx-grid loading issue with Action columns.

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#246]
# Describe the bug

Rx-grid does not load properly if i remove sorting on Action column.

# Expected Behavior

Rx-grid should load properly if i remove sorting on Action column.

# To Reproduce
1. Bind grid with any tables of your Database.
2. Then set allowSorting false under database models folder in v-{entity-name}-base.ts file

> allowSorting: False

`import { prop, propObject, propArray, required, maxLength, range } from "@rxweb/reactive-form-validators"
import { gridColumn, actionColumn } from "@rxweb/grid"

@actionColumn({
allowSorting: false,
configuredTemplate: { templateName: 'action' }, columnIndex: 3, headerTitle: "Action"

})`

3. Observe Grid sorting behavior.

# Url (stackblitz or plunker or other)

[http://prntscr.com/q3t4zu](url)

# Package Version
@rxweb/grid

**Comment by ajayojha** [comment]
The issue has been resolved, please update the latest version.
