### ISSUE TITLE
Localization is not working under setting or gear icon of the grid

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#247]
# Describe the bug
When I apply Localization in the system the same is not reflecting in the setting icon panel for column name text of the grid. 

# Expected Behavior
Localization should works throughout the system.

# To Reproduce
1. Bind grid with any tables of your Database.
2. Click on the setting icon which manage columns on the grid based on selection.
3. Observe column name text.

# Url (stackblitz or plunker or other)
[http://prntscr.com/q3tb6r](url)

# Package Version
@rxweb/localization

**Comment by ajayojha** [comment]
Outside grid content can't be managed through our grid. Hence I am closing this issue.
