### ISSUE TITLE
Multi select checkbox on the @Rx-grid

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#250]
### Description
Can we have a checkbox in Rx-grid rows to select / deselect all rows and does bulk update or bulk delete operation after that.

### Describe the solution you'd like
Please have a look into this reference url: [http://prntscr.com/q4v0nn](url)

**Comment by ajayojha** [comment]
This feature is available in the new release, Please use below code for checkbox selection.

You have to create a custom template and register the same.

The custom template is as below:

```js
export const CHECKBOX_GRID_TEMPLATE: TemplateConfig = {
    div: {
        class:["form-check","abc-checkbox"],
        childrens:[{
            input:{
                class:["form-check-input"],
                event:{
                    input:function(e,x,element){
this[e.name] = element.srcElement.checked;
                    }
                },
                attributes:{
                    type:"checkbox",
                    checked:function(e){return this[e.name];},
                    
                }
            }
        }]
    },
}
```
