### ISSUE TITLE
Auto focus on the field of the Add or Edit page.

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#251]
### Description
Can we have an auto focus on the very first field when user navigate to Add or Edit page.
Related to the package: @rxweb/reactive-form-validators

### Describe the solution you'd like
Please have a look into this url: [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_autofocus](url)

**Comment by ajayojha** [comment]
Autofocus cannot be possible through '@rxweb/reactive-form-validators' but this can be achieved through our "@rxweb/angular" package.

**Comment by ajayojha** [comment]
The feature is available in the latest release, please take to update the package of "@rxweb/angular".
