### ISSUE TITLE
Need row navigation control on the @rxweb\grid

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#252]
### Description
Can we have a navigation control on the first column of the Rx-grid to navigate user to record details or edit page.

### Describe the solution you'd like
Please have a look into the url: [http://prntscr.com/q4x76x](url)

**Comment by ajayojha** [comment]
This feature is available in the grid, you can achieve this through 'onRowSelect'. But I am marking this as the issue because the event will fire on the action column as well, which is incorrect.

**Comment by ajayojha** [comment]
I have resolved the issue in the latest release, please update your package.
