### ISSUE TITLE
Component generation issue @rxwebcore

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#253]
# Describe the bug
When I generating component for client side then command also generate query param instead of param in edit component.

# Expected Behavior
When I generating component for client side then command should only generate param in edit component.

# To Reproduce
1. Create API controller on the basis of DB tables structures.
2. Run command to create component using cmd:

> rxwebcore --components

3. Check behavior in the edit component of a particular module.

# Url (stackblitz or plunker or other)
Please look into this url: [http://prntscr.com/q507k9](url)

# Package Version
@rxwebcore

**Comment by ajayojha** [comment]
@devendraKLohar this is irrelevant to the rxweb package. I am closing this ticket.
