### ISSUE TITLE
Cannot figure out where this undefined error comes from

### ISSUE THREAD

**Issue by pjominet** [rxweb/rxweb#266]
I need to create a rather complex reactive from, but the view fails already on the form build with the following message:

> ERROR TypeError: Cannot read property 'conditionalValidationProps' of undefined
    at rxweb-reactive-form-validators.js:3620
    at Array.forEach (<anonymous>)
    at RxFormBuilder.checkObjectPropAdditionalValidation (rxweb-reactive-form-validators.js:3614)
    at RxFormBuilder.formGroup (rxweb-reactive-form-validators.js:3837)
    at RxFormBuilder.group (rxweb-reactive-form-validators.js:3674)
    at RuleComponent.buildForm (rule.component.ts:210)
    at RuleComponent.ngOnInit (rule.component.ts:91)
    at checkAndUpdateDirectiveInline (core.js:27788)
    at checkAndUpdateNodeInline (core.js:38472)
    at checkAndUpdateNode (core.js:38411)

Here is a part of my component class code:

```javascript
constructor(private formBuilder: RxFormBuilder) {}

ngOnInit() {
       this.buildForm();
}

private buildForm(): void {
        this.ruleForm = this.formBuilder.group({
        ruleAction: [null, RxwebValidators.required()],
        parsingSource: [null, RxwebValidators.required()],
        transcodingTarget: [{disabled: true, value: null}, RxwebValidators.required()],
        commitmentTypeTarget: [{disabled: true, value: null}, RxwebValidators.required()],
        defaultParsingCurrency: [{disabled: true, value: null},
                RxwebValidators.required({
                    conditionalExpression: formControls =>
                        formControls.commitmentTypeTarget == CommitmentType.TargetedStandard || CommitmentType.ReachedStandard
                })],
       amountMultiplier: [{disabled: true, value: null}, RxwebValidators.required()],
       classificationGroupTarget: [{disabled: true, value: null}, RxwebValidators.required()],
       splitOnDelimiter: [{disabled: true, value: null}],
       delimiter: [{disabled: true, value: null},
                RxwebValidators.required({conditionalExpression: formControls => formControls.splitOnDelimiter})],
       keyPerformanceIndicatorTarget: [{disabled: true, value: null},
                RxwebValidators.required({conditionalExpression: formControls => formControls.transcodingTarget == 'Value'})]
        });
    }
```

The different fields are enabled and disabled based on user selections in certain form fields. If I use a normal Angular ``FormBuilder``, I do not have this problem, but then some of the ``conditionalExpressions`` do not work or have no effect. So I wanted to try it with the ``RxFormBuilder`` as in the doc example, but then I got the mentioned error. 

Unfortunately, I cannot figure out if this a problem on my side, or a potential bug of this lib.

using version @rxweb/reactive-form-validators 1.9.7 with Angular 8.1.3
If this is not enough info I will provide a more complete stackblitz example, as soon as I have time.

**Comment by ajayojha** [comment]
@pjominet Thanks for reporting this. I checked in stackblitz and it's working fine. Please refer to this link: https://stackblitz.com/edit/angular-rqktsm?file=src%2Fapp%2Frequired-add.component.ts

Please let me know if I have missed something.

**Comment by pjominet** [comment]
I will recreate my component in a stackblitz, so you can take a look in detail :)

**Comment by ajayojha** [comment]
Thanks, @pjominet, That gives more visibility :).

**Comment by pjominet** [comment]
here: https://stackblitz.com/edit/angular-svmjie?file=src%2Fapp%2Frule%2Frule.component.ts

**Comment by ajayojha** [comment]
@pjominet  Thanks for providing the stackblitz URL, I will check and let you know.

**Comment by ajayojha** [comment]
@pjominet  Please refer this stackblitz link: https://stackblitz.com/edit/angular-fmqbyr?file=src/app/rule/rule.component.ts

The above link is working fine with minor code changes, the changes are mentioned below : 

```js
ruleAction: ['', RxwebValidators.required()],
      parsingSource: ['', RxwebValidators.required()],
```

I have changed `null` to `''` of the respective FormControlValue

Please let me if it's not working in your local machine.

**Comment by pjominet** [comment]
it seems to work, tho I did no in depth testing, as I refactored and by this simplified a lot of code, so there is no more need for the complicated form generation from before. Everything is way simpler now and works like a charm :) Thx for your help anyway, maybe someone else will find this useful :)

**Comment by ajayojha** [comment]
@pjominet Thanks for the update.
