### ISSUE TITLE
Failed to build a reusable form with RxFormBuilder

### ISSUE THREAD

**Issue by lkachun9129** [rxweb/rxweb#267]
# Describe the bug

I was trying to build a reusable form as introduced in this article:
[https://coryrylan.com/blog/building-reusable-forms-in-angular](url)

The example was using built-in FormBuilder.  I tried to replace FormBuilder with RxFormBuilder.  However, it turned out giving different behavior.

# Expected Behavior

The validity of the child form should pass to the parent form correctly.

![image](https://user-images.githubusercontent.com/6640910/72499103-e9991000-386b-11ea-9295-15f03f33b395.png)

# To Reproduce

Sample project using FormBuilder
https://stackblitz.com/edit/angular-eatlwa

Sample project using RxFormBuilder
https://stackblitz.com/edit/angular-a5awxf

# What is the motivation / use case for changing the behavior?

Build a reusable form with RxFormBuilder

# Url

Nil

# Package Version
@rxweb/reactive-form-validators@1.9.7

# Browser

Edge (Chromium) 81.0.387.0

# Additional Info

**Comment by ajayojha** [comment]
@lkachun9129 Thanks for the detailed information. I will check and do the necessary changes.

**Comment by lkachun9129** [comment]
After digging into the details, I found that the reusable form should subscribe to stateChanges too.

```js
this.subscriptions.push(
  this.form.statusChanges.subscribe(_ => {
    this.onChange(this.form.value);
    this.onTouched();
  })
)
```

Here is a working example:
https://stackblitz.com/edit/angular-6unkmp

**Comment by ajayojha** [comment]
Cool, Thanks for spending time and sharing the solution, now no action required from my side, so I am closing this ticket. If you think I have to do something in the lib then please share your thoughts on this ticket and reopen the same :).
