### ISSUE TITLE
How to handle nested object arrays?

### ISSUE THREAD

**Issue by Lempkin** [rxweb/rxweb#27]
# Describe the bug
Not a bug

# Expected Behavior
Let say I have an app to manage books and author.
I want a form to add books to an author.
Let say I'm loading an existing author with 3 books in his collection.
My Author.ts would be like
```
id : number
@required()
name : String
 @propObject(Book)
books : Books[]
```

And my Book.ts
```
id : number
@required()
name : string
```

I then have a form : 

```
<form [formGroup]="authorForm">
  <mat-form-field >
    <input matInput formControlName="name" />
  </mat-form-field>
 ???
...
</form>
```

In the place of the ??? I tried with

```
<div formArrayName="books" >
    <div *ngFor="let book of author.books">
      <mat-form-field>
        <input matInput  formControlName="name"  />
      </mat-form-field>
  </div>
</div>
```

Fields are correctly generated but input fields for book's names are empty although books do have a name. If I add a {{book.name}} in the loop I'm able to see it.
Do I miss something?
Thx!

# Package Version
@rxweb/reactive-form-validators@1.2.8

# Browser
Chrome

# Additional Info

**Comment by Lempkin** [comment]
I finnaly find my way by using  @propArray instead of @propObject, and with this tuto, if this is usefull for anyone : 
https://alligator.io/angular/reactive-forms-formarray-dynamic-fields/

**Comment by ajayojha** [comment]
Thanks Lempkin, You have to apply @propArray on the array object property and also you have to pass the object array while creating a FormGroup. RxFormBuilder will create a FormArray object inside the FormGroup based on JSON data. Please refer the stackblitz(https://stackblitz.com/edit/complete-rxweb-angular-reactive-form-validator-example?file=src%2Fapp%2Fuser%2Fmodels%2Fuser.model.ts) example which includes FormControl, FromGroup and FormArray, based on applied decorators on property of the class. 

I would suggest, Whenever you need a quick answer then please come on our gitter channel(https://gitter.im/rxweb-project/rxweb?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge) for faster response from our end.
