### ISSUE TITLE
@error decorator not return any error message.

### ISSUE THREAD

**Issue by ksiranjeevi92** [rxweb/rxweb#271]
## Describe the problem statement?

I am using Model to create and validate mu form group , I am using @error decorator for generate error message , when the form is still invalid but error message show undefined.
     <small class="form-text text-danger">
    {{userFormGroup.controls.firstName['errorMessage']}}
  </small>
## The expected solution you would like
Need to show error message after form field was touched.

## Url
https://rxweb-reactive-form.stackblitz.io
## Package version
@rxweb/1.9.7

**Comment by ajayojha** [comment]
@ksiranjeevi92 Please provide me the stackblitz link where I can see the code or paste it here so that I can resolve the same.

**Comment by ksiranjeevi92** [comment]
> @ksiranjeevi92 Please provide me the stackblitz link where I can see the code or paste it here so that I can resolve the same.

My html --->
$$$$$$$$$$$$$$$$$$$$$$$$$$$
<h1 class="bd-title" id="content">Model Object based reactive form</h1>
<br/>
<form  [formGroup]="userFormGroup">

<div class="form-group">
    <input type="text" formControlName="firstName" placeholder="First Name" class="form-control"  />
     <small class="form-text text-danger">
    {{userFormGroup.controls.firstName['errorMessage']}}
  </small>
    
</div>
<div class="form-group">
    <input placeholder="Last Name" type="text" formControlName="lastName" class="form-control"  />
    
</div>
<div class="form-group">
    <input placeholder="UserName" type="text" formControlName="userName" class="form-control"  />
    
</div>
<div class="form-group">
    <input placeholder="Password" type="text" formControlName="password" class="form-control"  />
       <small  class="form-text text-danger">
    {{userFormGroup.controls.password['errorMessage']}}
  </small>
    
</div>
<div class="form-group">
    <input placeholder="Confirm" type="text" formControlName="confirmPassword" class="form-control"  />
    
</div>
  <div class="form-group">
    <label>Full Name : {{user.fullName}}</label>
  </div>
<button  (click)="submit()" class="btn btn-primary">Submit</button>
</form>
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
my ts =>
$$$$$$$$$$$$$$$$$$$$$$$$$$

import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';


@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements OnInit {
  name = 'Angular';
  errorObject = {}

   userFormGroup: FormGroup;
    user:User;

  constructor( private formBuilder: RxFormBuilder) {}

   ngOnInit() {
        this.user = new User();
        this.userFormGroup = this.formBuilder.formGroup(this.user);
    }

    submit(){
      console.log(this.userFormGroup);
    }
}
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
and user model =>
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

import { required,compare } from "@rxweb/reactive-form-validators";
import { error,prop } from "@rxweb/reactive-form-validators"

import { AbstractControl} from "@angular/forms"

export class User{
  private _firstName: string = '';
  private _lastName: string = '';
  fullName: string;

  @error({conditionalExpression:function(control:AbstractControl){ return control.touched; }})
   @required()
    set firstName(value: string) {
        this._firstName = value;
        this.setFullName();
    }

    get firstName(): string {
        return this._firstName;
    }

    @required()
    set lastName(value: string) {
        this._lastName = value;
        this.setFullName();
    }

    get lastName(): string{
       return this._lastName;
    }

  @required()
  userName: string;


  @error({conditionalExpression:function(control:AbstractControl){ return control.touched; }})
  @required()
  password: string;

  @compare({fieldName: 'password'})
  confirmPassword: string;

   private setFullName() {
        this.fullName = `${this.firstName} ${this.lastName}`;
    }
}
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

**Comment by ksiranjeevi92** [comment]
<h1 class="bd-title" id="content">Model Object based reactive form</h1>
<br/>
<form  [formGroup]="userFormGroup">

<div class="form-group">
    <input type="text" formControlName="firstName" placeholder="First Name" class="form-control"  />
     <small class="form-text text-danger">
    {{userFormGroup.controls.firstName['errorMessage']}}
  </small>
    
</div>
<div class="form-group">
    <input placeholder="Last Name" type="text" formControlName="lastName" class="form-control"  />
    
</div>
<div class="form-group">
    <input placeholder="UserName" type="text" formControlName="userName" class="form-control"  />
    
</div>
<div class="form-group">
    <input placeholder="Password" type="text" formControlName="password" class="form-control"  />
       <small  class="form-text text-danger">
    {{userFormGroup.controls.password['errorMessage']}}
  </small>
    
</div>
<div class="form-group">
    <input placeholder="Confirm" type="text" formControlName="confirmPassword" class="form-control"  />
    
</div>
  <div class="form-group">
    <label>Full Name : {{user.fullName}}</label>
  </div>
<button  (click)="submit()" class="btn btn-primary">Submit</button>
</form>

**Comment by ksiranjeevi92** [comment]
https://stackblitz.com/edit/rxweb-reactive-form?file=src%2Fapp%2Fapp.component.html

**Comment by ajayojha** [comment]
@ksiranjeevi92 Thanks for sharing the link, It's really helpful for me :) . The problem is the error messages are not configured, Please configure the error messages through `ReactiveFormConfig`. Please see the below code : 

```js
ReactiveFormConfig.set({"validationMessage":{"required":"Please enter valid number"}});
``` 

Please refer to this link, it's working fine: https://stackblitz.com/edit/rxweb-reactive-form-zwsbem?file=src%2Fapp%2Fapp.component.ts.

Feel free to post your comment if you face any issue.

**Comment by ksiranjeevi92** [comment]
Thanks for the update , now the error message is pop out when the form validation is failed.
