### ISSUE TITLE
Bug with form array dynamic

### ISSUE THREAD

**Issue by kelvinsleonardo** [rxweb/rxweb#274]
# Describe the bug
When I use form array in reactive form,  the form keep valid when i change the first field "price". Check example bellow. 

# Expected Behavior
Propagate validation after change first field

# Step
1.Put value 10 in field price
2. Put value 9 in field newPrice
3. Change value 10 of field price to 8
4. Form is valid same the number is greater.

# Url (stackblitz or plunker or other)
https://github.com/kelvinsleonardo/rxweb-bug-form-array

**Comment by ajayojha** [comment]
@kelvinsleonardo Please provide code snippet for more visibility of the issue. I have reviewed the provided code of git, but nowhere I found the code of reactive form validation. Please update the repo code and let me know so that I can review and resolve the same.

**Comment by kelvinsleonardo** [comment]
@ajayojha I update the project, check again pls.

**Comment by ajayojha** [comment]
@kelvinsleonardo  Thanks for the update, I did some changes in your provided repo, now this is working fine. refer this link for code changes: https://github.com/kelvinsleonardo/rxweb-bug-form-array/pull/1/commits/fe5cfc38cf371db5dddab7f9a41b129d37773535#diff-465e9f13ce23ec4a1e366935273fdbb6L6

Please let me know if you have any questions.

**Comment by kelvinsleonardo** [comment]
@ajayojha I accepted your request in project but yet not working.

**Comment by ajayojha** [comment]
Sorry, @kelvinsleonardo, I was applying different cases it was my reading mistake of mentioned steps. You are right it's not working, I am considering this as a bug and this will be fixed in our next release.

**Comment by ajayojha** [comment]
@kelvinsleonardo The issue has been fixed in 1.9.8 release, please update the package in your project. Please let me if you face any issue.

**Comment by ajayojha** [comment]
I am closing this ticket, if you face any issue please reopen the same.
