### ISSUE TITLE
Bug with minDate

### ISSUE THREAD

**Issue by kelvinsleonardo** [rxweb/rxweb#278]
# Describe the bug
When I use the validator minDate, the validation of the date is wrong.

# To Reproduce
Put value "20/02/2020" in field.

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/rxweb-min-date-validation-angular-reactive-form-crmqdu

**Comment by ajayojha** [comment]
@kelvinsleonardo Can you please provide the code snippet.

**Comment by kelvinsleonardo** [comment]
@ajayojha sorry, link updated.

**Comment by ajayojha** [comment]
@kelvinsleonardo Thanks for updating the link. To overcome this issue, you have to configure the date format through `ReactiveFormConfig`. Please refer the below code

```js
  ReactiveFormConfig.set({ 
            "baseConfig": {
                "dateFormat": "dmy",
		"seperator": "/"
            }
        });
```

I have updated the provided code, please refer this link: https://stackblitz.com/edit/rxweb-min-date-validation-angular-reactive-form-mixevg?file=src/app/app.component.ts

**Comment by kelvinsleonardo** [comment]
@ajayojha Thank you for your help. Now is working.

**Comment by ajayojha** [comment]
@kelvinsleonardo I am closing this ticket as I don't see further action required on this. Feel free to create a new ticket if you face any issue :).
