### ISSUE TITLE
Provide documentation of @prop() decorator on rxweb.io

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#28]
**@prop** decorator documentation is not available on rxweb. Here is the [example ](https://stackblitz.com/edit/rxweb-prop-decorator-example?file=src%2Fapp%2Fuser%2Fadd%2Fuser-add.component.ts)of @prop() decorator which can be covered in the documentation.

**Comment by rxwebteam** [comment]
Added @prop decorator documentation and its example in rxweb.io site
