### ISSUE TITLE
@date does not validate as expected

### ISSUE THREAD

**Issue by yellowgrass** [rxweb/rxweb#280]
# Describe the bug

@date({message: 'Date must be in the format of dd/mm/yyyy.'})
  inputDate: string;

ReactiveFormConfig.set({
      baseConfig: {
        dateFormat: 'dmy',
        separator: '/'
      }
    });

But when I type in yyyy-mm-dd, the form validator validates the input field as valid

# Expected Behavior
Expected the field to be invalid for formats other than dd/mm/yyyy

**Comment by ajayojha** [comment]
@yellowgrass Thanks for reporting this issue, this will be fixed in our next release :)

**Comment by ajayojha** [comment]
@yellowgrass The issue has been fixed in our new release 1.9.9-beta3, please update your project package.
