### ISSUE TITLE
Rx-date picker issue

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#283]
# Describe the bug

When any date is selected in rx date picker, it stores previous day date. For example if 02-02-2020 date is selected then it stores 01-02-2020 date. This issue occurs for edit screen, only if that control is touched or is dirty. And when edit operation is performed there's an error regarding date control binding, please find this in attachment.
![rxdateissue](https://user-images.githubusercontent.com/61281539/74953755-1373c280-5428-11ea-9df9-5f9fed84a694.JPG)

# Expected Behavior

Rx-date picker should work properly regardless of control's state

# Package Version
@rxweb/angular@0.0.1

**Comment by ajayojha** [comment]
@mitanshu-patel Can you please provide the stackblitz url

**Comment by ajayojha** [comment]
@mitanshu-patel still waiting for your response, I am planning to release the package today, please update the stackblitz url so that I can fix this in coming release.

**Comment by mitanshu-patel** [comment]
Unfortunately,I won't be able to upload on stackblitz for now I have other tasks on priority. So I am sharing screenshot to depict the scenario. I hope it would give a clear idea about the issue. Please find attachment.

![dateissue](https://user-images.githubusercontent.com/61281539/75859694-79951800-5e20-11ea-9f7a-c66b3ce29bd7.png)

**Comment by ajayojha** [comment]
@mitanshu-patel The reported issue and the provided screenshot is different. Sorry to say but with this information I am not able to resolve the issue. I can understand you are busy in so many things but would be great if you can provide the stackblitz url without url it's not possible for me to resolve the same. I hope you understand my context.

Feel free to take your time, coming Friday I am planning another release in that release I will 
fix this, If the necessary information is available..

**Comment by mitanshu-patel** [comment]
@ajayojha The issue which I reported includes API call. Basically when date is selected on Client side, on server previous day date is received. So providing this code on stackblitz won't be feasible for me as it involves API call.

**Comment by ajayojha** [comment]
@mitanshu-patel the attached screenshot of console issue and server side returning value is different issue. I tried in my local but there is no issue, would be great if you provide the stackblitz link for below screenshot issue.
https://user-images.githubusercontent.com/61281539/74953755-1373c280-5428-11ea-9df9-5f9fed84a694.JPG

**Comment by mitanshu-patel** [comment]
@ajayojha There isn't only one issue. First issue is regarding date mismatch that occurs on API call and another issue is when component is rendered again then console error occurs as there is some problem regarding binding value in datepicker control but this issue only occurs when the datepicker control is in dirty state. Right now I am emphasizing on first issue where date mismatch occurs because it's my very first priority as some of my tasks are pending due to this issue. I would surely like to share stackblitz url but it's not feasible for me as the problem mainly occurs when date value is sent on server side.

**Comment by ajayojha** [comment]
@mitanshu-patel You are adding two different issues in this ticket I would suggest create a two different ticket with the respective issue info. Hence, I am closing this ticket as this is confusing for others.
