### ISSUE TITLE
Domain generation command issue

### ISSUE THREAD

**Issue by divyesh-vadhavana** [rxweb/rxweb#288]
![DomainGenerationIssue](https://user-images.githubusercontent.com/61281395/75246824-9618cb00-57f6-11ea-928e-ddd493930ff3.png)
![DomainGenerationIssue1](https://user-images.githubusercontent.com/61281395/75246827-9749f800-57f6-11ea-9739-21f0a0617aba.png)

# Describe the bug
While generating domain it is not taking BaseQueryParamModel parameter in generated Interface we have to add it manually.

# Expected Behavior
BaseQueryParamModel should be added in interface and its implemented methods.

# To Reproduce
Execute domain generate command.

**Comment by ajayojha** [comment]
You have to pass one more ``--queryParamModel``` parameter with model name while generating a domain controller.  Please create C# related issues in the [rxwebcore ](https://github.com/rxweb/RxWebCore)repository. this is only for client side apps.

**Comment by ajayojha** [comment]
I am closing this ticket as no further action is required on this.
