### ISSUE TITLE
@propObject() documentation is not available on rxweb.io

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#29]
Add @propObject decorator example on the site. I have created an [example ](https://stackblitz.com/edit/rxweb-propobject-decorator-example?file=src%2Fapp%2Fuser%2Fadd%2Fuser-add.component.ts) of propObject which we can use in the documentation as a guide.

**Comment by rxwebteam** [comment]
Added @propObject decorator documentation and its example in rxweb.io site
