### ISSUE TITLE
Column base grid

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#290]
### Description
We have a new feature requirement for column base grid in our project.

### Describe the solution you'd like
Please find prototype in given attachment.
![columnBaseGrid1](https://user-images.githubusercontent.com/61281539/75652217-8549d880-5c80-11ea-9615-0fc90ed276e4.jpg)

**Comment by ajayojha** [comment]
@mitanshu-patel  require more detailing for the feature request

**Comment by mitanshu-patel** [comment]
@ajayojha Right now we have a child grid which provides a child row to its parent row based on any event. But we require column base grid in which a grid will be loaded with an another grid in its individual column rather than appending a child row.

**Comment by ajayojha** [comment]
@mitanshu-patel this can be managed through the existing feature, it's more about design, I would suggest talk to your design team.

**Comment by ajayojha** [comment]
@mitanshu-patel  I am closing this ticket as there is no further action required from my end :).
