### ISSUE TITLE
Issue in Sorting on date column in rx-Grid

### ISSUE THREAD

**Issue by piyushjain201096** [rxweb/rxweb#291]
# Describe the bug
Sorting on date column in Rx-grid is not working properly. As When I change the sort order it only sort on the basis of the day irrespective of month and Year.
![Sorting Issue](https://user-images.githubusercontent.com/29598304/75781424-228d3580-5d83-11ea-8d70-f423d33e8f49.PNG)

# Expected Behavior
It Should Sort according to the Day , month and Year.

# Package Version
@rxweb/grid@0.0.2-beta2

**Comment by ajayojha** [comment]
the value is date object or string object, please confirm?

**Comment by ajayojha** [comment]
I am closing this ticket as no update from you, I would suggest use date object that will sort properly. Feel free to create a new ticket if there is an issue.
