### ISSUE TITLE
Hide Header in child Gird

### ISSUE THREAD

**Issue by piyushjain201096** [rxweb/rxweb#293]
### Description
Currently in Child grid we have Functionality To Hide header and footer together but we have a Requirement to only hide header or footer.

### Describe the solution you'd like

Currently we use 'hideHeaderFooter' to hide the header and footer in the gird but we need to Display the Header and hide the footer so we required two different properties to hide header/footer so we can display/hide any of them according to our need.

**Comment by ajayojha** [comment]
@piyushjain201096 Thanks for this request. It will be available in our next release. I am planning to release it on Wednesday.

**Comment by ajayojha** [comment]
@piyushjain201096 I have released the new version of @rxweb/grid package, you can use `hideHeader` and ```hideFooter``` wherever it's required. Hence, I am closing this ticket.
