### ISSUE TITLE
GreaterThan(Equals)/LesserThan(Equals) on date/custom function

### ISSUE THREAD

**Issue by Langstra** [rxweb/rxweb#294]
### Description
Currently greaterThan(Equals)/lesserThan(Equals) currently only works with numbers and not with dates, localized strings or other data types.

### Describe the solution you'd like
Possible options are to add a few default datatypes like number, date and string. And also add the options to provide your own comparison function.

**Comment by ajayojha** [comment]
@Langstra Interesting feature request, Thanks :). I will draft the case and implement the same.

**Comment by ajayojha** [comment]
@Langstra I am trying to draft the case of this ticket, but we have minDate and max date for date validation, I am a bit confused with your comment like ```localized strings or other data types```.  Number and Date we have covered, other data types are not covered as per my knowledge, if you have any specific case with the respective data type which is not available in the lib please share the case.

**Comment by Langstra** [comment]
`
this.userFormGroup = this.formBuilder.group({
            dateOfBirth:['',], 
            dateOfDeath:['', RxwebValidators.greaterThan({fieldName:'dateOfBirth' })], 
        });
`

This is an example where I would like the dateOfDeath to be greater than (or after) the date of birth. 

One possible solution for this is to provide a comparison function as an option.

`
comparisonFunction(a, b) => {
     a > b;
}

this.userFormGroup = this.formBuilder.group({
            dateOfBirth:['',], 
            dateOfDeath:['', RxwebValidators.greaterThan({fieldName:'dateOfBirth', compare: comparisonFunction })], 
        });
`

Using a solution like this also opens up possbilities for people to build custom string comparisons for local string comparison (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) etc.

**Comment by ajayojha** [comment]
Thanks @Langstra, I have few inputs based upon your comment.
instead of greaterThan we can use minDate validator, which works as expected. Here is the code example : 
```js
this.userFormGroup = this.formBuilder.group({
            dateOfBirth:['',], 
            dateOfDeath:['', RxwebValidators.minDate({fieldName:'dateOfBirth' })], 
        });
```
Your second point is related to the comparision, I don't know if you have used or not of `dynamicConfig` property. This works the same as you are expecting. Please refer this link : https://new.rxweb.io/how-to/bindConfig/validators

Here is the code example : 
```js
this.userFormGroup = this.formBuilder.group({
            dateOfBirth:['',], 
            dateOfDeath:['', RxwebValidators.minDate({fieldName:'dateOfBirth',dynamicConfig:function(x){return x;} })], 
        });
```
Please let me know your inputs on my comment, Is this is sufficient or feature required :).

**Comment by Langstra** [comment]
I am sorry, I was not familiar with the dynamic config yet. That would help more than enough. The fieldName in minDate is also a great addition I think.

**Comment by ajayojha** [comment]
@Langstra Great, if there is any confusion while implementation or your case doesn't fit with the suggested approach then please let me know :).

**Comment by ajayojha** [comment]
@Langstra I am closing this ticket as there is no further action required from my end :). Feel free to create new ticket if you need any help or any issue.
