### ISSUE TITLE
While using DBContextManager in rxwebcore for using Transaction for relational save Error

### ISSUE THREAD

**Issue by varsharoberoi** [rxweb/rxweb#296]
# Describe the bug
Error message:

The connection is already in a transaction and cannot participate in another transaction.

# Expected Behavior

Right now I solved problem by using AutoTransactionsEnabled false and making true.
written following code 
    Uow.Context.Database.AutoTransactionsEnabled = false;
                var result = await DbContextManager.BeginTransactionAsync(this.Uow);
              using (result)
            {
                try
                {
                    await Uow.RegisterNewAsync<Student>(entity.Student);
                    Uow.Context.SaveChanges();
                    await Uow.RegisterNewAsync<Admission>(entity);
                    Uow.Context.SaveChanges();
                    await result.CommitAsync();
                }
                catch(Exception e)
                {
                    Console.WriteLine(e.Message);
                   await result.RollbackAsync();
                }
            }

         
            Uow.Context.Database.AutoTransactionsEnabled = true;

# To Reproduce

If it can be included in DbContextManager it should be good.

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by ajayojha** [comment]
@varsharoberoi Please create the ticket in the rxwebcore repo (https://github.com/rxweb/RxWebCore), this repo is only for client-side projects. Hence I am closing this ticket.
