### ISSUE TITLE
isRestrict property of startsWith validator 

### ISSUE THREAD

**Issue by Ushmidave** [rxweb/rxweb#298]
# Describe the bug
while using `isRestrict` property, it is not allowing the character mentioned in value, but it is allowing other alphabetical letters as well as the first letter of the formControl value while using this

```js
RxwebValidators.startsWith({value:'D'  ,isRestrict:true });
```

# Expected Behavior
 `isRestrict` property should allow alphabetical letters and restrict only  the character mentioned in value parameter.

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-hrqbjx?file=src/app/starts-with-is-restrict.component.ts

# Package Version
@rxweb/reactive-form-validators@1.9.9-beta3(2020-03-17)

**Comment by ajayojha** [comment]
@Ushmidave This issue has been fixed in the previous release, Please check the same. Hence I am closing this ticket as no further action required.
