### ISSUE TITLE
Can we have checkbox control in child grid columns.

### ISSUE THREAD

**Issue by divyesh-vadhavana** [rxweb/rxweb#300]
### Description
As we are using ChildGridWithHeader in AppDivGrid can we have configuredTemplate as checkbox control in ChildGridWithHeader column?

I tried to set configuredTemplate: { templateName: "name" } in one of my ChildGridWithHeader column but it is not working, it display 1/0 as text.

### Describe the solution you'd like
I would like to display checkbox control instead of 1/0 text

![ChildGridFeatureRequest](https://user-images.githubusercontent.com/61281395/77415710-df097280-6de8-11ea-9eaa-3a6f72c6b455.png)

**Comment by ajayojha** [comment]
Whatever feature is available in the main grid the same is available in the child grid, Please implement the same. If there is any issue please let me know.

**Comment by ajayojha** [comment]
I am closing this ticket as no further update on this ticket.
