### ISSUE TITLE
extend RXFormControl 

### ISSUE THREAD

**Issue by Moharam10** [rxweb/rxweb#301]
### Description
I want the to have the ability to to pass an object to all the decorators which i could later  access  it thru formGroup->controls-->

### Describe the solution you'd like
EX: 
export class Employee{
@Required({info:{subForm:"description",}}) 
fistName
}
Then:
form = formBuilder.formGroup(new Employee())

and then in my code i want to be able to access this info object like that:
let subForm = this.form.controls.firstName.info.subForm;
this._router.navigat([subForm])

**Comment by ajayojha** [comment]
@Moharam10 Thanks for this feature request, Before moving forward I would like to know the benefit of doing this. If you have any strong case in your project, please share the same so that I have full visibility while integrating this feature :).

**Comment by Moharam10** [comment]
@ajayojha many thanks to your answer.
Yes I have a multi-step form with a stepper component. something that looks like that:
https://material.angular.io/components/stepper/examples
except i am not using the angular material. I build the compoment from scratch.
The idea is, before submitting the form, i should first test if each input is valid or not. and based on that i should change the color of the stepper icon and navigate to the first subform that contains the first unvalid input.

For that i would like to have the ability to tell each field in the model in which subform it should be rendered.

**Comment by ajayojha** [comment]
@Moharam10 Thanks for the reply :), I am still a bit confused but anyways let me draft the case and let you know, If everything is good then I will release the same in the next release.

**Comment by ajayojha** [comment]
@Moharam10 I tried to draft the case as per the mentioned need. But I would suggest please use any state management library because that provides a lot of flexibility to manage your form. 

Our development is going on for Form State Management, but that package will be released end of this month.

**Comment by Moharam10** [comment]
all is fine @ajayojha 
many thanks to you and best of luck with all of the new features.
