### ISSUE TITLE
PropArray with basic strings

### ISSUE THREAD

**Issue by Barzille** [rxweb/rxweb#304]
## Describe the problem statement?
I would like to use the propArray (or any other solution) to send an array of strings to my backend. Currently it seems only possible to create propArray with custom model classes.
But how should I use the framework to send a list like this:

{
...
   fruits: ["Apples", "Bananas", "Oranges"],
...
}

**Comment by ajayojha** [comment]
The PropArray is used for creating a Nested FormArray, As such, there is no feature available which stores the array value in the FormControl. Right now you have to manage manually. 

I have a question on the reference to your question on [stackoverflow](https://stackoverflow.com/questions/61058310/angular-rxformbuilder-and-array-of-strings).
Why you are creating a Nested FormArray?

**Comment by Barzille** [comment]
Hi,
thank you for your answer.
Maybe I am only not getting it right, but how would you store a list of strings in a Form?
If I could modify the backend and send and revise arrays go objects the framework would work fine. But for simplicity sending and receiving string arrays is a common way.

So I was creating a nested FormArray because I thought it is the right way to go. I could not find any other best practice on how to achieve this.
The rxweb framework saves me now a lot of work, as I am declaring the models for the transmitted data now globally. The string-array-thing is the only thing I am not getting managed at the moment.

**Comment by ajayojha** [comment]
Thanks @Barzille , Please refer to this [stackblitz example](https://stackblitz.com/angular/qxjmqldvdog?file=src%2Fapp%2Fall-of-add.component.ts). 

Instead of FormArray, you have to create a FormControl and stores the value as string array. Please refer to the above stackblitz example if any confusion please let me know happy to solve your queries :).

**Comment by ajayojha** [comment]
@Barzille Incorrect example I have added, Please refer to this link : https://stackblitz.com/edit/angular-481fvf?file=src%2Fapp%2Fall-of-add.component.ts

**Comment by ajayojha** [comment]
@Barzille I hope the provided example solves the problem. I am closing this ticket as no further action required on this ticket.

**Comment by Barzille** [comment]
May I ask one more question, how do you prepopulate the checkboxes with server data? When I adapt it and enter values into the server data object. The checkboxes still seem unchanged.
https://angular-481fvf-lnu7tq.stackblitz.io

**Comment by ajayojha** [comment]
@Barzille Please provide the code editor URL.
