### ISSUE TITLE
Inline date-picker binding in rx-grid

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#308]
## Describe the problem statement?
I have to bind two inline date picker controls in rx-grid one for Start date and another for End Date, which will bind value from database table fields.And on button click need to store selected value from date-picker controls.
I have tried to bind date-picker,but it is not binding value

## Url
Please have a look into this url : https://stackblitz.com/edit/angular-dg7vuy?file=src%2Fapp%2Fapp.component.html

## Package version
@rxweb/

**Comment by ajayojha** [comment]
Date format is not set on the global level in your code. I have added the code and it's working. Please refer to this link: https://stackblitz.com/edit/angular-vyhgjx?file=src/app/app.module.ts

**Comment by ajayojha** [comment]
I hope your concern has been resolved. I am closing this ticket as there is no update on this.
