### ISSUE TITLE
Dashboard with widget settings

### ISSUE THREAD

**Issue by weedkiller** [rxweb/rxweb#309]
### Feature request for Dashboards and widgets - code sample attached below
Code Sample: https://github.com/jdanylko/Tuxboard
Demo: http://mvc.jdash.net/dashboard/index/2134
Demo: https://www.logicmonitor.com/support/dashboards-and-widgets/managing-widgets/widget-configuration

![image](https://user-images.githubusercontent.com/21086190/79613290-3b9c3c80-80cc-11ea-8e43-402c9b096ffc.png)

### Describe the solution you'd like
Any business application needs dashboard with widgets/graphs. Most of it standards, but the data and type of graph may change, so the developers can set it up. 

Any chance you could add dashboards, with permissions.
__________________________

I recommend some features like widget configuration, data permissions.

We need some good examples on extending the widget to let user do business specific configuration for their views.

- [x] Configurable User Driven Widgets/Panels/Charts
- [ ] Let the user choose, the Data Sources/Tables to those Charts
- [ ] Let the user modify Label Names, like X axis and Y Axisi
- [ ] Let the user create a formula or KPI (like a formula)

Hello, I added this as a suggestion and it was lost and slowly keeps getting lost to the bottom of the pile.

We need some good examples on creating 

- Configurable User Driven Widgets/Panels/Charts
- Let the user choose, the Data Sources/Tables to those Charts
- Let the user modify Label Names, like X axis and Y Axisi
- Let the user create a formula or KPI

https://github.com/aspnetzero/aspnet-zero-core/issues/2809#issuecomment-561309329

In summary
__________________________

Sorry about the crude drawings,

- **Dashboard** _global_ settings vs _instance_ settings e.g. only 
  [SquareUp sample](https://squareup.com/help/us/en/article/5183-square-dashboard-overview)

- **Widgets** **Global settings** configured for the tenant level vs. instance settings that are used/set by user when he is viewing
          - I was referring to the widget settings, many people will have different types of widgets they will develop, and will want to render data based on user actions like 1) which widget did he pick, 2) did he use the default setting or change the other settings. 
         - For e.g. global setting are like, export to jpeg, excel, lock unlock. You can display user specific setting below the global settings 

Capture user and global settings in one place on the gear icon
![image](https://user-images.githubusercontent.com/21086190/70079680-32a24700-15d3-11ea-97ef-71fd32e6d451.png)

Also allow the widget to o be updated _without refreshing entire page_

_________________________________

Samples of **charts** on Github free [eCharts](https://echarts.apache.org/examples/en/)
![image](https://user-images.githubusercontent.com/21086190/78740120-e883f600-7923-11ea-914f-a50dff8f2911.png)

________________

[Setting up **KPI on a widget**](https://www.manageengine.com/analytics-plus/help/dashboard/kpi-widgets.html)

**Comment by ajayojha** [comment]
@weedkiller It's not clear what you trying to achieve with rxweb packages. Hence I am closing this ticket because it's not relevant as per our packages.

**Comment by weedkiller** [comment]
Hi, I was saying your framework could be used with dashboards, and widgets.

I was giving some examples of those dashboards already coded that you can pull into your framework
