### ISSUE TITLE
remove prop decorator in the model example

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#31]
Please refer alpha decorator [example ](http://rxweb.io/validation-decorators/alpha).  go to the basic alpha validation example, if you see the model example of alpha which imports 'prop' decorator but that's not used in the model. if it's nowhere used then remove it because it creates confusion.

**Current:**
![image](https://user-images.githubusercontent.com/20392302/48686186-ba8ffb80-ebe0-11e8-8fc7-128d0ba07e15.png)
**Expected:**
![image](https://user-images.githubusercontent.com/20392302/48686216-ca0f4480-ebe0-11e8-91a5-2d0b2e122665.png)

The same has been repeated in every decorator example.

**Comment by rxwebteam** [comment]
Issue is Resolved.
