### ISSUE TITLE
updateOn with RxFormBuilder

### ISSUE THREAD

**Issue by adreso** [rxweb/rxweb#316]
### Description
If someone wants to use updateOn

> updateOn: FormHooks | Read-OnlyReports the update strategy of the AbstractControl (meaning the event on which the control updates itself). Possible values: 'change' \| 'blur' \| 'submit' Default value: 'change'

For example ```updateOn:'blur'``` with the RxFormBuilder then that person has to use the native FormControl to resolve that demand.
`this._rxFormBuilder({role: new FormControl({value:null},{validators:[Validators.required], updateOn:'blur'})}`
the main problem is you can't use  the cross-field validation.
### Describe the solution you'd like
A way to do this with the rxweb, similar to something like this:
`role: [null, [RxwebValidators.required(), updateOn:'blur']];`
or
`role: [null, Validators:{[RxwebValidators.required(), updateOn:'blur'}]]`

**Comment by ajayojha** [comment]
Thanks @adreso for this feature request. This feature will be available in our coming release.

**Comment by ajayojha** [comment]
@adreso the feature is available in the new release 1.9.9. Please update your project package.
Here is code:

```js
  formGroup: FormGroup;
    constructor(private formBuilder: RxFormBuilder) { }
    ngOnInit() {
        this.formGroup = this.formBuilder.group({
            firstName: ['', RxwebValidators.required()]
        }, { abstractControlOptions: { firstName: 'blur' } })
    }
```

Please let me know if there is any issue :).

**Comment by adreso** [comment]
> @adreso the feature is available in the new release 1.9.9. Please update your project package.
> Here is code:
> 
> ```js
>   formGroup: FormGroup;
>     constructor(private formBuilder: RxFormBuilder) { }
>     ngOnInit() {
>         this.formGroup = this.formBuilder.group({
>             firstName: ['', RxwebValidators.required()]
>         }, { abstractControlOptions: { firstName: 'blur' } })
>     }
> ```
> 
> Please let me know if there is any issue :).

That is nice, thanks for the feedback and the support!

**Comment by dmitrye** [comment]
@ajayojha Can you also add abstractControlOptions to this.formBuilder.control() ? There are use cases where we want to add a single control without having to rebuild the group.

**Comment by ramu-erode** [comment]
@ajayojha How to add abstractControlOption for nested control.
