### ISSUE TITLE
Globally OnSubmit

### ISSUE THREAD

**Issue by prashantsynsoft** [rxweb/rxweb#317]
Is there any way we can set this.verifyInfoFormGroup.submitted = true;
this line globally instead of individual page.

**Comment by ajayojha** [comment]
@prashantsynsoft Can you please share the actual scenario alike why you want to set ```submitted``` on global level?

**Comment by prashantsynsoft** [comment]
I just want validation to be trigger in global not individual form.I don't want to go each and every form and property  submitted = true.

**Comment by ajayojha** [comment]
@prashantsynsoft Ok Thanks, But still I am not getting the actual use case for providing the feature on a global level. 

Would it be great if you share the best case which you can manage globally?

The above gives me the opportunity to understand your need and integrate the feature in our lib :).

**Comment by prashantsynsoft** [comment]
Suppose we have multiple component so we need to go each and every component and set 
submitted = true in order to render the validation on ErrorMessageBindingStrategy.OnSubmit in each component, so what i am thinking if we set ErrorMessageBindingStrategy.OnSubmit global the it should not need developer to go each and every component and set submitted = true, if developer want that component not render the validation the is should set submitted = false in that component.

**Comment by ajayojha** [comment]
@prashantsynsoft as far as my knowledge we are going to set the mark as submitted when user clicks on the submit button then how can we set by default true on a global level, Because this fails when the user will not click on submit but still it will work like as submitted. Do you think this is a appropriate to manage at a global level? 

I would be happy to know your thoughts and proceed accordingly :).

**Comment by prashantsynsoft** [comment]
I will Provide update on that let me think all scenario.
I have one question how to  trigger validation in FormGroup or how can i set submitted =true

**Comment by ajayojha** [comment]
@prashantsynsoft ```submitted``` is the property of ```RxFormGroup```. Once you call a method of ```RxFormBuilder``` it returns the ```RxFormGroup``` object.

Manually you have to set the ```submitted``` property value ```true```. Please refer to the doc of strongly type in how to section. You will get a better idea about how to access the property of ```submitted```.

**Comment by ajayojha** [comment]
@prashantsynsoft Whenever you have a strong case for  ```submitted``` property to configure at globally then feel free to create a new ticket. Hence, I am closing this ticket as no further action required on this.
