### ISSUE TITLE
Disable Not Working through Model Decorator

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#318]
@ajayojha Here you are https://stackblitz.com/edit/angular-5ckaqs

_Originally posted by @hoang-innomizetech in https://github.com/rxweb/rxweb/issues/307#issuecomment-617080157_

**Comment by tim1016** [comment]
What is the workaround, if there ?

**Comment by ajayojha** [comment]
@tim1016 the workaround is please use @disable decorator, I will fix this issue and release on Monday.

**Comment by ajayojha** [comment]
@tim1016 The disable is working in the new release, please update the package.
