### ISSUE TITLE
'When to use' section point 5 syntax corrections

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#32]
Point 5 is a little bit confusing what exactly this covered. I believe the syntax should be different as per given example in the doc. please refer this link : http://rxweb.io/validation-decorators/alpha

**Current:**
 
![image](https://user-images.githubusercontent.com/20392302/48686478-29218900-ebe2-11e8-9028-cab999f2cc00.png)
**Expected:**
![image](https://user-images.githubusercontent.com/20392302/48686484-35a5e180-ebe2-11e8-81a7-5ca04145c048.png)

The sample corrections should be required in every decorators.

**Comment by rxcontributorone** [comment]
correction done
