### ISSUE TITLE
To bind a grid forming up with dynamic columns

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#320]
The requirement is:
The grid formation should consists of columns naming, mainly selected from the drop down named entity in the below image.

Whereas the values coming in the drop down are not also dynamic, to suppose those as random selection options

![Dynamic_columns_grid](https://user-images.githubusercontent.com/61281626/80707404-8758d800-8b07-11ea-9d63-f959859a7520.png)

**Comment by ajayojha** [comment]
@Kiran-Pawar please share the information on maximum limit of columns that will be bind dynamically.

**Comment by Kiran-Pawar** [comment]
@ajayojha - The entities are not fixed and we cannot define max limit of columns.. they can even be 0 or more than 100.

**Comment by ajayojha** [comment]
@Kiran-Pawar I have released the new version of grid, please update the project package.
for dynamic column add in the grid you have to rebind the grid whenever you want to add a new column ad remove the column. Here is the code for adding:

```js
this.gridConfig = new AppGridDesigner(this.source, Company, {
            columns: {
                startColumnIndex: 4, columnConfigs:
                    [
                        { name: "columnOne",  visible: true, columnIndex: 1, allowSorting: true, headerKey: 'columnOne', keyColumn: false }

                    ]
            }
        });
        this.gridConfig.design(document.getElementById("grid"));
```

Whatever the columns you want to show in the grid, you have to pass those columns configuration through the ```columns``` parameter. ```startColumnIndex``` is used for set column position in the grid. Please refer the stackblitz example : https://stackblitz.com/edit/rxweb-grid-add-dynamic-columns?file=src%2Fapp%2Fapp.component.ts

I am closing this ticket as no further action required on this ticket.
