### ISSUE TITLE
Add prefix all directive 

### ISSUE THREAD

**Issue by batya15** [rxweb/rxweb#321]
### Description
Add prefixes to directives, since frequent intersection with input parameters of other libraries, in particular, I came across a maxDate

**Comment by dbusacca** [comment]
I've got the same problem with the "required" and angular-material `<mat-form-field>` for the `<input>` tag.

Material support the use of "required" in a dynamic way:

`
<input [required]="isRequired"></input>
`

The input is required only in if the `isRequired` variable is true.

RxwebValidators force the `required` validation always.

**Comment by ajayojha** [comment]
Thanks @batya15 & @dbusacca , I will fix this.

**Comment by ajayojha** [comment]
@batya15 and @dbusacca , the prefix(`rx`) have been added in the new release. Thanks for creating the ticket.

**Comment by dbusacca** [comment]
Thank you, I love this library!
