### ISSUE TITLE
How to use @unique() with @propArray()

### ISSUE THREAD

**Issue by DiponRoy** [rxweb/rxweb#323]
I have a validation model as below, where MsisdnBulkUploadModel  has child list of BulkMsisdnModel 

```
export class BulkMsisdnModel {
  @required()
  @digit()
  @startsWith({ value:'0', message: "Msisdn should start with 0" })
  @minLength({ value: 11, message: "Minimum value should be 11."})
  @maxLength({ value: 11, message: "Maximum value should be 11."})
  @unique()
  msisdn: string;
}

export class MsisdnBulkUploadModel {
  @required()
  file: File = null;

  @required()
  @digit()
  @minNumber({ value: 1, message: "Minimum value should be 1."})
  surveyId: number;

  @propArray(BulkMsisdnModel)
  msisdns: Array<BulkMsisdnModel> = [];
}
```
@unique() is not working with @propArray()
Is there any option?

**Comment by ajayojha** [comment]
@DiponRoy, the posted code seems correct, Where you are facing the issue, please highlight the same. Please refer this stackblitz link for your understanding, this is the same as you have implemented by class name is different: https://stackblitz.com/edit/angular-fo8vmw?file=src%2Fapp%2Femployee.model.ts

> @unique() is not working with @propArray()

It must work, please refer to the stackblitz example.

**Comment by DiponRoy** [comment]
You are right, things are also working for me now. It is definitely caches issue. 

One thing I have found in another form, that this type of binding is working great with a small data set (during development time).
My child model with 8 properties with validation attributes and a list of 2000 items, is failing to bind in the front end. (QA testing time). 

I was validating items uploaded as a file.

But I am very happy with this library, Thank you very much!!!

**Comment by ajayojha** [comment]
Thanks, @DiponRoy, 2000 items are binding on the page then there are so many other things you have to consider while binding the data in regards to performance, I don't think due to validators it fails, But still if you found related our library I would be happy to resolve the same :).

**Comment by ajayojha** [comment]
@DiponRoy I am closing this ticket as no further action required on this from my end  :), feel free to create a new ticket if you find anything is causing performance due to our library.
