### ISSUE TITLE
Need input  value of rx-select to be passed in queryParams instead of params

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#325]
## Describe the problem statement?
I have a  requirement of binding dropdown dynamically based on user's input in rx-select dropdown.I need to pass the value of  dropdown in queryParams instead of params while calling the API.

## The expected solution you would like
When user types any value in rx-dropdown, API will be called based on given input and data will get bind in that dropdown. But the given value should be passed in API url as queryParams  not in params.
Here I am giving value 'abc' as input. But that value is passed in params but I need that value in queryParams in key  'searchString'. So my queryParam key-value pair would be as follows:-
searchString:"abc"

Please find attachments
![rx-select1](https://user-images.githubusercontent.com/61281539/81551903-374c0200-93a0-11ea-8b3d-4ceb18887612.JPG)
![rx-select2](https://user-images.githubusercontent.com/61281539/81551906-387d2f00-93a0-11ea-861f-89d8563fc39c.jpg)
![rx-select3](https://user-images.githubusercontent.com/61281539/81551908-3915c580-93a0-11ea-9ab2-9cb50a249bd1.jpg)

## Package version
@rxweb/angular-0.0.2-beta6

**Comment by ajayojha** [comment]
@mitanshu-patel , Thanks for sharing the detailed information. I have released the new version (@rxweb/angular-0.0.2-beta7) please update the same.
For passing the value in query string, you have to use ```valueInQueryParams``` on the element with the value of ```true```. After this, you will get the entered value in the `q` query string.
