### ISSUE TITLE
allowSearch Property not working

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#326]
# Describe the bug

I have Grid which contains multiple columns and need not to provide search functionality on "Image" column(which Display Image),so i have used allowSearch:false property of rx-grid.
But is not working for me.still it searches record from image colunm also.

# Expected Behavior

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by ajayojha** [comment]
@Kiran-Pawar , I have released the new version, please update the project package.
