### ISSUE TITLE
Manage multiple inline controls in rx-grid

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#327]
## Describe the problem statement?
I have to manage multiple inline controls in rx-grid like Texbox,Textarea,Autocomplete Select,
rx-tag and checkbox controls.So how to manage this controls which contains dynamic values.

## The expected solution you would like
Easy way to manage multiple inline grid control and will be able to perform CRUD operation on that controls.
## Package version
@rxweb/

**Comment by ajayojha** [comment]
@Kiran-Pawar  inline controls are already available in the app, please use the same. What you are looking for additionally?

**Comment by ajayojha** [comment]
@Kiran-Pawar I am closing this ticket as no further update on this.
