### ISSUE TITLE
Issue using valueInQueryParams attribute in rx-select

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#329]
# Describe the bug
I am using rx-select for dynamically binding dropdown from API based on user input value in rx-select. I needed value in query params according to my project's API so I used **valueInQueryParams**  attribute with value **true** which should give value in 'q' parameter but it's not happening. Value is still passed as params.  Just let me know if there's any mistake in the way I implemented. This is related to ticket  https://github.com/rxweb/rxweb/issues/325 which I raised before the new package release.

# Expected Behavior
If I use **valueInQueryParams** attribute then it should pass value in **'q'** string in queryParams.

# Url (stackblitz)

https://stackblitz.com/edit/angular-ivy-dssfnh

# Package Version
@rxweb/angular@0.0.2beta7

**Comment by ajayojha** [comment]
@mitanshu-patel , The code was fixed in the previous release but the issue was in the published package set, I have corrected the same and released 0.0.2-beta8, please update the same. I have tested It's working as expected, I am not closing this ticket until you next update.

**Comment by ajayojha** [comment]
I hope the problem has been resolved, Hence I am closing this ticket.

**Comment by mitanshu-patel** [comment]
> @mitanshu-patel , The code was fixed in the previous release but the issue was in the published package set, I have corrected the same and released 0.0.2-beta8, please update the same. I have tested It's working as expected, I am not closing this ticket until you next update.

Sorry for such inconvenience. From past few days I was having quite hectic schedule  due to which  I wasn't able to see the updates. Currently I've installed the new package. Will update  you once its completely implemented.

**Comment by mitanshu-patel** [comment]
> I hope the problem has been resolved, Hence I am closing this ticket.

Now its working as expected. Thanks for the update
