### ISSUE TITLE
Validators documentation corrections sub text of ‘Basic {{validatorName}} validation’

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#33]
In every validator Basic example section, the content is not related to the current validator. Please refer this link http://rxweb.io/validation-validators/alpha
**Current:**
![image](https://user-images.githubusercontent.com/20392302/48686597-cda3cb00-ebe2-11e8-9a38-6a66575505fe.png)
**Expected:**
![image](https://user-images.githubusercontent.com/20392302/48686621-e1e7c800-ebe2-11e8-992d-bac5c5f248fc.png)

**Comment by rxcontributorone** [comment]
correction done
