### ISSUE TITLE
Allow building the form with AbstractControlOptions

### ISSUE THREAD

**Issue by lkachun9129** [rxweb/rxweb#332]
### Description

Allow assigning formGroup level validator for cross fields validations

### Describe the solution you'd like

Is it possible to allow building the form using `RxFormBuilder` by providing `AbstractControlOptions` from `@angular/forms`?

I find that there is a property `abstractControlOptions` in `FormBuilderConfiguration`. However, it sets only the value of `AbstractControlOptions.updateOn`

Here is an example of using `AbstractControlOptions` with `FormBuilder` from `@angular/forms`:
```
export class AppComponent  {
  form: FormGroup;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      published: true,
      credentials: this.fb.array([]),
    });
  }

  addCreds() {
    const creds = this.form.controls.credentials as FormArray;
    creds.push(this.fb.group({
      username: ['', {
      validators:[this.isNameDuplicate()],
      updateOn:'blur'}],
      password: '',
    }));
  }

  isNameDuplicate(): ValidatorFn {
    return (c: AbstractControl): { [key: string]: boolean } | null => {
    const userNames = this.form.get("credentials").value;
    console.log(userNames);
    const names = userNames.map(item=> item.username.trim());
    const hasDuplicate = names.some(
    (name, index) => names.indexOf(name, index + 1) != -1
  );

  if (hasDuplicate) {
    console.log(hasDuplicate);
    return { duplicate: true };
  }

  return null;
  }
} 
}
```

**Comment by ajayojha** [comment]
@lkachun9129  Please refer to this response https://github.com/rxweb/rxweb/issues/316#issuecomment-621614399, Please let me know if your requirement isn't fulfilled the same.

**Comment by lkachun9129** [comment]
@ajayojha I think the comment does not address my issue.

Here is an example showing what I want to archive:

**AbstractControlOptions in FormBuilder**
https://stackblitz.com/edit/unique-value-validation-in-formarray-reactive-forms-angu-zmtfg8

**AbstractControlOptions in RxFormBuilder**
https://stackblitz.com/edit/unique-value-validation-in-formarray-reactive-forms-angu-axnzqy

The only difference between the two examples is that the upper one uses FormBuilder while the lower one uses RxFormBuilder.

**Comment by ajayojha** [comment]
@lkachun9129 The feature is available in the 2.1.0 release. Please update the same. For how to part please refer to [this spec](https://github.com/rxweb/rxweb/blob/39713b62b3630e0a9b7ddce7e546ac1433e87f64/client-side/angular/test/reactive-form-validators/services/rx_form_builder_group.spec.ts#L373-L389).

**Comment by lkachun9129** [comment]
@ajayojha Thank you! It works great. But I have a question, why the validators need to be grouped under `global`?

```
baseAbstractControlOptions: {
    global: {
        validators: [globalValidator()]
    }
}
```

**Comment by ajayojha** [comment]
@lkachun9129 you can bind the validator with the specific FormControl level as well by mentioning the respective FormControl name instead of 'global', 'global' is used for binding the validators at FormGroup level.
