### ISSUE TITLE
@date does not validate as expected

### ISSUE THREAD

**Issue by yellowgrass** [rxweb/rxweb#333]
# Describe the bug
@Date({message: 'Date must be in the format of dd/mm/yyyy.'})
inputDate: string;

ReactiveFormConfig.set({
baseConfig: {
dateFormat: 'dmy',
separator: '/'
}
});

But when I type in dd-mm-yyyy, the form validator validates the input field as valid

# Expected Behavior

Expected the field to be invalid for formats other than dd/mm/yyyy

# Package Version
"@rxweb/reactive-form-validators": "^1.9.9"

**Comment by ajayojha** [comment]
@yellowgrass the issue has been fixed in 2.1.0 release. please update the project package and pass the parameter of ```{ allowISODate: false }``` for disallowing the iso dates.
