### ISSUE TITLE
Extended Models have incorrect import statements

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#334]
Hello Sir,

When I run model command, extended models generate imports Name of property in the class instead of type of the property.
Ex.
For property, buyerNavigation : UserBase;

import {BuyerNavigationBase} from '../database-models/buyer-navigation-base'; 
is being imported instead of
import {UserBase} from '../database-models/user-base';

[angulararchitectureissue.txt](https://github.com/rxweb/rxweb/files/4656694/angulararchitectureissue.txt)

**Comment by ajayojha** [comment]
@diptip09 Please create this ticket in RxWebCore repository, because it's a CLI issue and update their database script of the respective model. Hence I am closing this ticket here.
