### ISSUE TITLE
Optional digit in mask

### ISSUE THREAD

**Issue by mlibanori** [rxweb/rxweb#335]
### Description
A implementação de validação utilizando mascara traz facilidade nas aplicações. Hoje a proposta utilizada são de utilizar o digito 9 para informar os caracteres utilizados na mascara.
Nos tempos de Jquery utilizavamos muito o plugin Mask para esse fim, e nele, a forma de configuração era utilizando o caracter 0 para numeros obrigatórios, e 9 para numeros opcionais. Com isso, poderia criar mascaras mais flexiveis, como por exemplo a adição de numeros de telefone com 10 ou 11 digitos como por exemplo (00) 00000-0009

**Comment by ajayojha** [comment]
Thanks @mlibanori , I have translated the text with the help of google translate, which is mentioned below:

> The implementation of validation using a mask brings ease to applications. Today the proposal used is to use the digit 9 to inform the characters used in the mask.
In the days of Jquery we used the Mask plugin a lot for this purpose, and in it, the form of configuration was using the character 0 for mandatory numbers, and 9 for optional numbers. With this, you could create more flexible masks, such as adding phone numbers with 10 or 11 digits such as (00) 00000-0009

I will check the possibilities and implement the same.

**Comment by ajayojha** [comment]
@mlibanori I have added a feature in 2.0.0 release, please use ```minLength``` property for option values.
