### ISSUE TITLE
Customizing Header UI in rx-grid

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#336]
### Description
I have requirement of custom header in rx-grid. Currently in rx-grid, there's header for every column individually but I need an additional header which works as merged column header. I am attaching the screenshot for better clarity:-

![mergedHeader](https://user-images.githubusercontent.com/61281539/83392011-0b0d2980-a412-11ea-8536-01228543b513.JPG)

### Describe the solution you'd like
As we can see in above screenshot, there are 4 columns which has an additional header as MergedHeader1' and other 2 columns which has header as 'MergedHeader2'.  So I require any provision through which I can achieve this

**Comment by mitanshu-patel** [comment]
Hi @ajayojha As per my knowledge, there's a new package release for Grid in next week which would cover this feature request, so can I expect it around 17 July? Please let me know.

**Comment by mitanshu-patel** [comment]
Hi @ajayojha  Please let me know when the new package for grid is expected to be released. Because it's urgent for QA release

**Comment by ajayojha** [comment]
@mitanshu-patel The package will be released today, will update here soon.

**Comment by ajayojha** [comment]
The feature has been released, please refer to the [example](https://github.com/rxweb/rxweb/tree/master/examples/client-side/ticket-examples/336-grid-column-header-grouping), just to give you a high-level idea about how to implement in the project.

For the column group, you have to use the ```@grid``` decorator on the model.

```js
@grid({
    groupColumnHeader: [
        {
            parentTemplateName: "parentTemplate",
            items: [
                { templateName: "groupHeader", columns: ["id", "name"], data: { "name": "FirstColumn" }, index: 0 },
                { templateName: "groupHeader", columns: ["displayOrder"], data: { "name": "Second Column Group" }, index: 0 }
            ]
        }
    ]
})
```
Please refer to the [model](https://github.com/rxweb/rxweb/blob/master/examples/client-side/ticket-examples/336-grid-column-header-grouping/src/app/v-article-lookup-base.ts) for more information.

Create the template as per the application design, please refer to the [custom template](https://github.com/rxweb/rxweb/blob/master/examples/client-side/ticket-examples/336-grid-column-header-grouping/src/app/grid-custom-template.ts#L60-L71) which I have created for your understanding.


Please let me know if there is an issue.

**Comment by mitanshu-patel** [comment]
Ok thanks for update.Will implement it and let you know if any hurdle faced

**Comment by mitanshu-patel** [comment]
Hi @ajayojha . I implemented Group header and it's working but it is displaying that header at the beginning even though I've given **index : 7**

It's showing as:-
![groupHeader](https://user-images.githubusercontent.com/61281539/88083145-4e794e00-cba0-11ea-9bfa-9c4fd5d79990.JPG)

This is the integration of the template in model:-

```
@grid({
  groupColumnHeader: [
      {
          parentTemplateName: "parentTemplate",
          items: [
              { templateName: "groupHeader", columns: ["sold", "Pending","gifted","PreSold"], data: { "name": "Sales History" }, index: 7 },
          ]
      }
  ]
})
```

**Comment by ajayojha** [comment]
That you have to manage from css class, please the provided example where I have created a class which applied based the group of the columns,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mitanshu-patel** [comment]
Ok not an issue. Will manage it that way

**Comment by ajayojha** [comment]
@mitanshu-patel I am closing this ticket, as no further action required on this.
