### ISSUE TITLE
In multi-select, deselected option do not appear in the order in which they were selected

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#337]
## Describe the problem statement?
I have a multi-select(rx-tag) control,when options selected from that control and again if we deselect
that options, it is added to the last position in the list and not appear in the order in which they were selected.

## The expected solution you would like
When removing the selected options from rx-tag, options should add back to the same position in the drop-down list from which they were selected.so How can i manage order of values in list

## Package version
@rxweb/

**Comment by Kiran-Pawar** [comment]
Hi @ajayojha ,When i expect the solution of this problem

**Comment by ajayojha** [comment]
Will be released in this weekend

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
@Kiran-Pawar I have released the new version **[(0.0.2)](https://www.npmjs.com/package/@rxweb/angular)**, Please update the package and refer to the [stackblitz example of rxtag](https://stackblitz.com/edit/rxweb-tag-item-ordering?file=src%2Fapp%2Fapp.component.ts).
