### ISSUE TITLE
Documentation corrections of allowWhiteSpace Description

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#34]
allowWhiteSpace description minor correction required. Instead of property try to use FormControl word in the description. Please refer this link : http://rxweb.io/validation-validators/alpha ;  the same changes required in every validator/decorator documentation

**Current:**
![image](https://user-images.githubusercontent.com/20392302/48686695-60446a00-ebe3-11e8-9d48-cbd2df892426.png)

Expected:
![image](https://user-images.githubusercontent.com/20392302/48686711-7520fd80-ebe3-11e8-8f19-5914caaf2a9e.png)

**Comment by rxcontributorone** [comment]
Corrections done
