### ISSUE TITLE
Model Validations are not working in API

### ISSUE THREAD

**Issue by KamleshDedasaniya** [rxweb/rxweb#341]
Here is my model code

[Range(1,int.MaxValue)]
[Required]
public int TestId { get; set; }

I have applied above Annotations in model class but it's still not showing validation message in request call.

**Comment by ajayojha** [comment]
@KamleshDedasaniya Please share the response JSON data and requested data.

**Comment by ajayojha** [comment]
@KamleshDedasaniya No further update on this, hence I am closing this ticket.
