### ISSUE TITLE
rx-grid column date picker value does not get bind

### ISSUE THREAD

**Issue by rxdotnetdev21** [rxweb/rxweb#343]
I have applied the solution as mentioned in below ticket..
https://github.com/rxweb/rxweb/issues/308

The date picker gets well added in rx-grid column, but a date value returning from DB is not set in the date picker added as element in grid column.

**Comment by ajayojha** [comment]
Please share stackblitz url with enough information

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxdotnetdev21** [comment]
Please have a look into this url : https://stackblitz.com/edit/angular-dg7vuy?file=src%2Fapp%2Fapp.component.html

**Comment by ajayojha** [comment]
@rxdotnetdev21 Please refer to the mentioned ticket stackblitz example and share the actual problem with a detailed statement.

**Comment by rxdotnetdev21** [comment]
I needed a datepicker in rx-grid column, so i used the way as described in the stackblitz url solution which is working well.
when i select a date from the date picker it binds well.. but when the record gets the date value from DB side that value is not getting bind to the datepicker control.

**Comment by ajayojha** [comment]
Please refer to my comment in mentioned ticket, I am sure you will get the solution. If not then please update here which code not performing well so that I will focus on that part only instead of whole code.

**Comment by ajayojha** [comment]
It's working in this example (https://stackblitz.com/edit/angular-vyhgjx?file=src%2Fapp%2Fapp.component.ts) which I have copied from the #308

**Comment by rxdotnetdev21** [comment]
Yes, I referred it well, but it's not working for me..

**Comment by ajayojha** [comment]
But it’s working in the provided example, please check packages are updated in your project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxdotnetdev21** [comment]
I updated the packages, now its working well. Thank you.
