### ISSUE TITLE
@prop feature do not work

### ISSUE THREAD

**Issue by cxddlmu** [rxweb/rxweb#344]
## Describe the problem statement?
in angular, i try the demo provided for the feature‘
bind name of server side property‘ with @prop do not work. plz help to check
## Package version
@rxweb/

**Comment by ajayojha** [comment]
@cxddlmu Can you please provide the code snippet.

**Comment by ajayojha** [comment]
@cxddlmu as there is no further update, hence I am closing this ticket, feel free to create a new ticket.
