### ISSUE TITLE
NumericValidator breaks as soon as a input type=number is used

### ISSUE THREAD

**Issue by ChrisKaun** [rxweb/rxweb#345]
# Describe the bug
Once a html input tag is defined as a numeric field the validators won't work anymore. See Stackblitz below.  

Before using Rxweb I would have marked all float input fields as `type="number"`. This would tell angular to parse the number to the inputs in the correct format. The number `14.44` would be patched as `14,44` if the locale is set to `de`.

Rxwebvalidators couldn't validate correct once the type was set, so I removed it.

Now angular patches above number as  `14.44` to the input, Rxwebvalidator#numeric will mark this as invalid since `.` is a invalid seperator for `de`.

Of course there is an option to allow `.` seperator, but this would break user input since users will enter the value as `14,44`.

# Expected Behavior

Either allow to define a number type on the inputs (I guess that the parsing of the value while validating is broken) or handle the parsing of the values in this package.

# To Reproduce
Create a app with set locale to `de`. Create a FormControl with the numeric validator and allow decimals. Patch any decimal value from the typescript code to the control.

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/numeric-validator-fr-aoxmw2

**Comment by ajayojha** [comment]
@ChrisKaun Thank You for creating this ticket, I did analyze the mentioned use case and try to find out the best optimum solution, But I think we cannot provide anyone option in the lib. Let me describe the problem statement if we implement the auto parsing option in the lib.

**Auto Parsing:** As validator is used for validating the value, not for parsing the value, but still I try to draft the case but it fails our use cases. 

Maybe I need more time to find another good solution or conclude this in a way that we cannot provide this in the lib.


If you have any alternative inputs then please share the same.

**Comment by ajayojha** [comment]
@ChrisKaun I am closing this ticket as we can't mix to two things in one. I am finding the best alternative which we can use in this case. Feel free to reopen a new ticket if you have something or create a new.

**Comment by michelebenolli** [comment]
Has there been any solution found for this issue?
