### ISSUE TITLE
When FormGroup contains a FormControl instead of RxFormControl error is thrown

### ISSUE THREAD

**Issue by dmitrye** [rxweb/rxweb#346]
https://github.com/rxweb/rxweb/blob/cc7980e32acfcf1c827dfe9c5339a9254f8ece9b/client-side/angular/packages/reactive-form-validators/services/rx-form-group.ts#L195

rxweb-reactive-form-validators.js:formatted:1 ERROR TypeError: this.controls[columnName].getControlValue is not a function
    at rxweb-reactive-form-validators.js:formatted:1
    at Array.forEach (<anonymous>)
    at RxFormGroup.valueChangedSync (rxweb-reactive-form-validators.js:formatted:1)
    at RxFormControl.setValue (rxweb-reactive-form-validators.js:formatted:1)
    at updateControl (rxweb-reactive-form-validators.js:formatted:1)
    at DefaultValueAccessor.onChange (rxweb-reactive-form-validators.js:formatted:1)
    at DefaultValueAccessor._handleInput (rxweb-reactive-form-validators.js:formatted:1)
    at DefaultValueAccessor_input_HostBindingHandler (rxweb-reactive-form-validators.js:formatted:1)
    at executeListenerWithErrorHandling (rxweb-reactive-form-validators.js:formatted:1)
    at wrapListenerIn_markDirtyAndPreventDefault (rxweb-reactive-form-validators.js:formatted:1)

The issue is with the tail end of this line 195:
```
&& ApplicationUtil.notEqualTo((<RxFormControl>this.controls[columnName]).getControlValue(), this.entityObject[columnName])
```

RxFormControl has a .getControlValue() method but a FormControl does not. Therefore, when a FormControl is present in a FormGroup the above error will be thrown. Either add another check for FormControl or use a different method to grab the value.

Also, i looked at adding an RxFormControl instead of FormControl but RxFormControl constructor does not support the FormControl signature and requires 7 parameters making it cumbersome.  I had to add a custom async validator to the control so I had to recreate it manually.

**Comment by ajayojha** [comment]
@dmitrye Thanks for reporting this, Can you please share the little code snippet of Creating a FormGroup with FormControl Object :).

**Comment by dmitrye** [comment]
@ajayojha 

Here is an example. _this is a class object with decorator based validators. Since I can't add a custom async validator through decorators I removed the default email validators and reset them. I've also run into an issue where I can't use formBuilder.control() method since it doesn't support updateOn (configuration options).

```
let formGroup = formBuilder.formGroup(_this); =
    formGroup.removeControl('email');
    formBuilder.control()
    formGroup.addControl('email', new FormControl('', {
      validators: [Validators.required, Validators.email],
      asyncValidators: [User.checkEmailIsUnique(userManagementService)], //attach a custom async validator
      updateOn: 'blur'
    }));
```

**Comment by ajayojha** [comment]
@dmitrye I have fixed the issue, please update the package with the version of (2.0.0).

**Comment by dmitrye** [comment]
@ajayojha Thank you again, I will update over the weekend and provide feedback next week.
