### ISSUE TITLE
Could not Reset Drop Down list box in angular

### ISSUE THREAD

**Issue by KamleshDedasaniya** [rxweb/rxweb#347]
Hi Team,

I am facing issue in cascading DropDwonlist functionality.

I have two DDL one for Country and another for State.
When I am change country then state are not change.
Means State DropDownList doesn't reset base on Country
it is merge with old and new value.

Below code for html

 <rx-select [(source)]="administrationLookupGroup.countryLookup" formControlName="CountryId"
                             mainClass="chosen-select form-control focus-effect" (changed)="resetForm($event)"
                             [keyValueProps]="['country','countryId']"  selectPlaceholder="Select any" >
                            </rx-select>

  <rx-select  [(source)]="arryState" formControlName="StateId" 
                             mainClass="chosen-select form-control focus-effect" 
                             [keyValueProps]="['states','stateId']">

Below code for component.ts file

resetForm(event: any){
        this.arryState = null;
        if(event.text !== "")
        {
            this.searchFormGroup.resetForm({resetType:ResetFormType.DefinedPropsOnly,value:{ StateId: null }});
            this.getState(event.item.key);
        }
      }

**Comment by ajayojha** [comment]
@KamleshDedasaniya Please refer to this [stackblitz example](https://stackblitz.com/edit/rxweb-select-on-selection-changed?file=src%2Fapp%2Fapp.component.ts), in the example, I have used ```ViewChild``` decorator for getting the instance of ```RxSelectComponent``` and while changing the value of Country Dropdown I have reset the source of State Control. 

Any confusion please let me know.

**Comment by KamleshDedasaniya** [comment]
Thank you sir givenHello,

Using ViewChild decorator i can reset the child DropDownlist.

Now it is working proper.

Thanks for the given proper solution. the response
