### ISSUE TITLE
after changing data in rx-grid, update source of grid does not work

### ISSUE THREAD

**Issue by bharat0249** [rxweb/rxweb#348]
# Describe the bug
when change some data of source in grid , then try to update source
using method updateSource does not work this error occurs

TypeError: Cannot read property 'nextPage' of undefined

# Expected Behavior
this error should not occur, changed source of grid should be reflected and appear

# To Reproduce
click on up or down button, error will appear in console

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-rx-grid-8mexm8

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by Srishti-Khandelwal16** [comment]
You need to bind  `storeProcedure` property with the AppGrid object with necessary parameters.

**Comment by ajayojha** [comment]
@bharat0249 if every page data is coming from the server then please follow the @Srishti-Khandelwal16 suggested approach or else remove the swap code as there is no need of that code, I am closing this ticket as there is no further update on this.
