### ISSUE TITLE
after changing data on any page grid displays data from first page in rx-grid

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#349]
# Describe the bug
if i move on second page and update data grid refreshed and go on first page

# Expected Behavior
if we change data on any page grid the grid should be stay on current page rether than first page

# To Reproduce
go on 2nd page update display order it will go on 1st page 

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-rx-grid

# Package Version
@rxweb/grid "0.0.2-beta7"

**Comment by ajayojha** [comment]
@afzalmansuri Always changing the data it goes to the first page if there is a large number of data which is coming from server-specific page wise then I would suggest please refer to[ this comment](https://github.com/rxweb/rxweb/issues/348#issuecomment-651566325).

**Comment by afzalmansuri** [comment]
Hello @ajayojha Sir
as per you  suggest [this comment]( https://stackblitz.com/edit/angular-rx-grid-ya2cex?file=src/app/app.component.ts) i have refer this and try it out but i'm facing out problem in pagination can you help me out in this. i have attached below updated example for this.
[Example](https://stackblitz.com/edit/angular-rx-grid-wu7cxr?file=src%2Fapp%2Fapp.component.ts)
