### ISSUE TITLE
Documentation corrections of message Description

### ISSUE THREAD

**Issue by ajayojha** [rxweb/rxweb#35]
message property is used for applying the custom message on respective validation. But the message property description is incorrect.
Please refer this link: http://rxweb.io/validation-validators/alpha

**Current:**
![image](https://user-images.githubusercontent.com/20392302/48686790-ec569180-ebe3-11e8-833e-bbafe94c8394.png)

**Expected:**
![image](https://user-images.githubusercontent.com/20392302/48686799-f4aecc80-ebe3-11e8-8e4f-bbaf5d46241e.png)

**Comment by rxcontributorone** [comment]
Corrections done
