### ISSUE TITLE
SCRIPT5021: Invalid range in character set

### ISSUE THREAD

**Issue by KarthickAji** [rxweb/rxweb#351]
## Describe the problem statement?
Whenever i am adding the **RxReactiveFormsModule** in app-module.ts or any other module., facing below error.

**Note**: My application is working fine in Chrome. Facing this issue in all other browser(IE/Edge/Safari)

_SCRIPT5021: Invalid range in character set
xxxxx-module.js (2778,25)_

ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk xxx-module failed.

var alphabet = {
    'danish': /^[A-ZÃÃÃ]+$/,
    'french': /^[A-ZÃÃÃÃÃÃÃÃÃÃÃÅÃÃÃÅ¸]+$/,
    'german': /^[A-ZÃÃÃÃ]+$/,
    **_'greek': /^[Î-Ï]+$/,_**            // This is line which cause of this error
    'spanish': /^[a-zÃ±Ã¡Ã©Ã­Ã³ÃºÃ¼]+$/i,
    'russian': /^[Ð-Ð¯Ð]+$/,
};

## Package version
@rxweb/reactive-form-validators 2.0.0-rc2

i am just include the one "RxReactiveFormsModule" module. then my application is not loading properly...Kindly any one suggest the solution this issue?

**Comment by ajayojha** [comment]
@KarthickAji Thanks for reporting this, will check and correct the same.

**Comment by KarthickAji** [comment]
@ajayojha Kindly let me know the estimation date for above bug fix release

**Comment by ajayojha** [comment]
@KarthickAji, Possibly I am planning to release it in the coming weekend.

**Comment by ajayojha** [comment]
@KarthickAji I released the package version of 2.0.0, please update the same. Please let me know if there is an issue.
