### ISSUE TITLE
How can we Bind rx-select with value 0 

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#353]
Example:

I have a drop-down of company which is starting from value 0 
how can I bind this rx-select at the time of edit (if user's company is 0)
Note: it is working fine if user's companyid is 1

**Comment by ajayojha** [comment]
@rachanachag Thanks for reporting this issue, I have released the new version **[0.0.2](https://www.npmjs.com/package/@rxweb/angular)**, Please update your project package, here is the [working example](https://stackblitz.com/edit/rxweb-select-zero-value?file=src%2Fapp%2Fapp.component.ts).

I am closing this ticket as no further action required on this, feel free to create a new ticket if there is any issue :).

**Comment by rachanachag** [comment]
Yes it's working perfectly. Thank you
