### ISSUE TITLE
Rx-select binds with ID on click of Save button

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#354]
Example:

I am using rx-select for company during registration , on click of save button rx-select binds with companyid instead of company name.

**Comment by ajayojha** [comment]
@rachanachag Please refer to the [stackblitz example](https://stackblitz.com/edit/rxweb-select-value?file=src%2Fapp%2Fapp.component.html) for binding the value.

**Comment by rachanachag** [comment]
Yes form values are binding with company Name. But if i Click on save button  drop-down will be bind to companyId.

**Comment by ajayojha** [comment]
@rachanachag Please refer again the same stackblitz example.

**Comment by ajayojha** [comment]
@rachanachag I hope your concern has been resolved with the updated example, Hence I am closing this ticket.
