### ISSUE TITLE
Invalid regular expression: /^[Î‘-Ï‰]+$/ in ng Prod-build package

### ISSUE THREAD

**Issue by KarthickAji** [rxweb/rxweb#355]
# Describe the bug
I am using _rxweb/reactive-form-validators_  for unique check validation(_RxwebValidators.unique(_) ).
I am deploying the ng build --prod package . Whenever i am navigating to the particular validation page ,getting this below error 

_main.js:1 ERROR Error: Uncaught (in promise): SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class
SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class
    at Module.GoCe (11.js:1)
    at i (runtime.js:1)
    at e.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at e.invoke (polyfills.js:1)
    at t.run (polyfills.js:1)
    at polyfills.js:1_

# Expected Behavior

it should work for all browser with deploy the build--prod package

# Package Version
@rxweb/reactive-form-validators": "^2.0.0-rc2"

# Browser
Getting this error in all the browser

**Comment by ajayojha** [comment]
@KarthickAji Please provide ```package.json``` and ```tsconfig.json``` file information.

**Comment by KarthickAji** [comment]
**package.json:**
{
  "name": "xxxxxx",
  "version": "0.0.0",
  "seed-app-version": "5.0.0",
  "scripts": {
    "ng": "ng",
    "dev": "concurrently \"ng serve --public-host=http://localhost:4200/\" \"npm run demo-server\"",
    "dev:internal": "concurrently \"ng serve --public-host=http://localhost:4200/ --host=0.0.0.0\" \"npm run demo-server\"",
    "dev:internal:es5": "concurrently \"ng serve -c es5 --public-host=http://localhost:4200/ --host=0.0.0.0\" \"npm run demo-server\"",
    "dev:https": "ng serve --ssl",
    "dev:es5": "concurrently \"ng serve -c es5\" \"npm run demo-server\"",
    "dev:aot": "concurrently \"ng serve --prod\" \"npm run demo-server\"",
    "dev:aot:https": "ng serve --ssl --prod",
    "sass-lint": "node ./node_modules/sass-lint/bin/sass-lint.js -c ./sass-lint.yml -v -q",
    "start": "ng serve",
    **"build": "npm run lint && ng build --prod --base-href=xxxxxx && npm run gzip:build && npm run zip:build",**
    "build-prod": "npm --proxy=http://http.proxy.fmr.com:8000 install && ng build --prod",
    "package": "npm run build-prod && gulp package",
    "packageAnalysis": "npm run build-prod && gulp package && gulp packageAnalysis",
    "test": "echo 'use npm run test:unit or npm run test:e2e or npm run test:accessibilty instead' && exit 0",
    "test:watch": "ng test --code-coverage --watch=true",
    "test:unit": "ng test",
    "test:unit:singlerun": "ng test --watch=false",
    "test:unit:CICD": "ng test --browsers=WiHeadlessChrome --watch=false",
    "test:e2e": "concurrently  \"npm run demo-server\" \"ng e2e\"",
    "test:e2e:CICD": "concurrently -k --success=first \"npm run demo-server\" \"ng e2e --protractorConfig=e2e/protractor.cicd.conf.js\"",
    "test:accessibility": "echo TODO ADD ACCESSIBILITY TESTING",
    "zip:veracode": "node ./util-scripts/zip-veracode.js",
    "zip:build": "node ./util-scripts/zip-build.js",
    "gzip:build": "node ./util-scripts/gzip-build.js",
    "rename": "node ./util-scripts/rename-app.js",
    "precommit-cc": "ng lint && ng test",
    "prepush-cc": "npm run test",
    "prebundle-report": "ng build --prod --sourcemaps --output-hashing=none --vendor-chunk=false",
    "bundle-report": "source-map-explorer dist/xxxxxx/main.bundle.js",
    "lint": "ng lint",
    "demo-server": "node ./demo/demo-server.js",
    "e2e": "ng e2e",
    
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.13",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/router": "~8.2.13",
    "@rxweb/reactive-form-validators": "^2.0.0-rc2",
    "classlist.js": "^1.1.20150312",
    "concurrently": "^5.1.0",
    "core-js": "^2.6.9",
    "glob": "^7.1.6",
    "hammerjs": "^2.0.8",
    "husky": "^3.0.9",
    "karma-coverage": "^2.0.1",
    "lodash": "^4.17.5",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.17",
    "@angular/cli": "~8.3.17",
    "@angular/compiler-cli": "~8.2.13",
    "@angular/language-service": "~8.2.13",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "archiver": "^3.1.1",
    "codelyzer": "^5.0.0",
    "gulp": "^3.9.1",
    "gulp-zip": "^4.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-spec-reporter": "0.0.32",
    "protractor": "~5.4.0",
    "sass-lint": "^1.13.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-bundle-analyzer": "^3.6.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run precommit-cc",
      "pre-push": "npm run prepush-cc"
    }
  }
}


**tsconfig.json:**

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by KarthickAji** [comment]
@ajayojha  i have ran below build comment to build the prod package,
_npm run lint && ng build --prod --base-href=xxxxxx && npm run gzip:build && npm run zip:build_

**Comment by ajayojha** [comment]
@KarthickAji Thanks for sharing the information. I will try to produce the issue in my local environment.

**Comment by KarthickAji** [comment]
Latest package version solved this issue.Hence close the issue
