### ISSUE TITLE
rx-select does not automatically bind after lose focus

### ISSUE THREAD

**Issue by KamleshDedasaniya** [rxweb/rxweb#357]
If I search something in rx-select dropdown and no result found.
Thn If controls lose focus , rx-select does not bind automatically.

**Comment by ajayojha** [comment]
@KamleshDedasaniya Please fill all necessary parameters of the Bug Template. Otherwise, it's not possible to give you a solution.

**Comment by ajayojha** [comment]
@KamleshDedasaniya I am closing this ticket as no further update on this.

**Comment by rachanachag** [comment]
[example](https://stackblitz.com/edit/rxweb-select-value?file=src%2Fapp%2Fapp.component.html)

1) In above stack-blitz , search any value which does not exist in dropdown.
2) Click on anywhere else except drop down.
3) Now, please select drop down , at that time drop down does not bind automatically.
