### ISSUE TITLE
Sanitizers aren't executed when calling .value on a FormGroup

### ISSUE THREAD

**Issue by EvilVir** [rxweb/rxweb#359]
# Describe the bug
I have a model with `number` properties, annotated with `@toDouble()` so I expect that value kept in the formGroup object will be of type `number`. But then when I call `formGroup.value` to obtain object that will be sent down the wire to the API the numeric values are of type string.

# Expected Behavior

When `.value` is called on a `FormGroup` object, sanitizer should be executed and convert each property to desired type.

So after JSON serialization example data (used in StackBlitz example provided) should look like this:

```
{"totalAmount":123.123}
```

But instead it looks like this (note the quotes around value):

```
{"totalAmount":"123.123"}
```

# Url (stackblitz or plunker or other)
https://angular-t848bp.stackblitz.io

# Package Version
    "@rxweb/reactive-form-validators": "^1.9.9",
    "@rxweb/sanitizers": "0.0.1-1",

**Comment by ajayojha** [comment]
Please try like this ```formGroup.modelInstance.totalAmount``` or ```formGroup.modelInstance```

**Comment by ajayojha** [comment]
@EvilVir I am assuming that your concern has been resolved with the previous comment. Hence I am closing this ticket as there is no further update. Feel free to create a new ticket if there is an issue.
