### ISSUE TITLE
How to Apply Validation on Inline Grid Control

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#362]
## Describe the problem statement?
I have a grid,which contains multiple textbox as inline grid control,and need to apply required validation on that controls.
so,how to apply validation on inline grid control.

## Package version
@rxweb/

**Comment by ajayojha** [comment]
@Kiran-Pawar  Manually you have to manage whenever the value will be changed.

**Comment by ajayojha** [comment]
@Kiran-Pawar I am closing the ticket as no further action required.
