### ISSUE TITLE
Not able to use "Global Filter" feature of Rxwebcore

### ISSUE THREAD

**Issue by manalijn625** [rxweb/rxweb#363]
I have created a extended model in main folder of Models project named ActiveFilter.cs and create a function IsActive into it.
I written code as mentioned in Rxwebcore website :

   
    public Expression> IsActive()
                {
                    return x => x.StatusId == 1;
                }

this is showing me error as "cannot convert Lamda expression to type 'Expression' because it is not delegate type

I should be able to use global filter successfully

Url is  https://docs.rxweb.io/rx-web-core/working-with-data-model/advance/global-filter

## Package version : 1.1.5
@rxweb/

**Comment by Ushmidave** [comment]
@manalijn625  The extended model filter class ActiveFilter.cs would be

```js
 public class ActiveFilter
    {
        public Expression<Func<vUser, bool>> IsActive()
        {
            return x => x.StatusId == 1;
        }
    }
```
Please comment below if any queries

**Comment by manalijn625** [comment]
I have replaced the code you have given. It is showing error at StatusId as it is not present in vUser. As per document StatusId is in application objects, giving screenshot as below :
![screenshot](https://user-images.githubusercontent.com/65900639/87511948-d4befd00-c693-11ea-9f48-1633e2534783.png)

**Comment by Ushmidave** [comment]
@manalijn625 Add the property in the respective view based upon which you want to filter the data

**Comment by manalijn625** [comment]
ok
