### ISSUE TITLE
 Compare and pattern validation not working.

### ISSUE THREAD

**Issue by manalijn625** [rxweb/rxweb#369]
# Describe the bug
Example of Dynamic in compare validation of relational  is not working in stackblitz.
Example of Dynamic in pattern validation of custom is not working in stackblitz.

# Expected Behavior
Code mentioned in the website is not working. it should validation message if incorrect input given.

# To Reproduce
run following links:
https://run.stackblitz.com/api/angular/v1?file=src/app/compare-dynamic.component.ts

https://stackblitz.com/angular/omlkxgbpyrd?file=src%2Fapp%2Fpattern-dynamic.component.ts

# Url (stackblitz or plunker or other)
https://run.stackblitz.com/api/angular/v1?file=src/app/compare-dynamic.component.ts

https://stackblitz.com/angular/omlkxgbpyrd?file=src%2Fapp%2Fpattern-dynamic.component.ts

# Package Version
@rxweb/reactive-form-validators

**Comment by ajayojha** [comment]
Please create two separate tickets with the appropriate information, Hence I am closing this ticket as not according to the issue guideline.
