### ISSUE TITLE
MaxLength validation for Text Area is not working properly

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#371]
# Describe the bug
I have a textarea with 4000 maxlength. 
If I copy paste 5000 length text the text area don't shows validation message.
If I copy paste 3500 length text and keep on copying text till it crosses 4000 it shows validation message.

# Expected Behavior
If I copy paste any length text more than 4000 the text area should shows validation message.

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-6ey4g9-qh56qv

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by Ushmidave** [comment]
@diptip09 The validation is working as expected, you just need to change ` *ngIf="locationFormGroup.controls.firstName.errors"` to  ` *ngIf="locationFormGroup.controls.auditText.errors"` in the provided stackblitz

**Comment by diptip09** [comment]
https://angular-6ey4g9-qqy6eu.stackblitz.io

**Comment by diptip09** [comment]
https://stackblitz.com/edit/angular-6ey4g9-qqy6eu?file=src%2Fapp%2Fmax-length-add.component.html

Check for text around 5000 the issue is occuring

**Comment by ajayojha** [comment]
@diptip09 it's working as expected, please refer to the below snap. 
![maxlength](https://user-images.githubusercontent.com/20392302/88148919-f2084400-cc1c-11ea-9d62-e851fc1043c7.gif)
Please let me if I missed something.

**Comment by ajayojha** [comment]
@diptip09 As there is no further update on this ticket, hence I am closing this ticket.
