### ISSUE TITLE
Rx-Translate - Page Title is not working language wise using "pageTitle"

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#372]
I have used "pageTitle" as suggested in
[reference]( https://docs.rxweb.io/ngx-translate-extension/other-intuitive-features ) sometime it is not working
Please check the stackblitz [here](https://stackblitz.com/edit/rxweb-validation-message-with-parameters-nnjyzs?file=src%2Fapp%2Fglobal%2Fglobal.component.html)

1) when First time I click on "Open in new tab" , it shows undefined
2) After clicking on "French" button it shows french page title" and after clicking on "English" button it still shows french page title

**Comment by ajayojha** [comment]
@rachanachag The issue has been fixed in the latest release. Please update the project package with the latest version of @rxweb/translate@1.0.12.

**Comment by rachanachag** [comment]
I have updated the package as suggested (@rxweb/translate": "^1.0.12") , Previously I was using  ("@rxweb/translate": "^1.0.11")

after update, I am getting this error 
**Error: This constructor was not compatible with Dependency Injection.Type a message**

**Comment by rachanachag** [comment]
![image](https://user-images.githubusercontent.com/46072385/89511923-228cd800-d7f0-11ea-9ffd-c3565b4a714a.png)

**Comment by rachanachag** [comment]
![image](https://user-images.githubusercontent.com/46072385/89512083-57992a80-d7f0-11ea-9b32-64c999556558.png)

**Comment by ajayojha** [comment]
@rachanachag Please try with the latest version 1.0.13.

**Comment by rachanachag** [comment]
ok
