### ISSUE TITLE
Memory leaks in the Angular package

### ISSUE THREAD

**Issue by Xambey** [rxweb/rxweb#373]
If an observer is used, then in the absence of unsubscribe () or operator takeUntil($ subject) there will be a memory leak after the component is destroyed. More details [here](https://medium.com/angular-in-depth/the-best-way-to-unsubscribe-rxjs-observable-in-the-angular-applications-d8f9aa42f6a0)

https://github.com/rxweb/rxweb/blob/01bed4028bce7524c247b4c4ffee99d69b575cdc/client-side/angular/packages/angular/select/rx-select.component.ts#L243

**Comment by ajayojha** [comment]
Thanks for reporting this, I missed to 'unsubscribe', will add the same.
