### ISSUE TITLE
Rx-tag 'toString of null' error

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#376]
# Bug

When the page is loaded and form control is bind with rx-tag control then a console error is displayed 'toString of null'. This occurs majorly in search/add screens where at load time no value is selected for that control which causes that error. It works fine in edit screen where atleast one value is selected for rx-tag. 

![rxtagError](https://user-images.githubusercontent.com/61281539/88761596-0e602f80-d18d-11ea-9d42-fa21afcb140f.JPG)

# Expected Behavior
Console error should not occur when no value is selected for rx-tag control

# Stackblitz

https://stackblitz.com/edit/angular-zpaywi

# Package Version
@rxweb/angular@0.0.2

**Comment by ajayojha** [comment]
@mitanshu-patel  please provide the stackblitz code editor URL

**Comment by ajayojha** [comment]
@mitanshu-patel I have released the new package(0.0.3), please update the same. I am closing this ticket as no further action required.
