### ISSUE TITLE
[Feature] Add getValidators() method in RxFormControl

### ISSUE THREAD

**Issue by Xambey** [rxweb/rxweb#377]
### Description
Add getValidators() method in RxFormControl. Needed for manual reloading of validators. Angular doesn't provide this [method](https://github.com/angular/angular/issues/13461)

### Describe the solution you'd like
Add method getValidators(): RxFormControl[] to RxFormControl

**Comment by ajayojha** [comment]
@Xambey Thanks for this ticket. The feature is available in the 2.1.0 release. Please use the interface of ```IFormGroup``` for accessing the method of 'getValidators'.
