### ISSUE TITLE
max length with keyup validation

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#379]
My field has max length validation of 10. I have keyup event that removes all characters but digits from input value and replaces value again in field. When I try to put 11th letter in the field if the letter is invalid letter is being removed by the keyup event but my fields remains invalid.

# Expected Behavior
When I try to put 11th letter in the field if the letter is invalid letter is being removed by the keyup event but my fields should turn valid as invalid value(11th letter) is removed.

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-tqvswe?embed=1&file=src/app/max-length-add.component.ts

# Package Version

**Comment by Ushmidave** [comment]
@diptip09 This issue is coming because you have replaced with blank string and so the value exceeds and thus the input remains invalid, I would rather suggest you to opt the approach of using mask validation, Please let me know if any further help required.

**Comment by ajayojha** [comment]
@diptip09 please the value of respective FormControl instead of element 'value'. Here is a modified code that I have changed in the provided example.
```js
this.locationFormGroup.controls.firstName.setValue(inputValue.replace(/\D/g, ''));
```
[Stackblitz Example](https://stackblitz.com/edit/angular-tqvswe-xjo6fa?embed=1&file=src/app/max-length-add.component.ts)
