### ISSUE TITLE
mask is invalidating the field after receiving data from the server

### ISSUE THREAD

**Issue by mlibanori** [rxweb/rxweb#381]
# Describe the bug
I'm receiving the data from the server and applying it on the form using the command patchValue, but the fields that have masks are not being formatted and when clicking on the field the mask reappears but the field becomes invalid

# To Reproduce
Click on field phone in the example 
https://stackblitz.com/edit/rxweb-reactive-form-validation-angular-user-edit-form-sjtoe2

# Url (stackblitz or plunker or other)
[Test](https://stackblitz.com/edit/rxweb-reactive-form-validation-angular-user-edit-form-sjtoe2)

# Package Version
@rxweb/reactive-form-validators@2.0

**Comment by ajayojha** [comment]
@mlibanori The issue has been fixed in 2.1.0 release. Please update the project package. I have updated the package in the provided stackblitz example, please refer to [this link](https://stackblitz.com/edit/rxweb-mask-validator-during-patch-value?file=src/app/app.component.ts).
