### ISSUE TITLE
Scaffolding Models using RxWebCore Cli gives error 

### ISSUE THREAD

**Issue by Ushmidave** [rxweb/rxweb#382]
# Describe the bug
After completing database setup generating models using the below command returns compile time errors

> rxwebcore --models --main

![Capture50](https://user-images.githubusercontent.com/46391540/89373496-76bb8d80-d706-11ea-962c-64fadeba4cdb.PNG)

# Expected Behavior
The POCO model classes should not produce errors during build 

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
@RxWebCore --version 1.2.2

**Comment by ajayojha** [comment]
@Ushmidave Please update the package of RxWebCore.Data.
