### ISSUE TITLE
Dynamic form - Validations are not working 

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#384]
I  have used @rxweb/reactive-dynamic-forms in my project which is working fine  except validations [stackblitz ](https://stackblitz.com/edit/rxweb-validation-message-with-parameters-vkkwsw?file=src%2Fapp%2Fglobal%2Fglobal.component.ts)
1) Validations are not working .
2) How can I change date format for dynamic form date control?
3)  How can I use Multilingual validation(RX-translate) in this case.

**Comment by Ushmidave** [comment]
@rachanachag  multilingual validation messages wont work in case of dynamic forms

**Comment by rachanachag** [comment]
Hi @Ushmidave , can you please check in stackblitz  normal validations are also not working in my case.

**Comment by Ushmidave** [comment]
@rachanachag based upon my understanding on point 1 and 3, 
Answer 1 : Validations in dynamic form [example](https://stackblitz.com/edit/rxweb-validation-message-with-parameters-drey99?file=src/app/app.component.ts)
Answer 3: Please create new feature request, for creating please this link : https://github.com/rxweb/rxweb/issues/new?template=feature-request.md

**Comment by rachanachag** [comment]
Hi @Ushmidave , I have followed the same example from document. I have shared stackblitz. But I am not getting exact same result. could you please look into it and also let me know if I am missing something and also please let me know what can be done for Point number 2 (How can I change date format for dynamic form date control?
)

**Comment by Ushmidave** [comment]
@rachanachag  you have missed setting the `ReactiveFormConfig` part in the app component, kindly check will come to the point 2 soon

**Comment by rachanachag** [comment]
Thank you for the reply.

**Comment by ajayojha** [comment]
@rachanachag I am closing this ticket as no action further action required on this, once the multilingual translation feature will be added in the reactive-form-validators package then it will be available in the dynamic form package.

**Comment by rachanachag** [comment]
Hello @ajayojha , could you please also let me know above question : How can I change date format for dynamic form date control?
