### ISSUE TITLE
grid.updateSource() not working properly

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#387]
# Bug
I've a grid in which there's a header checkbox, rx-select  and an individual checkbox for each record in grid. So based on state of header checkbox , state of those individual checkboxes will get changed. If I check the header checkbox then all the checkboxes will get checked and if I uncheck header checkbox then all the checkboxes will get unchecked. To manage state of those checkboxes I need to update data of grid, for which I've used `grid.updateSource()` method. When this method is called, page becomes **unresponsive** and eventually page **crashes**. This issue is found  when **rx-select component** is bind in grid. Whereas updateSource method works fine with `<rx-grid>` 

UI of grid:-
![gridheader](https://user-images.githubusercontent.com/61281539/90511106-a2645c00-e179-11ea-954d-332f71352279.JPG)

# Expected Behavior
When `grid.updateSource()` is called, it should update the source data of grid and page should not get unresponsive.

# Url 
Here I am sharing stackblitz url, it doesn't have select all functionality logic. However it includes call of `updateSource()` method to reproduce the bug:-
https://stackblitz.com/edit/angular-2nr9vv?file=src/app/app.component.ts

# Package Version
@rxweb/grid@0.0.2-beta8

**Comment by ajayojha** [comment]
@mitanshu-patel I have released the new package of the grid, please update the same. Please refer to the [working example with updated package](https://stackblitz.com/edit/rxweb-grid-update-source-custom-component?file=src/app/app.component.ts).
