### ISSUE TITLE
rx-select with more than one dropdown

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#390]
## Describe the problem statement?
one html can have more than one drop down then working with keyboard scrollbar is working fine in first drop down but scrollbar not working in second dropd own from keyboard key

## The expected solution you would like
scrollbar working as expected in another drop down

## Url
https://stackblitz.com/edit/angular-rx-select
## Package version
@rxweb/

**Comment by ajayojha** [comment]
@afzalmansuri Please update the project with the latest package of 0.0.4, Please refer to [the working example](https://stackblitz.com/edit/angular-rx-select-zowxfq).

**Comment by afzalmansuri** [comment]
@ajayojha Sir It Works.Thanks for checking this.
