### ISSUE TITLE
File Extension validator to exclude list of extensions

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#393]
Existing Reactive form validators allow files with extensions in provided list. Please provide us a validator that can restrict files with extensions in provided list.
Ex. [exe, iso]
I want to throw validation message when any file with extension .exe or .iso is selected

**Comment by ajayojha** [comment]
@diptip09 Thanks for this feature request. I have released the new version 2.1.0, please update the same. I have added a new property of 'isExcludeExtensions'. Please refer to [this example ](https://stackblitz.com/edit/rxweb-extension-validator-for-excluding-extensions?file=src/app/extension-add.component.ts)for more information.
