### ISSUE TITLE
Sorting and filter icons are not visible for child grid

### ISSUE THREAD

**Issue by KamleshDedasaniya** [rxweb/rxweb#395]
1. I have main grid and child grid in my project.sorting and filter icons are visible in main grid but not visible in child grid . I am using same template for sorting icon.

2. Could you please help me with this?How can I handle pagination for child grid at server side?

![image](https://user-images.githubusercontent.com/55527396/91532662-3a0d3b80-e92c-11ea-80f5-4b7691947f2c.png)

**Comment by ajayojha** [comment]
@KamleshDedasaniya please provide the stackblitz url.

**Comment by ajayojha** [comment]
@KamleshDedasaniya I am closing this ticket as no further update on this.
