### ISSUE TITLE
Sorting not working on sort icon

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#396]
# Bug

Sorting in grid is not working properly. When sort icon is clicked, nothing happens but when we click on Header title then sorting works fine. This issue is faced in latest version of grid. In previous versions sort icon did sort the grid data.

UI of grid:-
![gridSortIssue](https://user-images.githubusercontent.com/61281539/91810809-2a536700-ec4c-11ea-96a7-f4708b2cb132.JPG)

# Expected Behavior
   Sorting should occur when we click on sort icon.

# To Reproduce
   Try to sort data by clicking on sort icon.

# Url
  https://stackblitz.com/edit/simple-grid?file=src/app/app.component.html

# Package Version
@rxweb/grid@0.2.2

**Comment by ajayojha** [comment]
@mitanshu-patel Please manage this through CSS.

**Comment by mitanshu-patel** [comment]
But it worked in previous versions. It won't be feasible through CSS as we need sort function call on the icon.

**Comment by mitanshu-patel** [comment]
> But it worked in previous versions. It won't be feasible through CSS as we need sort function call on the icon.

@ajayojha  Can you please provide help/solution regarding this? It is impacting whole application as sort icon sorting isn't working in all the grids which used to work before.

**Comment by ajayojha** [comment]
@mitanshu-patel Sorry It was my reading mistake. I have released the new version(0.2.3), please update the same. I have updated the package in the [provided example](https://stackblitz.com/edit/simple-grid-4beuae?file=src%2Fapp%2Fapp.component.ts).
