### ISSUE TITLE
Not indexed key name format for FileList properties

### ISSUE THREAD

**Issue by mehmetcuneyit** [rxweb/rxweb#399]
### Description
![image](https://user-images.githubusercontent.com/39027858/92538158-42277e00-f23e-11ea-855b-38457f9e6409.png)

- When I use ```const formData: FormData = (this.formGroup as FormGroupExtension).toFormData()``` , key names inside 'formData' comes with indexed format for FileList (input type:file element in html)
- the property name is '**imageFile**' and type is 'file', but formData key name is '**imageFile[0]**' since I selected only one file but the method generates all index key names according to the FileList size. 
### Describe the solution you'd like

- Being able to use the property name without indexed format with the FileList values.

**Comment by ajayojha** [comment]
@mehmetcuneyit Thanks for this ticket, I have released the new version(2.1.1), please update the same.
