### ISSUE TITLE
rxdatepicker adds timezone hours automatically for selected date

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#400]
We are using rxdatepicker in angular UI, after selecting date when I hit Save button my form group holds proper date with current time when it hits API call it does UTC conversion automatically. 

I believe the issue you are facing is back date.

**Comment by ajayojha** [comment]
@diptip09 please provide the stackblitz url.

**Comment by ajayojha** [comment]
as there is no update on this ticket, hence I am closing this ticket.
