### ISSUE TITLE
RxGrid, need a provision to hide Row Count Select dropdown

### ISSUE THREAD

**Issue by diptip09** [rxweb/rxweb#401]
In our application, we want to use rx grid in modal popup, we cannot allow user to select row count more than 10 due to design limitations of modal popup. Hence we need a facility to hide row count dropdown.

![Rowcount ddl](https://user-images.githubusercontent.com/62141853/93218844-4c8ad000-f788-11ea-8f52-7fd132d39273.png)

**Comment by ajayojha** [comment]
I would suggest please assign the source of the drop down max 10 like: [2,5,10];

**Comment by ajayojha** [comment]
I hope your concern has been resolved, as there is no further action required from my end, hence I am closing this ticket.
