### ISSUE TITLE
Methods removeAt() and clear() missing in IFormArray

### ISSUE THREAD

**Issue by folkmanis** [rxweb/rxweb#403]
# Describe the bug

**IFormArray** interface is missing FormArray methods **removeAt** and **clear**

# Expected Behavior

Missing method definitions 
    **removeAt(index: number): void;**
    **clear(): void**
should be added to IFormArray interface to correctly reflect the FormArray class.

References to corresponding Angular documentation
https://angular.io/api/forms/FormArray#removeat
https://angular.io/api/forms/FormArray#clear

# Package Version
@rxweb/types@^1.0.5

**Comment by ajayojha** [comment]
@folkmanis Thanks for reporting this, I have fixed and released the same, please update the package with version 1.0.6.

**Comment by ajayojha** [comment]
@folkmanis Thanks for reporting this, I have fixed and released the same, please update the package with version 1.0.6.
