### ISSUE TITLE
Create decorator that sets up AbstractControlOptions updateOn property

### ISSUE THREAD

**Issue by xzxzxc** [rxweb/rxweb#404]
### Description
As I understand from documentation, there is no decorator that sets up AbstractControlOptions updateOn property. It would be very useful to have one.

### Describe the solution you'd like

``` typescript
class User {
  @updateOn('blur')
  firstName: string;

  @updateOn('blur')
  lastName: string;
}
```

**Comment by dmitrye** [comment]
@ajayojha When is this feature going to be released? I'm actually looking for the same enhancement.

**Comment by ajayojha** [comment]
@xzxzxc This feature has been released in the version of 2.1.3.

**Comment by jure123** [comment]
@ajayojha, I think this issue has not added @updateOn() decorator for model driven validation (model decorator doesn't exist in 2.1.4). In your commit https://github.com/rxweb/rxweb/commit/814132be185607daa7db4c980832e46641110c49 you only added "updateOn" in DECORATORS.ts and ProperyInfo.ts, but there is actually no decorator/update-on.decorator.ts implementation.

Maybe the option could rather be added into @prop() directive, like @prop( {updateOn: 'blur' }). Currently in 2.1.4 PropConfig interface does not have this property.

**Comment by arnaldorigo** [comment]
@ajayojha is there an _updatedOn_ decorator working example? I'm using the 2.1.6 version but I don't find it in the code neither in the documentation.

I'm using decorated model and I also tried to achieve the goal like in the following line. but runtime error below:

`this.units.push(this.formBuilder.formGroup(new UnitLine(), {abstractControlOptions: {amount: 'blur'}}))`

```
Error detected, emitting error event: {"internalErrorMessage":"Cannot read properties of undefined (reading 'prototype')"} TypeError: Cannot read properties of undefined (reading 'prototype')
    at getInstance (rxweb-reactive-form-validators.js:1318:1)
    at instanceProvider (rxweb-reactive-form-validators.js:1303:1)
    at RxFormBuilder.updateObject (rxweb-reactive-form-validators.js:1377:1)
    at RxFormBuilder.formGroup (rxweb-reactive-form-validators.js:4261:1)
    at ProposeFormComponent.onAddLine (propose-form.component.ts:201:38)
```
Thanks in advance for any help

**Comment by ajayojha** [comment]
@jure123 Sorry, I missed reviewing your comment.

@arnaldorigo Need to check the code. Update here as soon as I have something on this.

**Comment by arnaldorigo** [comment]
thanks no problem!

**Comment by arnaldorigo** [comment]
Dear @ajayojha,
did you have any opportunity to check the scenario? The possibility to have update/validation on blur using the decorator would be extremely helpful.
Thanks

**Comment by ajayojha** [comment]
@arnaldorigo the feature has been added and the package will be released soon.

Here is a code example:

```js
export class UserInfo {

        @updateOn({runOn:'blur'})
	@required() 
	firstName: string;
}
```
