### ISSUE TITLE
RxwebValidators.url wrong validate 2 symbols host

### ISSUE THREAD

**Issue by Smip** [rxweb/rxweb#405]
# Describe the bug
The Validator RxwebValidators.url doesn't validate correctly URL where a host has 2 characters. For example, https://fb.com is correct URL, but the validator returns the error.

RxwebValidators.url to validate a URL [uses regexp](https://github.com/rxweb/rxweb/blob/01bed4028b/client-side/angular/packages/reactive-form-validators/util/regex-rules.ts#L46): 
`^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})$ `

This regexp require minimum 3 characters in the host.

To fix it I suggest change + to *:
`^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})$ `

# Url (stackblitz or plunker or other)
https://regex101.com/r/xmfQU9/1

# Package Version
@rxweb/reactive-form-validators@2.1.0

**Comment by ajayojha** [comment]
@Smip Thanks for this ticket and mentioning the regex, which helps me a lot. I have released the new version(2.1.1), please update the package.
