### ISSUE TITLE
In lazy loading angular app, shared components not loading properly due translation keys are not available in shared component html.

### ISSUE THREAD

**Issue by jagadeeshjsh** [rxweb/rxweb#409]
## Package version
    "@rxweb/cli": "0.0.10",
    "@rxweb/translate": "^1.0.13",
@rxweb/

**Comment by Ushmidave** [comment]
@jagadeeshjsh in my project i have lazy loading component and commonly resolved shared component translation, it is resolving the translation objects based on the keys after browser tab change, have a look at the below gif 

![git-issue](https://user-images.githubusercontent.com/46391540/94574316-9c8d8a80-0290-11eb-935b-5c2efcf794cd.gif)

This is made using the reference of the git example of lazy loading translation provided in the repository, please refer [Example](https://github.com/rxweb/rxweb/tree/master/examples/client-side/angular/translate/decorator-based-translation/src/app/lazy-load)

**Comment by ajayojha** [comment]
@jagadeeshjsh I hope the issue has been resolved, as there is no further update hence I am closing this ticket. feel free to create a new ticket or reopen this if there is any issue.
