### ISSUE TITLE
Error in model generation.

### ISSUE THREAD

**Issue by jchetan007** [rxweb/rxweb#412]
# Describe the bug
Whenever I try to generate new models through "rxwebcore --models --main" command, models are generated with wrong sequence. Import statements of the models are written inside the class.

![error](https://user-images.githubusercontent.com/61500514/94653608-75c76680-0319-11eb-9cd4-79e8679536d7.png)

# Expected Behavior

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/RxWebCore@1.1

**Comment by ajayojha** [comment]
@jchetan007  can you please delete all files and generate it again

**Comment by jchetan007** [comment]
> @jchetan007 can you please delete all files and generate it again

I have done the same two times already.

**Comment by jchetan007** [comment]
@ajayojha  Hello sir, every time I have to delete all the models and then generate it through the generator, but in Project level it is not possible to delete all the models and re-generate them again and again as we have to define some properties to it and needs to modify as per business logic, so it is very difficult to delete the models and generate it again.
Please suggest a legitimate solution for it.
