### ISSUE TITLE
Rx-tag random sort issue

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#413]
# Bug
When any data is bind in rx-tag then on page load it automatically changes the sequence of items bound in rx-tag control. Which results in incorrect sorting of rx-tag dropsource. However, when we place focus on rx-tag and press backspace key then it changes the sequence of the options.

# Expected Behavior
Dropdown options should be bind in rx-tag with given sequence as in source which is used for it.

# Url (stackblitz)
https://stackblitz.com/edit/angular-typlth?file=src/app/hello.component.html

# Package Version
@rxweb/angular@0.0.4

**Comment by ajayojha** [comment]
@mitanshu-patel Please update the package version of 0.0.7, the source sorting is the default feature of the rxtag, if you wish to disable it then please use ```isSort``` attribute with the value of ```false```. by doing this the source will not be sorted. if you want to disable sorting sourcing throughout the application then put that in the global configuration of the rxtag like : ```control.rx-tag.is-sort```. Please refer to this link (https://stackblitz.com/edit/rxtag-disable-sorting?file=src/app/hello.component.html)
