### ISSUE TITLE
Bug with greaterThan or greaterThanEqualTo

### ISSUE THREAD

**Issue by kelvinsleonardo** [rxweb/rxweb#415]
# Describe the bug
The form keep valid when i change the first field "min". I reported previouly this bug with form array dynamic check in [link].(https://github.com/rxweb/rxweb/issues/274)

# Expected Behavior
Propagate validation after change first field

# To Reproduce
  <li>Put value 10 in field min</li>
  <li>Put value 11 in field max</li>
  <li>Change value in field min to 12</li>

# Url (stackblitz or plunker or other)
https://codesandbox.io/s/bug-rx-web-validator-sdkfe?file=/src/app/app.component.css

# Package Version
@@rxweb/reactive-form-validators@2.1.2

**Comment by kelvinsleonardo** [comment]
@ajayojha any idea?

**Comment by ajayojha** [comment]
Sorry didn’t get time to review the ticket, tomorrow will let you know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
@kelvinsleonardo I have referred the provided code, the value of `fieldName` is incorrect, I have changed the `fieldName` value and now it's working fine.
##### Before
```js
RxwebValidators.greaterThan({ fieldName: "valueMinimum" }),
```

##### After
```js
RxwebValidators.greaterThan({ fieldName: "min" }),
```

**Comment by ajayojha** [comment]
@kelvinsleonardo Sorry, there is an issue, but it's coming in my local repo, will update you soon.

**Comment by ajayojha** [comment]
@kelvinsleonardo There is no issue, you have to import the `RxReactiveFormsModule`, please refer to this working example: https://codesandbox.io/s/bug-rx-web-validator-forked-lbvmx?file=/src/app/app.module.ts

As no further action required on this, hence I am closing this ticket :).
