### ISSUE TITLE
[Feature] Updating child validation when calling updateValueAndValidity

### ISSUE THREAD

**Issue by Xambey** [rxweb/rxweb#418]
### Description
Angular has the [problem](https://github.com/angular/angular/issues/6170),  that does not provide a way to explicitly validate group? (ex. RxFormArray and RxFormGroup), can you fix it?

### Describe the solution you'd like
Add a new implementation for this method

**Comment by ajayojha** [comment]
@Xambey I have referred the mentioned ticket information, I think we already have in our package, differently; I don't whether you are aware or not about the error messaging strategy; if you refer to that, I think that solves the mentioned problem. If I am missing anything, then please correct me the same.

**Comment by ajayojha** [comment]
@Xambey I am closing this ticket, as no further update on this.
