### ISSUE TITLE
Rx-Grid need help with checkbox

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#419]
[Stackblitz](https://stackblitz.com/edit/angular-ivy-1kijoc)

we are facing the below issue in above created stackblitz.
Issue 1)
1) Set page records = 10
2) Go to Second Page= tick any checkbox
3) Due to the refresh grid function it will take the grid to the first page

Issue 2)
1) Select 10 records from grid
2) Select any checkbox

**Comment by ajayojha** [comment]
@rachanachag Please update the project package of @rxweb/dom and @rxweb/grid, now onwards there is no need to call the `refresh` method. please refer to the update example https://stackblitz.com/edit/rxweb-grid-paging-checkbox?file=src/app/app.component.ts

**Comment by rachanachag** [comment]
Thank you for the update.
