### ISSUE TITLE
rx-select does not automatically bind after lose focus

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#420]
[example](https://stackblitz.com/edit/rxweb-select-value?file=src%2Fapp%2Fapp.component.html)

1) In above stack-blitz , search any value which does not exist in drop-down.
2) Click on anywhere else except drop down.
3) Now, please select drop down , at that time drop down does not bind automatically.

(It will work after clicking back space)

**Comment by ajayojha** [comment]
@rachanachag the issue has been fixed in the latest release, please refer to this stackblitz example https://stackblitz.com/edit/rxweb-select-value-qmxysb?file=src%2Fapp%2Fapp.component.html

**Comment by rachanachag** [comment]
Thank you for the update
