### ISSUE TITLE
Rx-Tag Update source issue

### ISSUE THREAD

**Issue by kunal-Rojasara** [rxweb/rxweb#421]
# Describe the bug

The source given to Rx-Tag is dependent on other field so if the other field changes the source given to Rx-Tag also changes,
the source is getting updated accordingly but it is not getting reflected in UI (In Dropdown of Rx-Tag)

# Expected Behavior

While updating the source of Rx-Tag, in UI the dropdown should display the updated source value,as the source value is updated by the code and according to condition but not displaying in the dropdown of Rx-Tag.

# To Reproduce

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-ivy-wdzmmv?file=src%2Fapp%2Fhello.component.html

# Package Version
@rxweb/angular@0.0.7

**Comment by ajayojha** [comment]
@kunal-Rojasara you have to call the method of 'changeTagSource'. I have updated the provided example code, please refer to this link: https://stackblitz.com/edit/angular-ivy-rfx3qy?file=src%2Fapp%2Fhello.component.html
