### ISSUE TITLE
Need help in client side rx-grid configuration

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#423]
## Describe the problem statement?
I'm working with client side grid here if i'm configuration for it all the records are displays in one page even i have set
maxperpage property to default value but it didn't bind as per configuration and also pagination didn't works

## Url

https://stackblitz.com/edit/angular-rx-grid-retnag?file=src%2Fapp%2Fapp.component.ts

## Package version
@rxweb/grid: 0.2.3

**Comment by Ushmidave** [comment]
@afzalmansuri you need to rebind the grid on `onPageChanging` method based upon the number of the page selected, please refer this example https://stackblitz.com/edit/angular-rx-grid-update-soure-8qzbxu?file=src/app/app.component.ts

**Comment by ajayojha** [comment]
@afzalmansuri I hope you got the solution, hence I am closing this ticket.
