### ISSUE TITLE
An error occurred during a cryptographic operation - 717 is an invalid input length

### ISSUE THREAD

**Issue by ahmad-devlop** [rxweb/rxweb#424]
Hello,
1. Cloning this repo.
2. `cd  RxWebCore-master\src\Samples\AspNetCore\Documentation Examples\HumanResourceApplication`
3. RxWebCore CLI Installation `dotnet tool install --global RxWebCore` Result: `Done`
4. `rxwebcore --init` 
5. Database Setup `rxwebcore --database-setup` 
6. Running The Project

**But unfortunately, when trying to test the API using Swagger UI:**

`curl -X POST "https://localhost:44301/api/Authentication" -H "accept: */*" -H "Authorization: Bearer CfDJ8C2-4Bwf8ZFDvsqtZlL3O5aQvmDNjdbP2JnOvFjLzy74d6M80j_iNGhIj74GDabhHgtdrnhzYrD6GhRxdbOdBFejhtV3hF0SdooRdPJvP2nW1GvHkbSfmsRyPE5PrAgg1S3JkzDdHAWKLU1n684oYjmzCy1xghQlf7TCyXf43Y3DWdZMUncapip7fkyg7D8NrxyUHCS8adIsoDYnQ5nZpA3xrspV9J5PPOjATFnKRsJYXQBiG6F4MBqM0pOWdY717LBd9AifSF3d0i1Pkh300au9OFB9-vkb0GDU2O7Tm-UE7qGPUUqioaJPLwfwHPFKfCcofXVeP-u8J4N-zXUnmSfyjIBa_7W_BD-nbJUMwZBwlw7TAIa5o31vBG-pxEMXDvNc9WvkdXB5A3lbFYVMV586rPGU7Fnx4an3PY2c4kZcrXQTet54xox0Vd2B4F8c8h-_EAYppmUuN9DD3RQfzqmg_g6Ryu0OlCYe43wHovaWwhz5nBzlhU5dVDitX80Eg1beKPentskQYO0SFzSqFHlqU3X9KpoazU3MJaNYy8lCy48nST2HuJj1owPf8C7DQz4AIgTAEMs2p5Cu5cvCg2fcgNCFrJofOET3MghZVgu2WXpiRQyTP3Mf7Fol2FNBT2t7WGISUkKFCqPxnjRtaL2eiUGXbHfOpf1D1_5BANONSEVu-xv2RmZ4DeQ0Spc1oA" -H "Content-Type: application/json-patch+json" -d "{\"userName\":\"admin\",\"password\":\"admin\"}"`

**Result Error:**
![image](https://user-images.githubusercontent.com/72513193/96854530-444b4200-1464-11eb-95b3-11f6391b313f.png)

```C#
namespace HumanResourceApplication.Infrastructure.Security
{
  public class TokenAuthorizer : ITokenAuthorizer
  {
    ....
    public ClaimsPrincipal AnonymousUserValidateToken(HttpContext context)
    {
      if (context.Request.Headers.TryGetValue(AUTHORIZATION_HEADER, out var token) && context.Request.Cookies.TryGetValue("anonymous", out var anonymousUser))
        **return this.TokenProvider.ValidateToken(anonymousUser, token);**
      return null;
    }
 ......
```

**Exception:**
_System.Security.Cryptography.CryptographicException: 'An error occurred during a cryptographic operation.'
Inner Exception: FormatException: Malformed input: 717 is an invalid input length._

![image](https://user-images.githubusercontent.com/72513193/96854984-cb98b580-1464-11eb-977a-7f73184913f9.png)

## Package version
@rxweb/1.2.2 (Latest)

**Comment by Ushmidave** [comment]
@ahmad-devlop clear the cookie and again hit the get authentication api, pass it using the authorize button and then hit the post authentication method

**Comment by ahmad-devlop** [comment]
> @ahmad-devlop clear the cookie and again hit the get authentication api, pass it using the authorize button and then hit the post authentication method

Tried to do that and using **Private Window** too, but the same exception occurred!! Sadly it did not resolve the problem...

**Comment by Ushmidave** [comment]
@ahmad-devlop use the annotation `[AnonymousUser]` on the post authentication method

**Comment by ahmad-devlop** [comment]
@Ushmidave as you see here [https://github.com/rxweb/RxWebCore/blob/f3b564bf5d108384a15c721140137907751dd87e/src/Samples/AspNetCore/Documentation%20Examples/HumanResourceApplication/HumanResourceApplication.Api/Controllers/Api/Core/AuthenticationController.cs#L40](url)

There is an attribute of `[AllowAnonymousUser]` and I tried to use this `[AnonymousUser]` but no namespace suggestions.

**Comment by Ushmidave** [comment]
@ahmad-devlop sorry it was a spelling mistake, use annotation  [AllowAnonymous] on the post authentication method

**Comment by ajayojha** [comment]
@ahmad-devlop I hope your concern has been resolved, I am closing this ticket, if there is any issue feel free to reopen this ticket.
