### ISSUE TITLE
Enhancement to the "Unique" function

### ISSUE THREAD

**Issue by Rlcolli4** [rxweb/rxweb#425]
### Description
Currently `unique` is good at validating against upper/lower case differences in various inputs, however if the user leaves a trailing space or leaves a space at the beginning of the input, the validator does not work.

### Describe the solution you'd like
Leading and trailing empty spaces should be trimmed when validating in `unique`

### Stackblitz
https://stackblitz.com/edit/unique-value-validation-in-formarray-reactive-forms-angu-2ffk5j?file=src%2Fapp%2Fapp.component.ts

**Comment by ajayojha** [comment]
the feature has been released in the 2.1.3
