### ISSUE TITLE
Trim validator doesn't work when used inside ComposeConfig

### ISSUE THREAD

**Issue by Xambey** [rxweb/rxweb#427]
# Describe the bug

trim() validator doesn't work when used inside ComposeConfig

# Expected Behavior

all validators from the ready config work

# To Reproduce

Example: 

```typescript
import { ComposeConfig } from '@rxweb/reactive-form-validators/models/config';
import {  RxwebValidators, trim } from '@rxweb/reactive-form-validators';

export function sysnameValidators(
  additionalConfig?: ComposeConfig
): ComposeConfig {
  return {
    validators: [
      RxwebValidators.required(),
      RxwebValidators.notEmpty(),
      RxwebValidators.maxLength({ value: 255, message: `Message` }),
      trim()
    ],
    ...additionalConfig
  };
}

export class User {

 @compose(sysnameValidators())
  login: string;
}

```

# Package Version
@rxweb/reactive-form-validators@2.1.2

**Comment by ajayojha** [comment]
@Xambey 'trim' is not a validator it's a sanitize decorator, so it won't work.

**Comment by Xambey** [comment]
Is it possible to add an array of sanitizers to ComposeConfig? I think that would be very helpful. I solved my problem as a result, creating a separate decorator, but this is a bad solution in my opinion

```typescript
export default function Name(additionalConfig?: BaseConfigFn<ComposeConfig>): (target: Object, propertyKey: string, parameterIndex?: any) => void {
  return (target: Object, propertyKey: string, parameterIndex?: any) => {
    trim()(target, propertyKey, parameterIndex);
    compose({
      validators: [
        RxwebValidators.required(),
        RxwebValidators.notEmpty(),
        RxwebValidators.maxLength({ value: 255, message: `Поле "Наименование" должно содержать не более {{1}} символов` }),
      ],
      ...additionalConfig
    })(target, propertyKey, parameterIndex);
  };
}
```

**Comment by ajayojha** [comment]
@Xambey I would like to know why you are mixing two things in one, I would suggest instead of creating the custom decorator and mingle up these things, use the existing validation decorator and sanitizer. If you have any specific case which cannot be achieved with the existing validation decorator and sanitizer then please share the exact use case so that I can do something intuitive.

**Comment by ajayojha** [comment]
@Xambey I hope your concern has been resolved, Hence I am closing this ticket. If there is any concern feel free to reopen this ticket.
