### ISSUE TITLE
Scrollbar is not working in Rx-tag

### ISSUE THREAD

**Issue by dotnetdev32radixweb** [rxweb/rxweb#428]
# Describe the bug

Scroll bar is not working in Rx-tag control of Angular. When we click on Up/Down arrow, item list get close. We also can't scroll through item list using keyboard arrow key. It is only working fine using mouse wheel.

# Expected Behavior
Up and Down arrow in scroll bar must be working and item list should remain open. We also can go through item list using keyboard arrow keys.

# Url (stackblitz or plunker or other)

Please refer attachment.

# Package Version

@rxweb/angular @ 0.0.7
@rxweb/dom @ 0.0.2-beta8
@rxweb/framework @ 0.0.1

**Comment by Ushmidave** [comment]
@dotnetdev32radixweb Here is the working example of rx-tag working with scrollbar working fine, kindly verify the necessary changes in your example : https://stackblitz.com/edit/rxweb-tag-item-ordering-hnjwhz?file=src/app/app.component.ts

**Comment by ajayojha** [comment]
@dotnetdev32radixweb Please update the package with the version of @rxweb/angular@0.0.19. Please refer to this working example (https://stackblitz.com/edit/rxweb-tag-item-ordering-vheyzv?file=src/app/app.component.ts).
