### ISSUE TITLE
Need help with rx-grid (With checkbox)

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#431]
[stackblitz](https://stackblitz.com/edit/rxweb-grid-paging-checkbox-gd2tsj?file=src%2Fapp%2Fapp.component.ts)

**Issue**: 
Currently, we are pushing static data in the second page to replicate the issue.
Step 1: Go to second page.
Step 2: check the header checkbox.
Step 3: Detail checkbox is not checked because source is not being updated.

Could you please help us with above issue?

This issue is in reference to https://github.com/rxweb/rxweb/issues/419

**Comment by ajayojha** [comment]
@rachanachag I have fixed this issue in the latest release, Please update the grid package version with 0.2.5. Please refer to the working stack blitz example (https://stackblitz.com/edit/rxweb-grid-paging-checkbox-axhagd?file=src%2Fapp%2Fapp.component.ts).
