### ISSUE TITLE
includedIn notIncludedIn

### ISSUE THREAD

**Issue by Dev2Cloud** [rxweb/rxweb#432]
### Description
It would be nice having a validator which check if an input value is included in an array of values, so that the user has to select one of them to be valid. Also the opposite, not included in, so that the user has to select a value or input a value which is not included in a given array (or enum)

Ive tried with oneOf or noneOf but I think its for array validation not string, which makes it harder to implement against a simple string input

### Describe the solution you'd like

An user has to select from an input or write a value which must one of a set of values:
["USD", "EUR", "SAR"]

If the user selects or writes CAD ie, it shouldnt be valid

**Comment by ajayojha** [comment]
@Dev2Cloud instead of creating a new validator, we have extended the feature of oneof validator. Now oneof validator also validates the string value. please refer to this [example](https://stackblitz.com/edit/angular-jagttq?file=src%2Fapp%2Fone-of-add.component.ts).
