### ISSUE TITLE
Need help with rx-grid (With checkbox)

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#433]
[Stackblitz](https://stackblitz.com/edit/rxweb-grid-paging-checkbox-yta5gv?file=src%2Fapp%2Fapp.component.ts)

Issue: 

1) For page index 1, when we click on check all, all items are selected 
2) Go to page index 2, when we click on select all, It is not working in this case.

In reference: to https://github.com/rxweb/rxweb/issues/431 and https://github.com/rxweb/rxweb/issues/419

**Comment by ajayojha** [comment]
@rachanachag please update the package version of @rxweb/grid@0.2.7, the issue has been fixed in the respective version. Please refer to this working example: https://stackblitz.com/edit/rxweb-grid-paging-checkbox-d5yntz?file=src%2Fapp%2Fapp.component.ts
