### ISSUE TITLE
rx-select does not automatically bind after lose focus (for existing value) 

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#434]
[stackblitz](https://stackblitz.com/edit/rxweb-select-value-qmxysb?file=src%2Fapp%2Fapp.component.html)

In the above stack-blitz, type "**ABC**" (data which already exists in the drop-down.
Click on anywhere else except dropdown.
Now, please select dropdown, at that time drop-down does not bind automatically. (Only record exists which has been searched, Dropdown will be bind only after clicking backspace)

In reference to https://github.com/rxweb/rxweb/issues/420

**Comment by ajayojha** [comment]
@rachanachag the issue has been fixed in the package(@rxweb/angular) version of 0.0.11, please update the same. Please refer to this working example (https://stackblitz.com/edit/rxweb-select-value-n9xayy?file=src%2Fapp%2Fapp.component.html)
