### ISSUE TITLE
Need close button feature in toaster 

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#435]
### Description
In current toaster we don't have close option in toaster 

As per our requirement we  need to add close option in toaster

![image](https://user-images.githubusercontent.com/48114976/98083508-774bf780-1ea0-11eb-8aec-fdf499037a12.png)

### Describe the solution you'd like
we need toaster like below image with close option

![Toastr](https://user-images.githubusercontent.com/48114976/98083307-2805c700-1ea0-11eb-8522-31a6543b3ab9.png)

**Comment by ajayojha** [comment]
@afzalmansuri Thanks for this ticket, I have released a new version(0.0.3), please update the same.
For showing the close icon you have to pass the additional parameter while calling the 'show' method of toastr class object. here is the code:

```js
this.show(message, ToastrMessageType.error, { autoHideDisable: true});
```

also, you have to add a css reference in the css file:
```css
.toast-close-display-none {
display:none;
}
```

Please let me know if there is any issue.

**Comment by afzalmansuri** [comment]
Thanks @ajayojha Sir for this feature. 
I have checked and working.

**Comment by ajayojha** [comment]
Thanks for the quick update, I am closing this ticket as no further action required on this.

**Comment by afzalmansuri** [comment]
Hi @ajayojha sir  as per you suggest i have update the package but if we need autoHide and toaster close button both then its not working.
See example : https://stackblitz.com/edit/toaster-message?file=src%2Fapp%2Ftoaster.ts

**Comment by afzalmansuri** [comment]
Hi @ajayojha Sir any update on this sir ?
