### ISSUE TITLE
Need to placeholder text  as non selectable text in rx-select

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#442]
### Description
In current version we can select placeholder text from the drop down 

### Describe the solution you'd like
 Place holder text should not selectable

**See below example of current drop down implementation**:
https://stackblitz.com/edit/angular-rx-select-check2-ifsxgd?file=src%2Fapp%2Fapp.component.ts

**Comment by ajayojha** [comment]
@afzalmansuri Please update the package with the version of 0.0.16, the feature is available in the respective version. You can use 'excludePlaceholder' property for excluding the property from the list. please refer to this example: https://stackblitz.com/edit/angular-rx-select-check2-jmyx9r?file=src%2Fapp%2Fdropdown%2Fdropdown.component.html
