### ISSUE TITLE
Rx-select navigation issue via tabbing

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#444]
# Bug
  Options in rx-select gets disappear when we move focus to rx-select control via tabbing. To see all the options again, we either need to change the value or refresh the page which should not be the case.

# Expected Behavior
  All the options which are passed as source to the dropdown should be visible regardless of whether the control is focused via mouse or via tabbing.

# To Reproduce
  Move to the control which is next to the rx-select dropdown. Now try to shift focus back to rx-select dropdown via **shift+tab**. Refer following attachments:-

### **Step 1)**
![img1](https://user-images.githubusercontent.com/61281539/100052039-1bdbac80-2e43-11eb-9646-3f123f8ed386.jpg)

### **Step 2)**
![img2](https://user-images.githubusercontent.com/61281539/100052074-2d24b900-2e43-11eb-93b6-df4ad61b8af4.jpg)

### **Step 3)**
![img3](https://user-images.githubusercontent.com/61281539/100052143-55acb300-2e43-11eb-94b2-c740354f17ba.jpg)

# Url (stackblitz)
https://stackblitz.com/edit/rxselect-navigation-issue?file=src/app/hello.component.html

# Package Version
@rxweb/angular@0.0.17

**Comment by mitanshu-patel** [comment]
@ajayojha  Can you please provide help regarding this issue?

**Comment by ajayojha** [comment]
@mitanshu-patel the issue has been fixed in the 0.0.19 version. Please update the package. Please refer to the working example (https://stackblitz.com/edit/rxselect-navigation-issue-ecaq6g?file=src/app/hello.component.html)
