### ISSUE TITLE
@rxweb/types IFormGroup.get return bad type

### ISSUE THREAD

**Issue by koloar** [rxweb/rxweb#448]
IFormGroup\<T>.get have return type IAbstactControl\<T> 
but i excepted some type in _T_ model

for example:
form: IFormGroup\<Person>;
x: Person; // {..., phone: string, ...}

when i do _this.form.get('phone')_
i get _IAbstractControl\<Person>_
but i excepted  _IAbstractControl\<string>_

version: "@rxweb/types": "^1.0.6",

**Comment by ajayojha** [comment]
@koloar it's working as expected. alike you are getting the ```IAbstractControl<Person, string>```, which is FormControl. It seems that I don't have to anything internally, if I missed something then please detailed the problem statement.

**Comment by ajayojha** [comment]
I am closing this ticket as no further update on this.
