### ISSUE TITLE
Popup Over Popup closing issue

### ISSUE THREAD

**Issue by rachanachag** [rxweb/rxweb#449]
When we open popup over popup then only topmost popup getting closed while closing main popup site is stuck and there is no error in console.

Note: I have referred https://github.com/rxweb/rxweb/issues/397 and Updated  "0.0.1" version of "@rxweb/js" and updated 'model.ts' as mentioned 

[stackblitz](https://stackblitz.com/edit/angular-rx-multi-popup-close-issue-x7tsfy?file=src%2Fapp%2Fmodal%2Fmodal.ts)

**Comment by Ushmidave** [comment]
@rachanachag replace the `destory` mehod to this code 

```js
destroy(componentRef) {
    return () => {
      if (componentRef) {
        componentRef.destroy();
        componentRef = undefined;
      }
    };
  }
```

**Comment by rachanachag** [comment]
It's working now. Thank you.
