### ISSUE TITLE
Inline Rx-Tag Control 

### ISSUE THREAD

**Issue by Kiran-Pawar** [rxweb/rxweb#451]
Description
 I have implemented rx-tag inline control in rx-grid for add operation, and it is binded properly. But when I click on inline add 
 button, then i am getting id of only first value that i have selected from rx-tag.and not getting all the other ids.so can you please 
 help me with this,how i will get string of all the ids that i have selected from rx-tag control.

And I also need to implement  inline textarea control in rx-grid.so can you please provide me some example of textarea and rx-tag control.I have to complete this task before 08/12/2020.so can you please help me out in this.

Expected Behavior
It should returns string of ids that i have selected in rx-tag instead of only one id. And example of inline textarea so that i can implment it in grid.

## Url

Package version
@rxweb/grid@^0.2.3

**Comment by Kiran-Pawar** [comment]
[
![RxTag_In_Grid](https://user-images.githubusercontent.com/61281626/101032759-ffa4e180-359f-11eb-87d7-474442badf56.PNG)
](url)

**Comment by ajayojha** [comment]
@Kiran-Pawar It would be great if you provide the stackblitz example so that I can help you out quickly.

**Comment by Kiran-Pawar** [comment]
ok, I will prepare stackblitz example and let you know about it

**Comment by Kiran-Pawar** [comment]
Hello @ajayojha ,I have implemented rx-tag and also getting comma seperated selected values . and for inline textarea getting this error "Object literal may only specify known properties, and 'textarea' does not exist in type 'TemplateConfig'.

so,I have added " textarea?:ElementConfig;" property in "node_modules\@rxweb\@rxweb\grid\interface\config\template-config.d.ts" file. and it is working.

But if package gets updated this change will overwrite.so can you please provide "textarea"  property in TemplateConfig

**Comment by Kiran-Pawar** [comment]
Hello @ajayojha, can you please update me on this package change

**Comment by Kiran-Pawar** [comment]
I have updated rx-grid version(@rxweb/grid@^0.2.8) and now able to implement inline text-area control properly. Thank you
