### ISSUE TITLE
Need autoHide and toaster close button both 

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#454]
# Describe the bug

Sir as per suggest in [435](https://github.com/rxweb/rxweb/issues/435)  we have update the package but if we need autoHide and toaster close button both then its not working.

# Url

See Stackblitz example
https://stackblitz.com/edit/toaster-message?file=src%2Fapp%2Ftoaster.ts

**Comment by ajayojha** [comment]
@afzalmansuri I have added a feature in the 0.0.4; please update the package of @rxweb/js. Please refer to this working example: https://stackblitz.com/edit/toaster-message-jshjrb?file=src%2Fapp%2Ftoaster.ts
