### ISSUE TITLE
Related Strongly Typed Form

### ISSUE THREAD

**Issue by radixdt1937** [rxweb/rxweb#455]
I faced error Cannot read property 'formGroup' of undefined and Cannot read property 'forEach' of undefined 
after refering this link
https://stackblitz.com/edit/strongly-typed-reactive-form?file=src%2Fapp%2Fstrongly-typed-reactive-form%2Fstrongly-typed-reactive-form.component.ts
I checked the code both local and stackblitz both are same but give formgroup error

and another project 
I used IFormGroup and IFormBuilder.
give error this.formbuilder.array([]) is not a function

**Comment by Ushmidave** [comment]
@radixdt1937  please provide a stackblitz link of your code or the code snippet of your implementation

**Comment by radixdt1937** [comment]
https://stackblitz.com/edit/angular-ivy-ouh3qc?file=src%2Fapp%2Fmodels%2Fpaper.ts

**Comment by ajayojha** [comment]
@radixdt1937 you are using angular ```FormBuilder``` instance for creating the FormGroup, if you want to access the property of 'modelInstance' then you have to use the 'RxFormBuilder' for creating the FormGroup. 

Sorry to say, but the provided example is incorrect, it's not clear what exactly you wanna achieve. If you are using RxFormBuilder then please refer to this documentation for [Strongly Typed](https://new.rxweb.io/how-to/stronglyType/decorators) and without RxFormBuilder then please refer to [this](https://new.rxweb.io/strongly-typed/angular-strongly-typed).

I am closing this ticket as no further action required on this.
