### ISSUE TITLE
Autocomplete feature in Rx-tag

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#456]
### Description
Requirement of autocomplete feature in rx-tag control same as available in rx-select.

### Solution
When user type any text in rx-tag control then data will bind through an API call based on that text. Value entered by user should be passed in queryparams (similar to rx-select where `[valueInQueryParams]` attribute is used). Also it should retain it's value i.e. when user selects option(s) in rx-tag and when the data is fetched then the selected values should bind in rx-tag

**Comment by mitanshu-patel** [comment]
@ajayojha can you please provide help regarding this feature request?

**Comment by Bibinthayyil** [comment]
@ajayojha I'm also looking for the autocomplete feature. Kindly help.
