### ISSUE TITLE
Multiple values support in  StartsWith, EndsWith and Contains validator

### ISSUE THREAD

**Issue by kalathiyan** [rxweb/rxweb#457]
### Description
need feature of pass multiple value in StartsWith, EndsWith and Contains validator,

### Describe the solution you'd like
when I have multiple strings which may be Start/End/Contains with input at that time I am not able to use this validator,
so need feature to pass multiple value in Validator

**Comment by ajayojha** [comment]
@kalathiyan Thanks for this feature request, This is available from 2.1.4 release. Please refer to this [example](https://stackblitz.com/edit/angular-3ww2vh?file=src%2Fapp%2Fends-with-add.component.ts).
