### ISSUE TITLE
Not getting value using BrowserStorage

### ISSUE THREAD

**Issue by mitanshu-patel** [rxweb/rxweb#459]
# Bug
 When a value is stored in localstorage using BrowserStorage class(itself extends ClientDataStorage) then the value gets stored successfully, but when that same value is fetched using `browserStorage.local.get() `method at that time it shows following console error:-
 
![storageError](https://user-images.githubusercontent.com/61281539/103862676-8c821400-50e5-11eb-820e-98164cd130bd.JPG)

**Note:-** This issue occurs only with some specific values(which I've used in given stackblitz example). And also works fine if `isEncryption` flag is passed **false** in `save()` and `get()` methods.

# Expected Behavior
When we try to get localstorage value using `browserStorage.local.get()` then value should get instead of showing console error. It should work fine when value is stored with encryption.

# To Reproduce
Save any value in localstorage using `browserStorage.local.save() `method and then try to fetch the same value using `browserStorage.local.get()` method(to reproduce the issue, please use the same value as used in given stackblitz example).

# Url (stackblitz)
https://stackblitz.com/edit/rxwebstorage-issue?file=src/app/hello.component.html

# Package Version
@rxweb/storage@0.0.2-beta2

**Comment by ajayojha** [comment]
@mitanshu-patel please provide the specific value which creates an issue after adding it into the local storage.

**Comment by mitanshu-patel** [comment]
@ajayojha  try storing this value in localstorage:- `rekha1.abc@gmail.com`. I've used this same value in given stackblitz example and it causes console error as mentioned.

**Comment by mitanshu-patel** [comment]
@ajayojha Can you please provide help regarding this issue?

**Comment by ajayojha** [comment]
@mitanshu-patel the issue has been fixed in the 0.0.2 release of @rxweb/storage, please update the same, here is the working example: https://stackblitz.com/edit/rxwebstorage-issue-xjrmbo?file=src%2Fapp%2Fapp.component.html
