### ISSUE TITLE
Directives not working in template driven form

### ISSUE THREAD

**Issue by freshdev1** [rxweb/rxweb#461]
## Describe the problem statement?
Cannot use directives with Template Driven form.

## The expected solution you would like
[numeric] or other validation directives should work as specified in the documentations.
## Url
https://stackblitz.com/edit/angular-ivy-qqwpoq?file=src%2Fapp%2Fapp.component.ts
## Package version
@rxweb/reactive-form-validators

**Comment by freshdev1** [comment]
Alright as per guidance from a user in gitter chat room I found the following documentation:

[Numeric Template Driven Directive](https://docs.rxweb.io/form-validations/numeric/template-driven/directives)

Working example:
[Stackblitz Example](https://stackblitz.com/angular/mngppvbkakb?file=src%2Fapp%2Fnumeric-add.component.html)

Hope this helps, closing the issue.

**Comment by Will-at-FreedomDev** [comment]
I think this should be reopened. For instance `[rxminDate]` and `[rxmaxDate]` do not seem to work per the [documentation](https://docs.rxweb.io/form-validations/maxDate/template-driven/directives) either.

It seems that the documentation should be updated to reflect the actual implementation. I am still learning how to use RxReactiveForms and followed the Template Driven video on their [Getting Started](https://docs.rxweb.io/getting-started) and that is also using the (assumingly) outdated validator property `[compare]` which led me to this issue (thank you @freshdev1 btw)
