### ISSUE TITLE
@loawercase sanitizer not working

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#462]
# Describe the bug
@lowercase sanitizer not working as expected

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-cw9my5?file=src%2Fapp%2Fsanitizer-lowercase.component.ts

**Comment by ajayojha** [comment]
@afzalmansuri the issue has been fixed in 0.0.1 release of @rxweb/sanitizers, please update the same, here is the working example: https://stackblitz.com/edit/angular-cw9my5-vg43da?file=src%2Fapp%2Fapp.module.ts
