### ISSUE TITLE
Validation not working properly when validators(required and credit card) are added to the form control 

### ISSUE THREAD

**Issue by MarcusCS** [rxweb/rxweb#464]
# Describe the bug

I've added required and credit card type validation to the form control. It is not working.  

# Expected Behavior

When there is an empty value in the form control it should display some message to the user and this works only when I remove the credit card validator. Both should work simultaneously.

# To Reproduce

Pick the example shown in the documentation for the credit card. And add an additional validator(required) to it. 

# Package Version
@rxweb/reactive-form-validators@2.1.2

**Comment by Ushmidave** [comment]
@MarcusCS You must perform multiple validations on one control using compose validator, refer this [example](https://stackblitz.com/edit/angular-yyetaz-6ykss2?file=src/app/credit-card-add.component.ts)

**Comment by MarcusCS** [comment]
Thanks.. I did not notice it.
