### ISSUE TITLE
Any update on the IP address mask, being able to enter 192.168.1.254 instead of 192.168.001.254

### ISSUE THREAD

**Issue by DuncanFaulkner** [rxweb/rxweb#465]
Creating a new issue as I think this has been forgotten.

Any update on the IP address mask, being able to enter 192.168.1.254 instead of 192.168.001.254

23rd Dec 2020 - Just wondering if having the ability to mask ip addresses is coming in the next release? 

I need the mask to accept either 192.168.1.254 and 192.168.100.254 as valid, at present we would have to add 192.168.001.254 which is not natural when adding IP addresses.

Thanks

_Originally posted by @DuncanFaulkner in https://github.com/rxweb/rxweb/issues/391#issuecomment-720424111_

**Comment by ajayojha** [comment]
@DuncanFaulkner Was busy with other priority work, It's in plan and will be available in the next release. I hope it will release on dated 01st Feb.

**Comment by ajayojha** [comment]
@DuncanFaulkner Thanks for creating this ticket.

**Comment by DuncanFaulkner** [comment]
any news on the next release?

**Comment by ajayojha** [comment]
@DuncanFaulkner This feature is already added in an earlier release (I don't remember when I have added this). Please refer to this [example](https://stackblitz.com/edit/angular-xe3v4m?file=src%2Fapp%2Fip-add.component.ts).
