### ISSUE TITLE
Popup issue with BrowserAnimationsModule 

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#469]
# Describe the bug
while adding **BrowserAnimationsModule** and while we are close the popup site getting stuk

# To Reproduce
Add **BrowserAnimationsModule** and open popup then close the popup

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-rx-multi-popup-close-issue-dydgwj?file=src%2Fapp%2Fapp.module.ts

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by ajayojha** [comment]
@afzalmansuri The issue has been fixed in the new version of @rxweb/js@0.0.5. Please update the same.
