### ISSUE TITLE
It's not compatible with Angular 5.x

### ISSUE THREAD

**Issue by pmestrum** [rxweb/rxweb#47]
It's not compatible with Angular 5.x
# Description
ERROR in node_modules/@rxweb/reactive-form-validators/services/rx-form-group.d.ts(1,51): error TS2305: Module '"/Users/mestrump/projects/work/MW_Credendo_Extranet/client/node_modules/@angular/forms/forms"' has no exported member 'AbstractControlOptions'.

AbstractControlOptions is an interface that is present in Angular since version 6.

**Comment by rxwebteam** [comment]
Hello Paul,
Can you please share your package.json file.

**Comment by pmestrum** [comment]
via mail?

"dependencies": {
  "@angular/animations": "^5.2.10",
  "@angular/cdk": "^5.2.5",
  "@angular/common": "^5.2.10",
  "@angular/compiler": "^5.2.10",
  "@angular/core": "^5.2.10",
  "@angular/forms": "^5.2.10",
  "@angular/http": "^5.2.10",
  "@angular/material": "^5.2.5",
  "@angular/platform-browser": "^5.2.10",
  "@angular/platform-browser-dynamic": "^5.2.10",
  "@angular/platform-server": "^5.2.10",
  "@angular/router": "^5.2.10",
  "@ng-bootstrap/ng-bootstrap": "^1.1.2",
  "@ng-select/ng-select": "^1.2.1",
  "@ngrx/router-store": "^5.2.0",
  "@ngrx/store": "^5.2.0",
  "@ngrx/store-devtools": "^5.2.0",
  "@ngx-loading-bar/core": "^2.2.0",
  "@ngx-loading-bar/http-client": "^2.2.0",
  "@ngx-translate/core": "^10.0.1",
  "@ngx-translate/http-loader": "^3.0.1",
  "@rxweb/reactive-form-validators": "^1.4.2",
  "angular-user-idle": "^1.1.0",
  "blob-util": "^2.0.2",
  "bootstrap": "^4.1.0",
  "bootstrap-4-grid": "^2.4.0",
  "bootstrap-sass": "^3.3.7",
  "classlist.js": "^1.1.20150312",
  "copy-webpack-plugin": "^4.5.1",
  "core-js": "^2.5.5",
  "file-saver": "^1.3.8",
  "font-awesome": "^4.7.0",
  "intl": "^1.2.5",
  "inuitcss": "6.0.0",
  "lodash": "^4.17.10",
  "merge": "^1.2.0",
  "mime-types": "^2.1.20",
  "moment": "^2.22.1",
  "mydatepicker": "^2.6.3",
  "ng2-dragula": "^1.5.0",
  "ng2-file-upload": "^1.3.0",
  "ng2-izitoast": "^2.0.0",
  "ngx-pagination": "^3.1.1",
  "object-hash": "^1.3.0",
  "priority-nav": "^1.0.12",
  "rxjs": "^5.6.0-forward-compat.4",
  "sass-mq": "^4.0.2",
  "tassign": "^1.0.0",
  "web-animations-js": "^2.3.1",
  "zone.js": "^0.8.26"
},

**Comment by rxwebteam** [comment]
Thanks Paul,
Will let you know, ASAP

**Comment by ajayojha** [comment]
I have released the new version "**1.4.3**" and it's working fine in Angular 5 project. 

Just for your reference, I have created [stackblitz ](https://stackblitz.com/edit/cross-field-date-validation-in-angular-with-rxweb-3cvcmb) project with your project angular package version and the latest version of rxweb. It is working as expected.

Please check in your project and let me know if there is any issue.

**Comment by pmestrum** [comment]
thanks a lot !  I’ll check it out

**Comment by ajayojha** [comment]
I hope the issue has been resolved in your project also. I am closing this issue. Feel free log new issue if there is any issue.
