### ISSUE TITLE
FormGroup.Get().ValueChanged has wrong type

### ISSUE THREAD

**Issue by mligtenberg** [rxweb/rxweb#470]
# Describe the bug

When subscribing on the ValueChanged from a IFormControl the actual type is the type of the formControl (most likely a string) but this library says that the entire form is returned.

# Expected Behavior

The IFormControl.ValueChanged is an observable of the value of the control, not of the value of the form.

# To Reproduce

add the following code to an existing form and replace "contentType" with an existing control in your form.

```typescript
this.form.get("contentType").valueChanges.subscribe((value) => console.log({value}));
```

you will see that the valueChanges observable returns the value of the control while the typing sugest that it returns the value of the entire form.

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/types@1.0.6

**Comment by mligtenberg** [comment]
workaround that I currently use is:
```typescript
this.form.get("contentType").valueChanges.subscribe((value) => console.log({value as any as string}));
```

**Comment by ajayojha** [comment]
@mligtenberg This issue has been fixed in the latest release.
