### ISSUE TITLE
Bug MinDate v2.1.0

### ISSUE THREAD

**Issue by kelvinsleonardo** [rxweb/rxweb#471]
# Describe the bug
When I use the validator minDate, the validation of the date is invalid.

# To Reproduce
Put value "06-02-2020" in field.
In version 2.0.0 is working

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/rxweb-min-date-validation-angular-reactive-form-nglbht?file=src%2Fapp%2Fapp.component.ts

# Package Version
@rxweb/reactive-form-validators":"^2.1.0

**Comment by kelvinsleonardo** [comment]
@ajayojha any idea?

**Comment by ajayojha** [comment]
I was busy in other work, I will start on this in next 2/3 day.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
@kelvinsleonardo Thanks for reporting this issue, this has been fixed in the 2.1.4 release.
