### ISSUE TITLE
Behavior of RxFormControl.reset() is not the same as FormControl.reset()

### ISSUE THREAD

**Issue by lkachun9129** [rxweb/rxweb#473]
# Describe the bug

I want to call reset() on RxFormControl without affecting its parent.

```ts
formControl.reset(null, { onSelf: true });
```

However, after checking the implementation of `reset()` in `RxFormControl`, it was found that the behavior of `reset()` was different to the one in `FormControl`

#### Implementation in FormControl
```ts
reset(formState: any = null, options: {onlySelf?: boolean, emitEvent?: boolean} = {}): void {
    this._applyFormState(formState);
    this.markAsPristine(options);
    this.markAsUntouched(options);
    this.setValue(this.value, options);
    this._pendingChange = false;
}
```

#### Implementation in RxFormControl
```ts
reset(value?: any) {
        if (value !== undefined)
            this.setValue(value);
        else
            this.setValue(this.getFormState(this._baseValue));
        this._dirty = false;
 }
```

# Expected Behavior

`reset()` should accept the option to suppress the propagation to parent control.

```ts
reset(value?: any, options: {onlySelf?: boolean, emitEvent?: boolean} = {}): void {
    if (value !== undefined)
        this.setValue(value, options);
    else
        this.setValue(this.getFormState(this._baseValue), options);
    this._dirty = false;
}
```

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/reactive-form-validators@2.1.2

**Comment by ajayojha** [comment]
@lkachun9129 this has been fixed in the latest release, please update the same.
