### ISSUE TITLE
Bug FormArray with conditionalExpression

### ISSUE THREAD

**Issue by kelvinsleonardo** [rxweb/rxweb#474]
# Describe the bug
When I use the validator required with conditionalExpression in formArray.

# To Reproduce
Put a value of 1 in the first, second and third fields. Check the third field.
Is there a problem adding asynchronously more elements. Check console.

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-5c1rcb?file=src%2Fapp%2Fapp.component.ts

# Package Version
@rxweb/reactive-form-validators": "^2.1.2

**Comment by simfyz** [comment]
I'm also facing same issues. Is there any fixes or workarounds? It's working only once. After that it's not triggering

**Comment by ajayojha** [comment]
@kelvinsleonardo & @simfyz I have updated the code of mentioned [stackblitz example](https://stackblitz.com/edit/angular-hwomra?file=src%2Fapp%2Fapp.component.html). Please use ```[formGroup]``` instead of ```[formGroupName]```.

Here is the change:

**Old**
```js
<ng-container [formGroupName]="i">
```

**New**
```js
<ng-container [formGroup]="ex">
```

I am closing this ticket as no further action is required on this.

**Comment by simfyz** [comment]
@ajayojha I have tried your solution. It is only working on the first change. After that conditionalExpression is not firing. Please respond if you have any idea or fixes.
