### ISSUE TITLE
File Upload with preview

### ISSUE THREAD

**Issue by prateekg415** [rxweb/rxweb#479]
### Description
Hi Team,

Modification to the current file control.

### Describe the solution you'd like

This is to request an add-on feature wherein files can be uploaded asynchronously and we see a thumbnail once file is uploaded.

**Comment by Ushmidave** [comment]
@prateekg415  This issue is been resolved in @rxweb/reactive-dynamic-forms@0.0.5, Here is the working [example](https://stackblitz.com/edit/angular-yskdw4-ejdgjb?file=src/app/app.component.html)

**Comment by ajayojha** [comment]
I am closing this ticket as the issue has been fixed in the new release.
