### ISSUE TITLE
IAbstractControl's get method type doesn't support a path

### ISSUE THREAD

**Issue by Jrubzjeknf** [rxweb/rxweb#480]
# Describe the bug

The current type definition of `get` is too restrictive. The following paths are marked as incorrect by the get method's type definition:

```ts
        // Valid path, but produces a type error  
        const countryName1 = this.formGroup.get('address.countryName');

        // Valid path, but produces a type error  
        const countryName2 = this.formGroup.get(['address', 'countryName']);
```

# Expected Behavior

No type error, for these are valid paths. With Angular strict template type checking becoming more common, this issue will start breaking builds.

The second example may be possible to correctly type check, but frankly, I don't mind either way.

# To Reproduce

See the stackblitz.

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/rxweb-types-strongly-typed-reactive-form-ceyr9w?file=src%2Fapp%2Fapp.component.ts

# Package Version
@rxweb/types@1.0.6

**Comment by Megingjard** [comment]
# Confirm the bug
I can confirm this problem. It is also a problem for simple paths, as:
`const address = this.formGroup.get('address');` 

Then `address.value` always retuns the type `User` and not `Address` which is wrong. 

# Workaround
We're working with a workaround and wrote an 
```
export class TypedFormDecorator {

  private static getForm<FORM>(that: any, formKey= 'form') {
    return (that[formKey] as IFormGroup<FORM>);
  }

  static getFormControl<FORM>(that: any, formKey= 'form'): <NAME extends keyof FORM>(controlName: NAME) => IAbstractControl<FORM[NAME]> {
    return <K extends keyof FORM>(controlName: K) => this.getForm<FORM>(that, formKey)?.controls[controlName];
  }

}
```
Then you can create the getFormControl function in your class:
```  
private form: IFormGroup<User>;
getFormControl = TypedFormDecorator.getFormControl<BuergerportalSearchForm>(this, 'form');
```

Then `const address = this.getFormControl('address').value` would correctly return the type `Address`

Nevertheless the bug should be fixed.

**Comment by ajayojha** [comment]
@Jrubzjeknf Thanks for sharing the detailed information.

### Won't fix
```js
        // Valid path, but produces a type error  
        const countryName1 = this.formGroup.get('address.countryName');

        // Valid path, but produces a type error  
        const countryName2 = this.formGroup.get(['address', 'countryName']);
```

### Fixed
```js
const address = this.formGroup.get('address').value; /// `Address` class object value will be returned.
```

Please the package with the latest version.
