### ISSUE TITLE
minSize config property not included  ValidationErrors  of fileSize validator

### ISSUE THREAD

**Issue by Serene47** [rxweb/rxweb#483]
# Describe the bug

First add a `fileSize` validator to file input control with  with `minSize`  and `maxSize` properties, then upload a file less than minsize specified. 

Now the `errors` of input control has the property `"fileSize": { "message": "", "refValues": [ currFileSize, maxFileSize ] } `. It contains maxFileSize , but no minFileSize

To give feedback to the user about min file size there is no reference to `minSize` property

# Expected Behavior

The validation errors should contain the `minSize` config property also. ( it will be better if showing which validation is failed )

# To Reproduce

1. Configure a file input control with `fileSize` validator with `minSize`  and `maxSize` properties.
2. Upload a file with size less than min size 

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-ivy-xsaxzq

# Package Version
@rxweb/reactive-form-validators@2.1.2

**Comment by ajayojha** [comment]
@Serene47 Thanks for reporting this issue, this has been fixed in the 2.1.4 release.
