### ISSUE TITLE
rx-select control

### ISSUE THREAD

**Issue by prince-developer-csharp** [rxweb/rxweb#484]
Hello Team,
Good Evening,

# Describe the bug
If I select the value in "rx-select" control  then again click the "rx-select" control after that selected value is showing if i change the value using up and down arrow keys then multiple focus showing on "rx-select" control.

#Expected Behavior
if i change the value in "rx-select" control using up and down arrow keys then single focus showing not multiple.

![Screenshot (235)](https://user-images.githubusercontent.com/60307000/114391147-c23b0b00-9bb4-11eb-980d-f90a9dfb971a.png)

# Package Version
@rxweb/angular@0.0.23

**Comment by ajayojha** [comment]
@prince-developer-csharp Kindly provide the stackblitz URL with reproducible steps

**Comment by prince-developer-csharp** [comment]
Stackblitz url :
https://stackblitz.com/edit/rxweb-select-value-farshp

Reproduce steps:
1. select the gujrat value in dropdown.
2.Again click the dropdown then enter arrow down key you will face the issue.
