### ISSUE TITLE
Password Validator - Add more special characters

### ISSUE THREAD

**Issue by mineminemine** [rxweb/rxweb#486]
### Description
https://stackblitz.com/angular/omokjooxypd?file=src%2Fapp%2Fpassword-validation.component.ts
The current password validator with the special characters turned on does not accept some special characters.
With the example link above, using 'test1!' will show that its valid but when putting in 'test1-' or 'test1_' will not be considered as valid inputs.
![1](https://user-images.githubusercontent.com/17585549/114961391-7c739080-9e9b-11eb-8dab-08cc15016144.png)
![2](https://user-images.githubusercontent.com/17585549/114961397-80071780-9e9b-11eb-8c86-815320b74af0.png)

So far these are the invalid special characters that I've found:
`~-_+=[\]';/

### Describe the solution you'd like
Allow for more special characters to be considered as valid inputs.
Or maybe allow us to add in our own custom special character validators.

**Comment by ajayojha** [comment]
@mineminemine Thanks for this feature request. This has been added in the latest release.
