### ISSUE TITLE
rx-select [enableFreeText] property not working

### ISSUE THREAD

**Issue by afzalmansuri** [rxweb/rxweb#487]
# Describe the bug
'enableFreeText' property not working in rx-select drop down as it is use for enable or disable enter free text in drop down

# Expected Behavior
'enableFreeText' property should work as not able to enter any text in drop down

**Comment by ajayojha** [comment]
@afzalmansuri share the stackblitz URL and please share a little bit more information.

**Comment by afzalmansuri** [comment]
Sure here is the Example
https://stackblitz.com/edit/angular-rx-select-check2-2faekj?file=src%2Fapp%2Fdropdown%2Fdropdown.component.html
