### ISSUE TITLE
Url Validator supports not FQDN correctly

### ISSUE THREAD

**Issue by anschm** [rxweb/rxweb#493]
# Describe the bug
I think the url validator is not working correct. Because he does not support the correct syntax of FQDN which is described on wikipedia: https://en.wikipedia.org/wiki/Fully_qualified_domain_name.

The url has to start with http or www. But 'myhost.example.com' is also a valid FQDN.

If you enter the following urls into the url validator you get the following results:
http://myhost.example.com -> valid
www.myhost.example.com -> valid
myhost.example.com -> not valid (should be valid)

# Expected Behavior

myhost.example.com is accepted by the url validator

# Package Version
@rxweb/reactive-form-validators@latest

**Comment by ajayojha** [comment]
@anschm This has been fixed in the latest release, please refer to this [example](https://stackblitz.com/angular/nvvogkgmxxdx?file=src%2Fapp%2Furl-add.component.ts).
