### ISSUE TITLE
Angular 12

### ISSUE THREAD

**Issue by mcheruvu** [rxweb/rxweb#503]
# Describe the bug
hello - I am trying to make rxweb/translate to work with Angular 12 and I running into issues with translate interceptor as it is not able to identify the JSON file. Any help and/or pointing me to an existing sample (with latest Angular). Appreciate your help. Thanks

# Package Version
@rxweb/translate@1.0.14

**Comment by ajayojha** [comment]
This has been answered on gitter, kindly refer to this [chat](https://gitter.im/rxweb-project/rxweb?at=60ddd870457e19611a2c1fc7).
