### ISSUE TITLE
Example code given is not working in AllOfSync topic

### ISSUE THREAD

**Issue by MilitPanchasara** [rxweb/rxweb#506]
# Description
conditionalExpression value defined in the wrong manner and it is not working, even in stackblitz code.
For example:
Current implementation (conditionalExpression defined inside of() method): 

_skills: ['',[], RxwebValidators.allOfAsync({validatorConfig:of({ matchValues: ["MVC", "AngularJS", "Angular 5", "C#", "Web Api", "SQL Server"], conditionalExpression: "x => x.department =='DotNet'" })})],_

Correct implementation (conditionalExpression should be outside of of() method):

_skills: ['',[], RxwebValidators.allOfAsync({validatorConfig:of({ matchValues: ["MVC", "AngularJS", "Angular 5", "C#", "Web Api", "SQL Server"]}), conditionalExpression: "x => x.department =='DotNet'" })],_

# Location
https://docs.rxweb.io/async-validators/allOfAsync/validators
https://stackblitz.com/angular/mdkvkoypray?file=src%2Fapp%2Fall-of-async-complete.component.ts

**Comment by Ushmidave** [comment]
@MilitPanchasara using a property outside of of() method is an incorrect way to use async validators,  i would recommend you to use @All validator in this case

**Comment by ajayojha** [comment]
@MilitPanchasara I am closing this ticket as there is no further update on this.
