### ISSUE TITLE
Compare return the field relating

### ISSUE THREAD

**Issue by elvispdosreis** [rxweb/rxweb#514]
how do I bring in the value in the error listing the related field **fieldName:'password'**, the component just brings me the values of the two fields

```
this.userFormGroup = this.formBuilder.group({
            password:['',], 
            confirm_password:['', RxwebValidators.compare({fieldName:'password' })], 
});
```

![image](https://user-images.githubusercontent.com/15267623/130626336-923e9dda-efb1-418f-9ac6-8776bf951d2b.png)

**Comment by ajayojha** [comment]
@elvispdosreis use ```{{0}}``` for self control value and ```{{1}}``` reference control value. 
here is the format of the error message.

```js
    ReactiveFormConfig.set({"validationMessage":{"compare":"Input ('{{0}}') does not match with this value '{{1}}'."}});
```

Please refer to this [example](https://stackblitz.com/edit/angular-lttjm8?file=src%2Fapp%2Fapp.component.ts).
