### ISSUE TITLE
Require a pagination at bottom and top of grid

### ISSUE THREAD

**Issue by radixdt2212** [rxweb/rxweb#517]
### Description
Presently the rx-grid has pagination at bottom.

whenever the list is long the user has to scroll at the very bottom to check whether there are more items/pages or not. this creates confusion for user to check other records.

### Solution
Any configuration to enable pagination at both top and bottom of rx-grid, as we don't want this solution for each and every grid, making it configurable which allows us to provide top and bottom pagination on selected grids based on our requirement.
![image](https://user-images.githubusercontent.com/85940721/133244462-c0fd4d6e-dfe7-4e25-9b36-4cbd5af6d16c.png)

**Comment by radixdt2212** [comment]
**Add on:** 

Please provide another configurable functionality to make column headers in grid as "sticky headers" similar to freeze panes (Top row) in MS Excel.

**Comment by ajayojha** [comment]
@radixdt2212 This feature is available in the latest release. 

You have to set the ```true``` value on the property of  ```cloneFooterOnTop``` in the GridDesigner class. here is the code example:
```js
export class AppGrid extends GridDesigner {
    constructor(source: any[], model: Function, gridConfiguration?: any) {
        super(source, model, gridConfiguration);
         this.cloneFooterOnTop = true;
    }
}
```

**Comment by ajayojha** [comment]
> **Add on:**
> 
> Please provide another configurable functionality to make column headers in grid as "sticky headers" similar to freeze panes (Top row) in MS Excel.

Kindly create a new ticket with enough information, one ticket is for only one feature request/issue.
