### ISSUE TITLE
Not work in Angular 12

### ISSUE THREAD

**Issue by se7ennlv** [rxweb/rxweb#535]
Hi All, 
I got this error in Angular version 12, Please suggest me

![image](https://user-images.githubusercontent.com/91686951/139274370-ce288b05-61c3-4d21-9cff-865e491905ae.png)

Thanks in advance

**Comment by se7ennlv** [comment]
resolved by changes "strictTemplates": false in tsconfig file

**Comment by ajayojha** [comment]
Ok, Thanks.. I am closing this ticket as no further action required on this.
