### ISSUE TITLE
rx-grid pagination scroll issue

### ISSUE THREAD

**Issue by divyesh-vadhavana** [rxweb/rxweb#552]
### Description

When rx-grid has horizontal scroll enabled due to larger table width, scroll also applies to pagination bar.

![rxgridPagination](https://user-images.githubusercontent.com/61281395/147818560-e7610320-97f9-4d2b-9842-3467789a4d4a.png)

### Describe the solution you'd like
Need feature to set pagination bar fixed in the page, while grid can have a horizontal scroll.

**Comment by hiteshthakor93** [comment]
@divyesh-vadhavana 
add 'table-responsive' class to the grid class property of 'tableClass'.

here is the code snippet:
`export class AppGrid extends GridDesigner {

  constructor(source: any[], model: Function, gridConfiguration?: any) {
    super(source, model, gridConfiguration);
    this.allowSorting = true;
    this.designClass.tableClass = "table-responsive table".split(' ');
    .....................
  }
}`

**Comment by divyesh-vadhavana** [comment]
@hiteshthakor93 
Thanks it works for me
