### ISSUE TITLE
Need link in tags in rx-tag

### ISSUE THREAD

**Issue by MilitPanchasara** [rxweb/rxweb#553]
### Description
We need tags with hyperlink in rx-tag, so that we can navigate on clicking particular tag.

### Describe the solution you'd like
I would like to have functionality to use URL or `<a href=""></a>` from source data in rx-tag, so that tag can have clickable links.

For example,
As shown in image below, I want to use 'url' or 'countryWithUrl' property from source in rx-tag. So when i click on existing tag, it should redirect me to that page.

Stackblitz link for this example: https://stackblitz.com/edit/rxweb-tag-item-ordering-gtkxmv?file=src%2Fapp%2Fapp.component.ts
![image](https://user-images.githubusercontent.com/47338058/151919023-01356778-1532-4977-9370-8a0f49e3eff0.png)

**Comment by hiteshthakor93** [comment]
@MilitPanchasara ,  We have introduced a click event for the selected tag.

Refer to the attached code snippet.

[https://stackblitz.com/edit/rxweb-tag-item-ordering-alnlka?file=src%2Fapp%2Fapp.component.ts](url)

**Comment by MilitPanchasara** [comment]
Thank you.
