### ISSUE TITLE
Unable to inject service inside AuthFilter 

### ISSUE THREAD

**Issue by viralchauhan** [rxweb/rxweb#559]
inside OnRequest() unable to use other service like localstorage service or other service. if we use undefined get 

we are unable to set dynamic filter 

# Package Version
@rxweb/<package-name>@xhrFilter

**Comment by viralchauhan** [comment]
do not use this library because due to no one response if you struggle.

**Comment by ajayojha** [comment]
@viralchauhan Sorry, I was not available during that time. I hope your issue has been resolved or found an alternative way. If still there is an issue then post the issue in detail.

**Comment by viralchauhan** [comment]
@ajayojha  Please check first My issues i have clear mention in AuthFilter. i am not able to other service inject dependency injection . for example inside AuthFilter 

Constructer(private viewService: ViewService){
                   //geting viewService is null

}

**Comment by ajayojha** [comment]
Please refer to this [example](https://stackblitz.com/edit/angular-nkmcqc-rufy17?file=src%2Fapp%2Fapp.component.ts). I have created a [ViewService](https://stackblitz.com/edit/angular-nkmcqc-rufy17?file=src%2Fapp%2Fview.service.ts) Class and this is to be used in [HeaderFilter](https://stackblitz.com/edit/angular-nkmcqc-rufy17?file=src%2Fapp%2Fheader-filter.ts).

**Comment by viralchauhan** [comment]
@ajayojha  i have used Angular 13.2.2 version this version not work.

**Comment by ajayojha** [comment]
Would be great if you share the error detail, the above-provided solution is for getting the service instance instead of null.

**Comment by viralchauhan** [comment]
@ajayojha  Please verify. i am not able to install RXWEB lib in stackblitz Angular 13

**Comment by viralchauhan** [comment]
Please find URl : https://stackblitz.com/edit/angular-13-template-fv2mmm

**Comment by viralchauhan** [comment]
Not work without test close this isues. we are not recomdeation other.
