### ISSUE TITLE
Search with special characters not working as expected in Rx-Tag

### ISSUE THREAD

**Issue by MilitPanchasara** [rxweb/rxweb#594]
# Description
When string with special characters like + or * is entered in the Rx-Tag element, it is not able fetch expected data in dropdown.

For example,
In below attached screenshot, user is trying to search "a+ ", but expected result is not shown in dropdown.
![image](https://user-images.githubusercontent.com/47338058/189845498-dbeb49d6-02a5-4de4-b235-a2e532541c36.png)

# Expected Behavior
It should fetch all the records with exact match of the input string.

In current example, it should fetch "A+ grade" record only.

# To Reproduce
Here is the link to demo project to reproduce the same issue:
https://stackblitz.com/edit/rxweb-tag-item-ordering-bentbf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Enter any word with special character and **Space** after any special character, it will show wrong or no records in dropdown.

# Possible cause of issue:
Filter functionality in rx-tag is not escaping special characters while applying Regex for filtering, because of which wrong records are getting fetched.

# Package Version
@rxweb/angular@0.0.28

**Comment by dotnetdev57radixweb** [comment]
@MilitPanchasara, try with the latest version.

**Comment by hiteshthakor93** [comment]
@MilitPanchasara, try with the latest version.

**Comment by MilitPanchasara** [comment]
Thanks @hiteshthakor93 for the fix. It is working with latest version (@rxweb/angular@0.0.30).
