### ISSUE TITLE
"lessThan" and "greaterThan" validators not working correctly

### ISSUE THREAD

**Issue by maxiwer** [rxweb/rxweb#601]
# Describe the bug
I've created two properties of a component in an angular project, let's name them "lessDate" and "greaterDate". Placing them inside of [FormBuilder's group](https://angular.io/api/forms/FormBuilder#methods) constructor, I've started attaching validators for them - among them was `RxwebValidators.lessThan` validator:
```
form = this.fb.group({
    lessDate: [
      this.lessDate,
      [
        RxwebValidators.notEmpty(),
        RxwebValidators.lessThan({
          fieldName: 'greaterDate',
          message: this.translate.get('someErrorMessage'),
        }),
      ],
    ],
    greaterDate: [this.greaterDate, [RxwebValidators.notEmpty()]],
  });
  ```
  My concern is - the "lessThan" validator doesn't work correctly for dates comparison.

# Expected Behavior
"lessThan" validator correctly compares two dates.

# To Reproduce
```
lessDate: any = new Date();
greaterDate: Date = new Date();

form = this.fb.group({
    lessDate: [
      this.lessDate,
      [
        RxwebValidators.notEmpty(),
        RxwebValidators.lessThan({
          fieldName: 'greaterDate',
          message: this.translate.get('someErrorMessage'),
        }),
      ],
    ],
    greaterDate: [this.greaterDate, [RxwebValidators.notEmpty()]],
  });
  ```
# Package Version
@rxweb/reactive-form-validators@^2.1.7

**Comment by ajayojha** [comment]
@maxiwer please use `minDate` & `maxDate` validator according to your need, instead `lessThan` & `greaterThan`. 

Hence, I am closing this ticket as no further action is required on this :). feel free to create new ticket if there is any issue or have some queries.
