### ISSUE TITLE
pattern validator is not working properly

### ISSUE THREAD

**Issue by rxcontributortwo** [rxweb/rxweb#62]
# Describe the bug

 "only alpha" and "only digit" is not working correctly and messages in "only digit" also conflicts.

# Expected Behavior

pattern should work correctly on the basis of defined expression.

# Url (stackblitz or plunker or other)

https://rxweb.io/form-validations/pattern/validators

# Package Version
@rxweb/<package-name>@1.4.5

**Comment by ajayojha** [comment]
you have to remove the inverted comma in the regex parameter. I have changed in the code and here is the working example : https://stackblitz.com/edit/angular-fzvtcm?file=src/app/pattern-complete.component.ts

Earlier:
RegExp('/^[A-Za-z]+$/')
Now:
RegExp(/^[A-Za-z]+$/)

As no further actions required on this, I am closing this issue.
