### ISSUE TITLE
Decorators prop, propArray, propObject do not work in stackblitz.com

### ISSUE THREAD

**Issue by gleonova** [rxweb/rxweb#65]
## Describe the problem statement?

Code example for decorators prop, propArray, propObject do not work in stackblitz.com
## The expected solution you would like
Sample code to actually work
## Url
https://rxweb.io/decorators/propArray/decorators
## Package version
@rxweb/

**Comment by ajayojha** [comment]
Thanks for reporting this issue.
In our next update, this will be corrected. I have corrected in stackblitz propArray example for you and now it is working in the stackblitz, please refer this link: https://stackblitz.com/edit/angular-nhasjc?file=src/app/app.module.ts

**Comment by gleonova** [comment]
Thank you for you quick response! The example is working now.

Best regards,

Galina Leonova
Contractor - NexGen Technologies, Inc
Software Developer
Bureau of Land Management
National Operations Center
Division of Information Resources Management

O 303-236-6457

M 719-201-5050

-----------------------------------------------------------------------------------------------------------------------

Confidentiality Notice:  This electronic communications is intended only
for the use of the individual(s) or entity(ies) to which it is addressed
and may contain information that is privileged, confidential and exempt
from disclosure under applicable law.  If you have received this
communication in error, please do not distribute, delete the original
message, and notify the sender.

**Comment by ajayojha** [comment]
We have corrected the example of propArray on our rxweb.io site. If you face any issue related to the decorator based validation. Feel free to chat on our gitter channel or log the issue. 

I am closing this issue, As I don't see further action on this.
