### ISSUE TITLE
how to add new element  to a form with propArray

### ISSUE THREAD

**Issue by gleonova** [rxweb/rxweb#68]
## Describe the problem statement?
In yous example for propArray() you have address decorated with propArray(). I need to have multiple addresses that user can add with "Add Address" button. I found examples of  how to implement it with Angular form builder, but I can't figure out or find example how to do it with RxFormBuilder. Is it even possible? Can you provide an example?

## The expected solution you would like
Sample of code to add multiple addresses on form built with RxFormBuilder. 
## Package version
@rxweb/

**Comment by michelebenolli** [comment]
Hi Ajay, I need to extend the form by including a simple array of strings. The provided code allows adding an array of objects, which is not what I'm looking for. Is there a way to use RxFormBuilder to add a FormArray of FormControl for handling a list of strings with multiple input fields?
