### ISSUE TITLE
Allow second property in time validator not working properly

### ISSUE THREAD

**Issue by rxcontributorone** [rxweb/rxweb#7]
### Current Behavior
Time validator allow seconds property is not working property , when allow seconds property is set true it does not allow seconds 
### Expected behavior
 Allow second property should allow second if it is set true
###URL
https://stackblitz.com/github/rxweb/rxweb/tree/dev/docs/examples/reactive-form-validators/time/complete-rxweb-time-validation-add-angular-reactive-form
###Browser
Any Browser

**Comment by ajayojha** [comment]
Thanks
