### ISSUE TITLE
docs: unique validator docs

### ISSUE THREAD

**Issue by technicalarchitectrx** [rxweb/rxweb#73]
# Description
Add a documentation of Unique validator on the site and readme doc of validators. 
refer this https://stackoverflow.com/questions/53933229/update-form-with-validation-not-working-until-atleast-one-value-is-changed-in-th/53943990#53943990

**Comment by ajayojha** [comment]
Unique documentation is available on our site. Please refer this link: https://rxweb.io/form-validations/unique/validators
