### ISSUE TITLE
Add new FQDN validator

### ISSUE THREAD

**Issue by NiravMistry096** [rxweb/rxweb#76]
### Description

Required new validator for FQDN.

### Describe the solution you'd like

It should validate as per below wiki link,
Wiki Link : https://en.wikipedia.org/wiki/Fully_qualified_domain_name

**Comment by ajayojha** [comment]
@NiravMistry096, Later on, will plan the same if I get one more request from another user. As there are lots of other items are in priority, Hence I am closing this issue.
