### ISSUE TITLE
Required Global Release Identifier ( GRid ) validator

### ISSUE THREAD

**Issue by niraj096** [rxweb/rxweb#79]
### Description

Required GRid ( Global Release Identifier ) validator

### Describe the solution you'd like

you can find the details from wiki : https://en.wikipedia.org/wiki/Global_Release_Identifier

**Comment by ajayojha** [comment]
This feature is provided in our new release 1.5.0. For more information please refer release note : https://github.com/rxweb/rxweb/releases
