### ISSUE TITLE
Abstraction is not possible in model class

### ISSUE THREAD

**Issue by guidosreis** [rxweb/rxweb#88]
Bug report or Feature request
Abstraction is not possible.
I created a class with common attributes and exteded it in other more specific classes, as you can see bellow:
```
// user.model.ts
class Contact {
  @required()
  type: string;

  @required()
  primary: boolean;
}

export class PhoneNumber extends Contact {
  @required()
  phoneNumber: string;
}

export class Email extends Contact {
  @required()
  @email()
  email: string;
}

export class User {
  @required()
  usernamename: string;

  @propArray(PhoneNumber)
  phoneNumbers: PhoneNumber[];

  @propArray(Email)
  emails: Email[];
}
```

```
// app.component.ts
...
export class AppComponent implements OnInit {
  userForm: FormGroup;

  constructor(private fb: RxFormBuilder) { }

  ngOnInit() {
    const user = new User();
    const phoneNumber = new PhoneNumber();
    const email = new Email();

    user.phoneNumbers = new Array<PhoneNumber>();
    user.phoneNumbers.push(phoneNumber);

    user.emails = new Array<Email>();
    user.emails.push(email);

    this.userForm = this.fb.formGroup(user);
  }

  ...
}
```

# Expected Behavior
I expected that the `type` and `primary` controls would be present in the phoneNumber group object, but they are not. Only the attribute defined in PhoneNumber class is part of the phoneNumber group, the same happens with Email class and email group.

# To Reproduce
You can see the console in the example app I built in SlackBlitz.

# Url (stackblitz or plunker or other)
https://stackblitz.com/edit/angular-7ubjvp

# Package Version
@rxweb/reactive-form-validators@1.4.7

**Comment by ajayojha** [comment]
Currently this feature is not available in our framework, It's in our pipeline, I will try to release this in our next 1.6.0 release or 1.7.0 release. Currently I am marking this as milestone of 1.6.0.

**Comment by ajayojha** [comment]
We have added this feature in our 1.5.0 release. Please use the latest version. I have updated the package your provided stackblitz link, please refer this link : https://stackblitz.com/edit/angular-5simde?file=src/app/app.component.ts

Please let me know if there is any issue.

**Comment by guidosreis** [comment]
That is awesome! Thank you!
