### ISSUE TITLE
Locale Specific VAT 

### ISSUE THREAD

**Issue by rxwebteam** [rxweb/rxweb#97]
If someone wants validate VAT no based on country 
For India 11 digit number followed by V, to indicate VAT TIN (or by C to indicate CST TIN). First two digits identify the state where the registration is done, e.g. 27 indicates State of Maharashtra. 

For Canada 9 Characters

**Comment by ajayojha** [comment]
@rxwebteam , Later on, will plan the same if I get one more request from another user. As there are lots of other items are in priority, Hence I am closing this issue.
